/*
 * Copyright (c) 2021 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"golang.org/x/mod/modfile"
)

const modulePath = "github.com/goplus/builder/tools/ai"

func main() {
	sourcePath := flag.String("source", "", "path to the source go.mod file")
	outputPath := flag.String("output", "", "path to the generated Go file")
	flag.Parse()

	if *sourcePath == "" || *outputPath == "" {
		fmt.Fprintln(os.Stderr, "usage: genversion -source <go.mod> -output <file>")
		os.Exit(2)
	}

	version, err := moduleVersionFromFile(*sourcePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate builder ai version: %v\n", err)
		os.Exit(1)
	}

	content := []byte(fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package builderai

const Version = %q
`, version))

	if existing, err := os.ReadFile(*outputPath); err == nil && bytes.Equal(existing, content) {
		return
	} else if err != nil && !os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "read output %s: %v\n", *outputPath, err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "create output dir for %s: %v\n", *outputPath, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*outputPath, content, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write output %s: %v\n", *outputPath, err)
		os.Exit(1)
	}
}

func moduleVersionFromFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read source %s: %w", path, err)
	}

	file, err := modfile.Parse(path, data, nil)
	if err != nil {
		return "", fmt.Errorf("parse source %s: %w", path, err)
	}

	for _, req := range file.Require {
		if req.Mod.Path == modulePath {
			return req.Mod.Version, nil
		}
	}
	return "", fmt.Errorf("module %q not found in %s", modulePath, path)
}
