changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix

  categories:
    - title: New Features
      labels:
        - enhancement

    - title: Bug Fixes
      labels:
        - bug

    - title: Platform Improvements
      labels:
        - android
        - ios
        - linux
        - mac
        - web
        - windows

    - title: Dependency Updates
      labels:
        - dependencies

    - title: Documentation
      labels:
        - documentation

    - title: Other Changes
      labels:
        - "*"
