//go:build !js

/*
------------------------------------------------------------------------------
//   This code was generated by template ffi_gdextension_interface.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_gdextension_interface.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------
*/
package wrap

/*
#include <stdlib.h>
*/
import "C"

import (
	"fmt"
	. "github.com/goplus/spbase/mathf"
	. "github.com/goplus/spx/v2/pkg/gdspx/internal/ffi"
	. "github.com/goplus/spx/v2/pkg/gdspx/pkg/engine"
	"reflect"
	"unsafe"
)

func BindMgr(mgrs []IManager) {
	for _, mgr := range mgrs {
		switch v := mgr.(type) {
		case IAudioMgr:
			AudioMgr = v

		case ICameraMgr:
			CameraMgr = v

		case IDebugMgr:
			DebugMgr = v

		case IExtMgr:
			ExtMgr = v

		case IInputMgr:
			InputMgr = v

		case INavigationMgr:
			NavigationMgr = v

		case IPenMgr:
			PenMgr = v

		case IPhysicMgr:
			PhysicMgr = v

		case IPlatformMgr:
			PlatformMgr = v

		case IResMgr:
			ResMgr = v

		case ISceneMgr:
			SceneMgr = v

		case ISpriteMgr:
			SpriteMgr = v

		case ITilemapMgr:
			TilemapMgr = v

		case IUiMgr:
			UiMgr = v

		default:
			panic(fmt.Sprintf("engine init error : unknown manager type %s", reflect.TypeOf(mgr).String()))
		}
	}
}

type audioMgr struct {
	baseMgr
}
type cameraMgr struct {
	baseMgr
}
type debugMgr struct {
	baseMgr
}
type extMgr struct {
	baseMgr
}
type inputMgr struct {
	baseMgr
}
type navigationMgr struct {
	baseMgr
}
type penMgr struct {
	baseMgr
}
type physicMgr struct {
	baseMgr
}
type platformMgr struct {
	baseMgr
}
type resMgr struct {
	baseMgr
}
type sceneMgr struct {
	baseMgr
}
type spriteMgr struct {
	baseMgr
}
type tilemapMgr struct {
	baseMgr
}
type uiMgr struct {
	baseMgr
}

func createMgrs() []IManager {
	addManager(&audioMgr{})
	addManager(&cameraMgr{})
	addManager(&debugMgr{})
	addManager(&extMgr{})
	addManager(&inputMgr{})
	addManager(&navigationMgr{})
	addManager(&penMgr{})
	addManager(&physicMgr{})
	addManager(&platformMgr{})
	addManager(&resMgr{})
	addManager(&sceneMgr{})
	addManager(&spriteMgr{})
	addManager(&tilemapMgr{})
	addManager(&uiMgr{})
	return mgrs
}

// call gdextension interface functions

func (pself *audioMgr) StopAll() {
	CallAudioStopAll()
}
func (pself *audioMgr) CreateAudio() Object {
	retValue := CallAudioCreateAudio()
	return ToObject(retValue)
}
func (pself *audioMgr) DestroyAudio(obj Object) {
	arg0 := ToGdObj(obj)
	CallAudioDestroyAudio(arg0)
}
func (pself *audioMgr) SetPitch(obj Object, pitch float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(pitch)
	CallAudioSetPitch(arg0, arg1)
}
func (pself *audioMgr) GetPitch(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallAudioGetPitch(arg0)
	return ToFloat64(retValue)
}
func (pself *audioMgr) SetPan(obj Object, pan float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(pan)
	CallAudioSetPan(arg0, arg1)
}
func (pself *audioMgr) GetPan(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallAudioGetPan(arg0)
	return ToFloat64(retValue)
}
func (pself *audioMgr) SetVolume(obj Object, volume float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(volume)
	CallAudioSetVolume(arg0, arg1)
}
func (pself *audioMgr) GetVolume(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallAudioGetVolume(arg0)
	return ToFloat64(retValue)
}
func (pself *audioMgr) PlayWithAttenuation(obj Object, path string, owner_id Object, attenuation float64, max_distance float64) int64 {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdObj(owner_id)
	arg3 := ToGdFloat(attenuation)
	arg4 := ToGdFloat(max_distance)
	retValue := CallAudioPlayWithAttenuation(arg0, arg1, arg2, arg3, arg4)
	return ToInt64(retValue)
}
func (pself *audioMgr) Play(obj Object, path string) int64 {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallAudioPlay(arg0, arg1)
	return ToInt64(retValue)
}
func (pself *audioMgr) Pause(aid int64) {
	arg0 := ToGdInt(aid)
	CallAudioPause(arg0)
}
func (pself *audioMgr) Resume(aid int64) {
	arg0 := ToGdInt(aid)
	CallAudioResume(arg0)
}
func (pself *audioMgr) Stop(aid int64) {
	arg0 := ToGdInt(aid)
	CallAudioStop(arg0)
}
func (pself *audioMgr) SetLoop(aid int64, loop bool) {
	arg0 := ToGdInt(aid)
	arg1 := ToGdBool(loop)
	CallAudioSetLoop(arg0, arg1)
}
func (pself *audioMgr) GetLoop(aid int64) bool {
	arg0 := ToGdInt(aid)
	retValue := CallAudioGetLoop(arg0)
	return ToBool(retValue)
}
func (pself *audioMgr) GetTimer(aid int64) float64 {
	arg0 := ToGdInt(aid)
	retValue := CallAudioGetTimer(arg0)
	return ToFloat64(retValue)
}
func (pself *audioMgr) SetTimer(aid int64, time float64) {
	arg0 := ToGdInt(aid)
	arg1 := ToGdFloat(time)
	CallAudioSetTimer(arg0, arg1)
}
func (pself *audioMgr) IsPlaying(aid int64) bool {
	arg0 := ToGdInt(aid)
	retValue := CallAudioIsPlaying(arg0)
	return ToBool(retValue)
}
func (pself *cameraMgr) GetCameraPosition() Vec2 {
	retValue := CallCameraGetCameraPosition()
	return ToVec2(retValue)
}
func (pself *cameraMgr) SetCameraPosition(position Vec2) {
	arg0 := ToGdVec2(position)
	CallCameraSetCameraPosition(arg0)
}
func (pself *cameraMgr) GetCameraZoom() Vec2 {
	retValue := CallCameraGetCameraZoom()
	return ToVec2(retValue)
}
func (pself *cameraMgr) SetCameraZoom(size Vec2) {
	arg0 := ToGdVec2(size)
	CallCameraSetCameraZoom(arg0)
}
func (pself *cameraMgr) GetViewportRect() Rect2 {
	retValue := CallCameraGetViewportRect()
	return ToRect2(retValue)
}
func (pself *cameraMgr) GetGlobalCameraRect() Rect2 {
	retValue := CallCameraGetGlobalCameraRect()
	return ToRect2(retValue)
}
func (pself *cameraMgr) SetCameraLimit(side int64, limit int64) {
	arg0 := ToGdInt(side)
	arg1 := ToGdInt(limit)
	CallCameraSetCameraLimit(arg0, arg1)
}
func (pself *cameraMgr) SetCameraSmoothing(enabled bool) {
	arg0 := ToGdBool(enabled)
	CallCameraSetCameraSmoothing(arg0)
}
func (pself *debugMgr) DebugDrawCircle(pos Vec2, radius float64, color Color) {
	arg0 := ToGdVec2(pos)
	arg1 := ToGdFloat(radius)
	arg2 := ToGdColor(color)
	CallDebugDebugDrawCircle(arg0, arg1, arg2)
}
func (pself *debugMgr) DebugDrawRect(pos Vec2, size Vec2, color Color) {
	arg0 := ToGdVec2(pos)
	arg1 := ToGdVec2(size)
	arg2 := ToGdColor(color)
	CallDebugDebugDrawRect(arg0, arg1, arg2)
}
func (pself *debugMgr) DebugDrawLine(from Vec2, to Vec2, color Color) {
	arg0 := ToGdVec2(from)
	arg1 := ToGdVec2(to)
	arg2 := ToGdColor(color)
	CallDebugDebugDrawLine(arg0, arg1, arg2)
}
func (pself *extMgr) RequestExit(exit_code int64) {
	arg0 := ToGdInt(exit_code)
	CallExtRequestExit(arg0)
}
func (pself *extMgr) RequestReset(exit_code int64) {
	arg0 := ToGdInt(exit_code)
	CallExtRequestReset(arg0)
}
func (pself *extMgr) RequestRestart() {
	CallExtRequestRestart()
}
func (pself *extMgr) OnRuntimePanic(msg string) {
	arg0Str := C.CString(msg)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	CallExtOnRuntimePanic(arg0)
}
func (pself *extMgr) Pause() {
	CallExtPause()
}
func (pself *extMgr) Resume() {
	CallExtResume()
}
func (pself *extMgr) IsPaused() bool {
	retValue := CallExtIsPaused()
	return ToBool(retValue)
}
func (pself *extMgr) NextFrame() {
	CallExtNextFrame()
}
func (pself *extMgr) SetLayerSorterMode(mode int64) {
	arg0 := ToGdInt(mode)
	CallExtSetLayerSorterMode(arg0)
}
func (pself *inputMgr) GetGlobalMousePos() Vec2 {
	retValue := CallInputGetGlobalMousePos()
	return ToVec2(retValue)
}
func (pself *inputMgr) GetKey(key int64) bool {
	arg0 := ToGdInt(key)
	retValue := CallInputGetKey(arg0)
	return ToBool(retValue)
}
func (pself *inputMgr) GetMouseState(mouse_id int64) bool {
	arg0 := ToGdInt(mouse_id)
	retValue := CallInputGetMouseState(arg0)
	return ToBool(retValue)
}
func (pself *inputMgr) GetKeyState(key int64) int64 {
	arg0 := ToGdInt(key)
	retValue := CallInputGetKeyState(arg0)
	return ToInt64(retValue)
}
func (pself *inputMgr) GetAxis(neg_action string, pos_action string) float64 {
	arg0Str := C.CString(neg_action)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1Str := C.CString(pos_action)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallInputGetAxis(arg0, arg1)
	return ToFloat64(retValue)
}
func (pself *inputMgr) IsActionPressed(action string) bool {
	arg0Str := C.CString(action)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallInputIsActionPressed(arg0)
	return ToBool(retValue)
}
func (pself *inputMgr) IsActionJustPressed(action string) bool {
	arg0Str := C.CString(action)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallInputIsActionJustPressed(arg0)
	return ToBool(retValue)
}
func (pself *inputMgr) IsActionJustReleased(action string) bool {
	arg0Str := C.CString(action)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallInputIsActionJustReleased(arg0)
	return ToBool(retValue)
}
func (pself *navigationMgr) SetupPathFinderWithSize(grid_size Vec2, cell_size Vec2, with_jump bool, with_debug bool) {
	arg0 := ToGdVec2(grid_size)
	arg1 := ToGdVec2(cell_size)
	arg2 := ToGdBool(with_jump)
	arg3 := ToGdBool(with_debug)
	CallNavigationSetupPathFinderWithSize(arg0, arg1, arg2, arg3)
}
func (pself *navigationMgr) SetupPathFinder(with_jump bool) {
	arg0 := ToGdBool(with_jump)
	CallNavigationSetupPathFinder(arg0)
}
func (pself *navigationMgr) SetObstacle(obj Object, enabled bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(enabled)
	CallNavigationSetObstacle(arg0, arg1)
}
func (pself *navigationMgr) FindPath(p_from Vec2, p_to Vec2, with_jump bool) Array {
	arg0 := ToGdVec2(p_from)
	arg1 := ToGdVec2(p_to)
	arg2 := ToGdBool(with_jump)
	retValue := CallNavigationFindPath(arg0, arg1, arg2)
	return ToArray(retValue)
}
func (pself *penMgr) DestroyAllPens() {
	CallPenDestroyAllPens()
}
func (pself *penMgr) CreatePen() Object {
	retValue := CallPenCreatePen()
	return ToObject(retValue)
}
func (pself *penMgr) DestroyPen(obj Object) {
	arg0 := ToGdObj(obj)
	CallPenDestroyPen(arg0)
}
func (pself *penMgr) PenStamp(obj Object) {
	arg0 := ToGdObj(obj)
	CallPenPenStamp(arg0)
}
func (pself *penMgr) MovePenTo(obj Object, position Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(position)
	CallPenMovePenTo(arg0, arg1)
}
func (pself *penMgr) PenDown(obj Object, move_by_mouse bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(move_by_mouse)
	CallPenPenDown(arg0, arg1)
}
func (pself *penMgr) PenUp(obj Object) {
	arg0 := ToGdObj(obj)
	CallPenPenUp(arg0)
}
func (pself *penMgr) SetPenColorTo(obj Object, color Color) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdColor(color)
	CallPenSetPenColorTo(arg0, arg1)
}
func (pself *penMgr) ChangePenBy(obj Object, property int64, amount float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(property)
	arg2 := ToGdFloat(amount)
	CallPenChangePenBy(arg0, arg1, arg2)
}
func (pself *penMgr) SetPenTo(obj Object, property int64, value float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(property)
	arg2 := ToGdFloat(value)
	CallPenSetPenTo(arg0, arg1, arg2)
}
func (pself *penMgr) ChangePenSizeBy(obj Object, amount float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(amount)
	CallPenChangePenSizeBy(arg0, arg1)
}
func (pself *penMgr) SetPenSizeTo(obj Object, size float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(size)
	CallPenSetPenSizeTo(arg0, arg1)
}
func (pself *penMgr) SetPenStampTexture(obj Object, texture_path string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(texture_path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallPenSetPenStampTexture(arg0, arg1)
}
func (pself *physicMgr) Raycast(from Vec2, to Vec2, collision_mask int64) Object {
	arg0 := ToGdVec2(from)
	arg1 := ToGdVec2(to)
	arg2 := ToGdInt(collision_mask)
	retValue := CallPhysicRaycast(arg0, arg1, arg2)
	return ToObject(retValue)
}
func (pself *physicMgr) CheckCollision(from Vec2, to Vec2, collision_mask int64, collide_with_areas bool, collide_with_bodies bool) bool {
	arg0 := ToGdVec2(from)
	arg1 := ToGdVec2(to)
	arg2 := ToGdInt(collision_mask)
	arg3 := ToGdBool(collide_with_areas)
	arg4 := ToGdBool(collide_with_bodies)
	retValue := CallPhysicCheckCollision(arg0, arg1, arg2, arg3, arg4)
	return ToBool(retValue)
}
func (pself *physicMgr) CheckTouchedCameraBoundaries(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallPhysicCheckTouchedCameraBoundaries(arg0)
	return ToInt64(retValue)
}
func (pself *physicMgr) CheckTouchedCameraBoundary(obj Object, board_type int64) bool {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(board_type)
	retValue := CallPhysicCheckTouchedCameraBoundary(arg0, arg1)
	return ToBool(retValue)
}
func (pself *physicMgr) SetCollisionSystemType(is_collision_by_alpha bool) {
	arg0 := ToGdBool(is_collision_by_alpha)
	CallPhysicSetCollisionSystemType(arg0)
}
func (pself *physicMgr) SetGlobalGravity(gravity float64) {
	arg0 := ToGdFloat(gravity)
	CallPhysicSetGlobalGravity(arg0)
}
func (pself *physicMgr) GetGlobalGravity() float64 {
	retValue := CallPhysicGetGlobalGravity()
	return ToFloat64(retValue)
}
func (pself *physicMgr) SetGlobalFriction(friction float64) {
	arg0 := ToGdFloat(friction)
	CallPhysicSetGlobalFriction(arg0)
}
func (pself *physicMgr) GetGlobalFriction() float64 {
	retValue := CallPhysicGetGlobalFriction()
	return ToFloat64(retValue)
}
func (pself *physicMgr) SetGlobalAirDrag(air_drag float64) {
	arg0 := ToGdFloat(air_drag)
	CallPhysicSetGlobalAirDrag(arg0)
}
func (pself *physicMgr) GetGlobalAirDrag() float64 {
	retValue := CallPhysicGetGlobalAirDrag()
	return ToFloat64(retValue)
}
func (pself *physicMgr) CheckCollisionRect(pos Vec2, size Vec2, collision_mask int64) Array {
	arg0 := ToGdVec2(pos)
	arg1 := ToGdVec2(size)
	arg2 := ToGdInt(collision_mask)
	retValue := CallPhysicCheckCollisionRect(arg0, arg1, arg2)
	return ToArray(retValue)
}
func (pself *physicMgr) CheckCollisionCircle(pos Vec2, radius float64, collision_mask int64) Array {
	arg0 := ToGdVec2(pos)
	arg1 := ToGdFloat(radius)
	arg2 := ToGdInt(collision_mask)
	retValue := CallPhysicCheckCollisionCircle(arg0, arg1, arg2)
	return ToArray(retValue)
}
func (pself *physicMgr) RaycastWithDetails(from Vec2, to Vec2, ignore_sprites Array, collision_mask int64, collide_with_areas bool, collide_with_bodies bool) Array {
	arg0 := ToGdVec2(from)
	arg1 := ToGdVec2(to)
	arg2 := ToGdArray(ignore_sprites)
	arg3 := ToGdInt(collision_mask)
	arg4 := ToGdBool(collide_with_areas)
	arg5 := ToGdBool(collide_with_bodies)
	retValue := CallPhysicRaycastWithDetails(arg0, arg1, arg2, arg3, arg4, arg5)
	return ToArray(retValue)
}
func (pself *platformMgr) SetStretchMode(enable bool) {
	arg0 := ToGdBool(enable)
	CallPlatformSetStretchMode(arg0)
}
func (pself *platformMgr) SetStretchAspect(is_keep bool) {
	arg0 := ToGdBool(is_keep)
	CallPlatformSetStretchAspect(arg0)
}
func (pself *platformMgr) SetStretchContentScale(width int64, height int64) {
	arg0 := ToGdInt(width)
	arg1 := ToGdInt(height)
	CallPlatformSetStretchContentScale(arg0, arg1)
}
func (pself *platformMgr) SetWindowPosition(pos Vec2) {
	arg0 := ToGdVec2(pos)
	CallPlatformSetWindowPosition(arg0)
}
func (pself *platformMgr) GetWindowPosition() Vec2 {
	retValue := CallPlatformGetWindowPosition()
	return ToVec2(retValue)
}
func (pself *platformMgr) SetWindowSize(width int64, height int64, with_content_scale bool) {
	arg0 := ToGdInt(width)
	arg1 := ToGdInt(height)
	arg2 := ToGdBool(with_content_scale)
	CallPlatformSetWindowSize(arg0, arg1, arg2)
}
func (pself *platformMgr) GetWindowSize() Vec2 {
	retValue := CallPlatformGetWindowSize()
	return ToVec2(retValue)
}
func (pself *platformMgr) SetWindowTitle(title string) {
	arg0Str := C.CString(title)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	CallPlatformSetWindowTitle(arg0)
}
func (pself *platformMgr) GetWindowTitle() string {
	retValue := CallPlatformGetWindowTitle()
	return ToString(retValue)
}
func (pself *platformMgr) SetWindowFullscreen(enable bool) {
	arg0 := ToGdBool(enable)
	CallPlatformSetWindowFullscreen(arg0)
}
func (pself *platformMgr) IsWindowFullscreen() bool {
	retValue := CallPlatformIsWindowFullscreen()
	return ToBool(retValue)
}
func (pself *platformMgr) SetDebugMode(enable bool) {
	arg0 := ToGdBool(enable)
	CallPlatformSetDebugMode(arg0)
}
func (pself *platformMgr) IsDebugMode() bool {
	retValue := CallPlatformIsDebugMode()
	return ToBool(retValue)
}
func (pself *platformMgr) GetTimeScale() float64 {
	retValue := CallPlatformGetTimeScale()
	return ToFloat64(retValue)
}
func (pself *platformMgr) SetTimeScale(time_scale float64) {
	arg0 := ToGdFloat(time_scale)
	CallPlatformSetTimeScale(arg0)
}
func (pself *platformMgr) GetPersistantDataDir() string {
	retValue := CallPlatformGetPersistantDataDir()
	return ToString(retValue)
}
func (pself *platformMgr) SetPersistantDataDir(path string) {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	CallPlatformSetPersistantDataDir(arg0)
}
func (pself *platformMgr) IsInPersistantDataDir(path string) bool {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallPlatformIsInPersistantDataDir(arg0)
	return ToBool(retValue)
}
func (pself *resMgr) CreateAnimation(p_sprite_type string, p_anim_name string, p_json_ctx string, fps int64, is_atlas bool) {
	arg0Str := C.CString(p_sprite_type)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1Str := C.CString(p_anim_name)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2Str := C.CString(p_json_ctx)
	arg2 := (GdString)(arg2Str)
	defer C.free(unsafe.Pointer(arg2Str))
	arg3 := ToGdInt(fps)
	arg4 := ToGdBool(is_atlas)
	CallResCreateAnimation(arg0, arg1, arg2, arg3, arg4)
}
func (pself *resMgr) SetLoadMode(is_direct_mode bool) {
	arg0 := ToGdBool(is_direct_mode)
	CallResSetLoadMode(arg0)
}
func (pself *resMgr) GetLoadMode() bool {
	retValue := CallResGetLoadMode()
	return ToBool(retValue)
}
func (pself *resMgr) GetBoundFromAlpha(p_path string) Rect2 {
	arg0Str := C.CString(p_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallResGetBoundFromAlpha(arg0)
	return ToRect2(retValue)
}
func (pself *resMgr) GetImageSize(p_path string) Vec2 {
	arg0Str := C.CString(p_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallResGetImageSize(arg0)
	return ToVec2(retValue)
}
func (pself *resMgr) ReadAllText(p_path string) string {
	arg0Str := C.CString(p_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallResReadAllText(arg0)
	return ToString(retValue)
}
func (pself *resMgr) HasFile(p_path string) bool {
	arg0Str := C.CString(p_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallResHasFile(arg0)
	return ToBool(retValue)
}
func (pself *resMgr) ReloadTexture(path string) {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	CallResReloadTexture(arg0)
}
func (pself *resMgr) FreeStr(str string) {
	arg0Str := C.CString(str)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	CallResFreeStr(arg0)
}
func (pself *resMgr) SetDefaultFont(font_path string) {
	arg0Str := C.CString(font_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	CallResSetDefaultFont(arg0)
}
func (pself *sceneMgr) ChangeSceneToFile(path string) {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	CallSceneChangeSceneToFile(arg0)
}
func (pself *sceneMgr) DestroyAllSprites() {
	CallSceneDestroyAllSprites()
}
func (pself *sceneMgr) ReloadCurrentScene() int64 {
	retValue := CallSceneReloadCurrentScene()
	return ToInt64(retValue)
}
func (pself *sceneMgr) UnloadCurrentScene() {
	CallSceneUnloadCurrentScene()
}
func (pself *sceneMgr) ClearPureSprites() {
	CallSceneClearPureSprites()
}
func (pself *sceneMgr) CreatePureSprite(texture_path string, pos Vec2, zindex int64) {
	arg0Str := C.CString(texture_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1 := ToGdVec2(pos)
	arg2 := ToGdInt(zindex)
	CallSceneCreatePureSprite(arg0, arg1, arg2)
}
func (pself *sceneMgr) DestroyPureSprite(id Object) {
	arg0 := ToGdObj(id)
	CallSceneDestroyPureSprite(arg0)
}
func (pself *sceneMgr) CreateRenderSprite(texture_path string, pos Vec2, degree float64, scale Vec2, zindex int64, pivot Vec2) Object {
	arg0Str := C.CString(texture_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1 := ToGdVec2(pos)
	arg2 := ToGdFloat(degree)
	arg3 := ToGdVec2(scale)
	arg4 := ToGdInt(zindex)
	arg5 := ToGdVec2(pivot)
	retValue := CallSceneCreateRenderSprite(arg0, arg1, arg2, arg3, arg4, arg5)
	return ToObject(retValue)
}
func (pself *sceneMgr) CreateStaticSprite(texture_path string, pos Vec2, degree float64, scale Vec2, zindex int64, pivot Vec2, collider_type int64, collider_pivot Vec2, collider_params Array) Object {
	arg0Str := C.CString(texture_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1 := ToGdVec2(pos)
	arg2 := ToGdFloat(degree)
	arg3 := ToGdVec2(scale)
	arg4 := ToGdInt(zindex)
	arg5 := ToGdVec2(pivot)
	arg6 := ToGdInt(collider_type)
	arg7 := ToGdVec2(collider_pivot)
	arg8 := ToGdArray(collider_params)
	retValue := CallSceneCreateStaticSprite(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	return ToObject(retValue)
}
func (pself *spriteMgr) SetDontDestroyOnLoad(obj Object) {
	arg0 := ToGdObj(obj)
	CallSpriteSetDontDestroyOnLoad(arg0)
}
func (pself *spriteMgr) SetProcess(obj Object, is_on bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(is_on)
	CallSpriteSetProcess(arg0, arg1)
}
func (pself *spriteMgr) SetPhysicProcess(obj Object, is_on bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(is_on)
	CallSpriteSetPhysicProcess(arg0, arg1)
}
func (pself *spriteMgr) SetTypeName(obj Object, type_name string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(type_name)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallSpriteSetTypeName(arg0, arg1)
}
func (pself *spriteMgr) SetPivot(obj Object, pivot Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(pivot)
	CallSpriteSetPivot(arg0, arg1)
}
func (pself *spriteMgr) GetPivot(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetPivot(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) SetChildPosition(obj Object, path string, pos Vec2) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdVec2(pos)
	CallSpriteSetChildPosition(arg0, arg1, arg2)
}
func (pself *spriteMgr) GetChildPosition(obj Object, path string) Vec2 {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallSpriteGetChildPosition(arg0, arg1)
	return ToVec2(retValue)
}
func (pself *spriteMgr) SetChildRotation(obj Object, path string, rot float64) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdFloat(rot)
	CallSpriteSetChildRotation(arg0, arg1, arg2)
}
func (pself *spriteMgr) GetChildRotation(obj Object, path string) float64 {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallSpriteGetChildRotation(arg0, arg1)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) SetChildScale(obj Object, path string, scale Vec2) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdVec2(scale)
	CallSpriteSetChildScale(arg0, arg1, arg2)
}
func (pself *spriteMgr) GetChildScale(obj Object, path string) Vec2 {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallSpriteGetChildScale(arg0, arg1)
	return ToVec2(retValue)
}
func (pself *spriteMgr) CheckCollision(obj Object, target Object, is_src_trigger bool, is_dst_trigger bool) bool {
	arg0 := ToGdObj(obj)
	arg1 := ToGdObj(target)
	arg2 := ToGdBool(is_src_trigger)
	arg3 := ToGdBool(is_dst_trigger)
	retValue := CallSpriteCheckCollision(arg0, arg1, arg2, arg3)
	return ToBool(retValue)
}
func (pself *spriteMgr) CheckCollisionWithPoint(obj Object, point Vec2, is_trigger bool) bool {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(point)
	arg2 := ToGdBool(is_trigger)
	retValue := CallSpriteCheckCollisionWithPoint(arg0, arg1, arg2)
	return ToBool(retValue)
}
func (pself *spriteMgr) CreateBackdrop(path string) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallSpriteCreateBackdrop(arg0)
	return ToObject(retValue)
}
func (pself *spriteMgr) CreateSprite(path string, pos Vec2) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1 := ToGdVec2(pos)
	retValue := CallSpriteCreateSprite(arg0, arg1)
	return ToObject(retValue)
}
func (pself *spriteMgr) CloneSprite(obj Object) Object {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteCloneSprite(arg0)
	return ToObject(retValue)
}
func (pself *spriteMgr) DestroySprite(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteDestroySprite(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) IsSpriteAlive(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsSpriteAlive(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) SetPosition(obj Object, pos Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(pos)
	CallSpriteSetPosition(arg0, arg1)
}
func (pself *spriteMgr) GetPosition(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetPosition(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) SetRotation(obj Object, rot float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(rot)
	CallSpriteSetRotation(arg0, arg1)
}
func (pself *spriteMgr) GetRotation(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetRotation(arg0)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) SetScale(obj Object, scale Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(scale)
	CallSpriteSetScale(arg0, arg1)
}
func (pself *spriteMgr) GetScale(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetScale(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) SetRenderScale(obj Object, scale Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(scale)
	CallSpriteSetRenderScale(arg0, arg1)
}
func (pself *spriteMgr) GetRenderScale(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetRenderScale(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) SetColor(obj Object, color Color) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdColor(color)
	CallSpriteSetColor(arg0, arg1)
}
func (pself *spriteMgr) GetColor(obj Object) Color {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetColor(arg0)
	return ToColor(retValue)
}
func (pself *spriteMgr) SetMaterialShader(obj Object, path string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallSpriteSetMaterialShader(arg0, arg1)
}
func (pself *spriteMgr) GetMaterialShader(obj Object) string {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetMaterialShader(arg0)
	return ToString(retValue)
}
func (pself *spriteMgr) SetMaterialParams(obj Object, effect string, amount float64) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(effect)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdFloat(amount)
	CallSpriteSetMaterialParams(arg0, arg1, arg2)
}
func (pself *spriteMgr) GetMaterialParams(obj Object, effect string) float64 {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(effect)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallSpriteGetMaterialParams(arg0, arg1)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) SetMaterialParamsVec(obj Object, effect string, x float64, y float64, z float64, w float64) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(effect)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdFloat(x)
	arg3 := ToGdFloat(y)
	arg4 := ToGdFloat(z)
	arg5 := ToGdFloat(w)
	CallSpriteSetMaterialParamsVec(arg0, arg1, arg2, arg3, arg4, arg5)
}
func (pself *spriteMgr) SetMaterialParamsVec4(obj Object, effect string, vec4 Vec4) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(effect)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdVec4(vec4)
	CallSpriteSetMaterialParamsVec4(arg0, arg1, arg2)
}
func (pself *spriteMgr) GetMaterialParamsVec4(obj Object, effect string) Vec4 {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(effect)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallSpriteGetMaterialParamsVec4(arg0, arg1)
	return ToVec4(retValue)
}
func (pself *spriteMgr) SetMaterialParamsColor(obj Object, effect string, color Color) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(effect)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdColor(color)
	CallSpriteSetMaterialParamsColor(arg0, arg1, arg2)
}
func (pself *spriteMgr) GetMaterialParamsColor(obj Object, effect string) Color {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(effect)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallSpriteGetMaterialParamsColor(arg0, arg1)
	return ToColor(retValue)
}
func (pself *spriteMgr) SetTextureAltas(obj Object, path string, rect2 Rect2) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdRect2(rect2)
	CallSpriteSetTextureAltas(arg0, arg1, arg2)
}
func (pself *spriteMgr) SetTexture(obj Object, path string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallSpriteSetTexture(arg0, arg1)
}
func (pself *spriteMgr) SetTextureAltasDirect(obj Object, path string, rect2 Rect2) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdRect2(rect2)
	CallSpriteSetTextureAltasDirect(arg0, arg1, arg2)
}
func (pself *spriteMgr) SetTextureDirect(obj Object, path string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallSpriteSetTextureDirect(arg0, arg1)
}
func (pself *spriteMgr) GetTexture(obj Object) string {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetTexture(arg0)
	return ToString(retValue)
}
func (pself *spriteMgr) SetVisible(obj Object, visible bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(visible)
	CallSpriteSetVisible(arg0, arg1)
}
func (pself *spriteMgr) GetVisible(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetVisible(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) GetZIndex(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetZIndex(arg0)
	return ToInt64(retValue)
}
func (pself *spriteMgr) SetZIndex(obj Object, z int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(z)
	CallSpriteSetZIndex(arg0, arg1)
}
func (pself *spriteMgr) PlayAnim(obj Object, p_name string, p_speed float64, isLoop bool, p_revert bool) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(p_name)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdFloat(p_speed)
	arg3 := ToGdBool(isLoop)
	arg4 := ToGdBool(p_revert)
	CallSpritePlayAnim(arg0, arg1, arg2, arg3, arg4)
}
func (pself *spriteMgr) PlayBackwardsAnim(obj Object, p_name string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(p_name)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallSpritePlayBackwardsAnim(arg0, arg1)
}
func (pself *spriteMgr) PauseAnim(obj Object) {
	arg0 := ToGdObj(obj)
	CallSpritePauseAnim(arg0)
}
func (pself *spriteMgr) StopAnim(obj Object) {
	arg0 := ToGdObj(obj)
	CallSpriteStopAnim(arg0)
}
func (pself *spriteMgr) IsPlayingAnim(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsPlayingAnim(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) SetAnim(obj Object, p_name string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(p_name)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallSpriteSetAnim(arg0, arg1)
}
func (pself *spriteMgr) GetAnim(obj Object) string {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetAnim(arg0)
	return ToString(retValue)
}
func (pself *spriteMgr) SetAnimFrame(obj Object, p_frame int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(p_frame)
	CallSpriteSetAnimFrame(arg0, arg1)
}
func (pself *spriteMgr) GetAnimFrame(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetAnimFrame(arg0)
	return ToInt64(retValue)
}
func (pself *spriteMgr) SetAnimSpeedScale(obj Object, p_speed_scale float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(p_speed_scale)
	CallSpriteSetAnimSpeedScale(arg0, arg1)
}
func (pself *spriteMgr) GetAnimSpeedScale(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetAnimSpeedScale(arg0)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) GetAnimPlayingSpeed(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetAnimPlayingSpeed(arg0)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) SetAnimCentered(obj Object, p_center bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(p_center)
	CallSpriteSetAnimCentered(arg0, arg1)
}
func (pself *spriteMgr) IsAnimCentered(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsAnimCentered(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) SetAnimOffset(obj Object, p_offset Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(p_offset)
	CallSpriteSetAnimOffset(arg0, arg1)
}
func (pself *spriteMgr) GetAnimOffset(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetAnimOffset(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) SetAnimFlipH(obj Object, p_flip bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(p_flip)
	CallSpriteSetAnimFlipH(arg0, arg1)
}
func (pself *spriteMgr) IsAnimFlippedH(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsAnimFlippedH(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) SetAnimFlipV(obj Object, p_flip bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(p_flip)
	CallSpriteSetAnimFlipV(arg0, arg1)
}
func (pself *spriteMgr) IsAnimFlippedV(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsAnimFlippedV(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) GetCurrentAnimName(obj Object) string {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetCurrentAnimName(arg0)
	return ToString(retValue)
}
func (pself *spriteMgr) SetVelocity(obj Object, velocity Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(velocity)
	CallSpriteSetVelocity(arg0, arg1)
}
func (pself *spriteMgr) GetVelocity(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetVelocity(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) IsOnFloor(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsOnFloor(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) IsOnFloorOnly(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsOnFloorOnly(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) IsOnWall(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsOnWall(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) IsOnWallOnly(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsOnWallOnly(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) IsOnCeiling(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsOnCeiling(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) IsOnCeilingOnly(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsOnCeilingOnly(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) GetLastMotion(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetLastMotion(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) GetPositionDelta(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetPositionDelta(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) GetFloorNormal(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetFloorNormal(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) GetWallNormal(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetWallNormal(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) GetRealVelocity(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetRealVelocity(arg0)
	return ToVec2(retValue)
}
func (pself *spriteMgr) MoveAndSlide(obj Object) {
	arg0 := ToGdObj(obj)
	CallSpriteMoveAndSlide(arg0)
}
func (pself *spriteMgr) SetGravity(obj Object, gravity float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(gravity)
	CallSpriteSetGravity(arg0, arg1)
}
func (pself *spriteMgr) GetGravity(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetGravity(arg0)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) SetMass(obj Object, mass float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(mass)
	CallSpriteSetMass(arg0, arg1)
}
func (pself *spriteMgr) GetMass(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetMass(arg0)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) AddForce(obj Object, force Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(force)
	CallSpriteAddForce(arg0, arg1)
}
func (pself *spriteMgr) AddImpulse(obj Object, impulse Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(impulse)
	CallSpriteAddImpulse(arg0, arg1)
}
func (pself *spriteMgr) SetPhysicsMode(obj Object, mode int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(mode)
	CallSpriteSetPhysicsMode(arg0, arg1)
}
func (pself *spriteMgr) GetPhysicsMode(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetPhysicsMode(arg0)
	return ToInt64(retValue)
}
func (pself *spriteMgr) SetUseGravity(obj Object, enabled bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(enabled)
	CallSpriteSetUseGravity(arg0, arg1)
}
func (pself *spriteMgr) IsUseGravity(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsUseGravity(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) SetGravityScale(obj Object, scale float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(scale)
	CallSpriteSetGravityScale(arg0, arg1)
}
func (pself *spriteMgr) GetGravityScale(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetGravityScale(arg0)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) SetDrag(obj Object, drag float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(drag)
	CallSpriteSetDrag(arg0, arg1)
}
func (pself *spriteMgr) GetDrag(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetDrag(arg0)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) SetFriction(obj Object, friction float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(friction)
	CallSpriteSetFriction(arg0, arg1)
}
func (pself *spriteMgr) GetFriction(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetFriction(arg0)
	return ToFloat64(retValue)
}
func (pself *spriteMgr) SetCollisionLayer(obj Object, layer int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(layer)
	CallSpriteSetCollisionLayer(arg0, arg1)
}
func (pself *spriteMgr) GetCollisionLayer(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetCollisionLayer(arg0)
	return ToInt64(retValue)
}
func (pself *spriteMgr) SetCollisionMask(obj Object, mask int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(mask)
	CallSpriteSetCollisionMask(arg0, arg1)
}
func (pself *spriteMgr) GetCollisionMask(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetCollisionMask(arg0)
	return ToInt64(retValue)
}
func (pself *spriteMgr) SetTriggerLayer(obj Object, layer int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(layer)
	CallSpriteSetTriggerLayer(arg0, arg1)
}
func (pself *spriteMgr) GetTriggerLayer(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetTriggerLayer(arg0)
	return ToInt64(retValue)
}
func (pself *spriteMgr) SetTriggerMask(obj Object, mask int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(mask)
	CallSpriteSetTriggerMask(arg0, arg1)
}
func (pself *spriteMgr) GetTriggerMask(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteGetTriggerMask(arg0)
	return ToInt64(retValue)
}
func (pself *spriteMgr) SetColliderRect(obj Object, center Vec2, size Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(center)
	arg2 := ToGdVec2(size)
	CallSpriteSetColliderRect(arg0, arg1, arg2)
}
func (pself *spriteMgr) SetColliderCircle(obj Object, center Vec2, radius float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(center)
	arg2 := ToGdFloat(radius)
	CallSpriteSetColliderCircle(arg0, arg1, arg2)
}
func (pself *spriteMgr) SetColliderCapsule(obj Object, center Vec2, size Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(center)
	arg2 := ToGdVec2(size)
	CallSpriteSetColliderCapsule(arg0, arg1, arg2)
}
func (pself *spriteMgr) SetCollisionEnabled(obj Object, enabled bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(enabled)
	CallSpriteSetCollisionEnabled(arg0, arg1)
}
func (pself *spriteMgr) IsCollisionEnabled(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsCollisionEnabled(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) SetTriggerRect(obj Object, center Vec2, size Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(center)
	arg2 := ToGdVec2(size)
	CallSpriteSetTriggerRect(arg0, arg1, arg2)
}
func (pself *spriteMgr) SetTriggerCircle(obj Object, center Vec2, radius float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(center)
	arg2 := ToGdFloat(radius)
	CallSpriteSetTriggerCircle(arg0, arg1, arg2)
}
func (pself *spriteMgr) SetTriggerCapsule(obj Object, center Vec2, size Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(center)
	arg2 := ToGdVec2(size)
	CallSpriteSetTriggerCapsule(arg0, arg1, arg2)
}
func (pself *spriteMgr) SetTriggerEnabled(obj Object, trigger bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(trigger)
	CallSpriteSetTriggerEnabled(arg0, arg1)
}
func (pself *spriteMgr) IsTriggerEnabled(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallSpriteIsTriggerEnabled(arg0)
	return ToBool(retValue)
}
func (pself *spriteMgr) CheckCollisionByColor(obj Object, color Color, color_threshold float64, alpha_threshold float64) bool {
	arg0 := ToGdObj(obj)
	arg1 := ToGdColor(color)
	arg2 := ToGdFloat(color_threshold)
	arg3 := ToGdFloat(alpha_threshold)
	retValue := CallSpriteCheckCollisionByColor(arg0, arg1, arg2, arg3)
	return ToBool(retValue)
}
func (pself *spriteMgr) CheckCollisionByAlpha(obj Object, alpha_threshold float64) bool {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(alpha_threshold)
	retValue := CallSpriteCheckCollisionByAlpha(arg0, arg1)
	return ToBool(retValue)
}
func (pself *spriteMgr) CheckCollisionWithSpriteByAlpha(obj Object, obj_b Object, alpha_threshold float64) bool {
	arg0 := ToGdObj(obj)
	arg1 := ToGdObj(obj_b)
	arg2 := ToGdFloat(alpha_threshold)
	retValue := CallSpriteCheckCollisionWithSpriteByAlpha(arg0, arg1, arg2)
	return ToBool(retValue)
}
func (pself *tilemapMgr) OpenDrawTilesWithSize(tile_size int64) {
	arg0 := ToGdInt(tile_size)
	CallTilemapOpenDrawTilesWithSize(arg0)
}
func (pself *tilemapMgr) OpenDrawTiles() {
	CallTilemapOpenDrawTiles()
}
func (pself *tilemapMgr) SetLayerIndex(index int64) {
	arg0 := ToGdInt(index)
	CallTilemapSetLayerIndex(arg0)
}
func (pself *tilemapMgr) SetTile(texture_path string, with_collision bool) {
	arg0Str := C.CString(texture_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1 := ToGdBool(with_collision)
	CallTilemapSetTile(arg0, arg1)
}
func (pself *tilemapMgr) SetTileWithCollisionInfo(texture_path string, collision_points Array) {
	arg0Str := C.CString(texture_path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1 := ToGdArray(collision_points)
	CallTilemapSetTileWithCollisionInfo(arg0, arg1)
}
func (pself *tilemapMgr) SetLayerOffset(index int64, offset Vec2) {
	arg0 := ToGdInt(index)
	arg1 := ToGdVec2(offset)
	CallTilemapSetLayerOffset(arg0, arg1)
}
func (pself *tilemapMgr) GetLayerOffset(index int64) Vec2 {
	arg0 := ToGdInt(index)
	retValue := CallTilemapGetLayerOffset(arg0)
	return ToVec2(retValue)
}
func (pself *tilemapMgr) PlaceTiles(positions Array, texture_path string) {
	arg0 := ToGdArray(positions)
	arg1Str := C.CString(texture_path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallTilemapPlaceTiles(arg0, arg1)
}
func (pself *tilemapMgr) PlaceTilesWithLayer(positions Array, texture_path string, layer_index int64) {
	arg0 := ToGdArray(positions)
	arg1Str := C.CString(texture_path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdInt(layer_index)
	CallTilemapPlaceTilesWithLayer(arg0, arg1, arg2)
}
func (pself *tilemapMgr) PlaceTile(pos Vec2, texture_path string) {
	arg0 := ToGdVec2(pos)
	arg1Str := C.CString(texture_path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallTilemapPlaceTile(arg0, arg1)
}
func (pself *tilemapMgr) PlaceTileWithLayer(pos Vec2, texture_path string, layer_index int64) {
	arg0 := ToGdVec2(pos)
	arg1Str := C.CString(texture_path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	arg2 := ToGdInt(layer_index)
	CallTilemapPlaceTileWithLayer(arg0, arg1, arg2)
}
func (pself *tilemapMgr) EraseTile(pos Vec2) {
	arg0 := ToGdVec2(pos)
	CallTilemapEraseTile(arg0)
}
func (pself *tilemapMgr) EraseTileWithLayer(pos Vec2, layer_index int64) {
	arg0 := ToGdVec2(pos)
	arg1 := ToGdInt(layer_index)
	CallTilemapEraseTileWithLayer(arg0, arg1)
}
func (pself *tilemapMgr) GetTile(pos Vec2) string {
	arg0 := ToGdVec2(pos)
	retValue := CallTilemapGetTile(arg0)
	return ToString(retValue)
}
func (pself *tilemapMgr) GetTileWithLayer(pos Vec2, layer_index int64) string {
	arg0 := ToGdVec2(pos)
	arg1 := ToGdInt(layer_index)
	retValue := CallTilemapGetTileWithLayer(arg0, arg1)
	return ToString(retValue)
}
func (pself *tilemapMgr) CloseDrawTiles() {
	CallTilemapCloseDrawTiles()
}
func (pself *tilemapMgr) ExitTilemapEditorMode() {
	CallTilemapExitTilemapEditorMode()
}
func (pself *uiMgr) BindNode(obj Object, rel_path string) Object {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(rel_path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallUiBindNode(arg0, arg1)
	return ToObject(retValue)
}
func (pself *uiMgr) CreateNode(path string) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallUiCreateNode(arg0)
	return ToObject(retValue)
}
func (pself *uiMgr) CreateButton(path string, text string) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1Str := C.CString(text)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallUiCreateButton(arg0, arg1)
	return ToObject(retValue)
}
func (pself *uiMgr) CreateLabel(path string, text string) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1Str := C.CString(text)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallUiCreateLabel(arg0, arg1)
	return ToObject(retValue)
}
func (pself *uiMgr) CreateImage(path string) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	retValue := CallUiCreateImage(arg0)
	return ToObject(retValue)
}
func (pself *uiMgr) CreateToggle(path string, value bool) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1 := ToGdBool(value)
	retValue := CallUiCreateToggle(arg0, arg1)
	return ToObject(retValue)
}
func (pself *uiMgr) CreateSlider(path string, value float64) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1 := ToGdFloat(value)
	retValue := CallUiCreateSlider(arg0, arg1)
	return ToObject(retValue)
}
func (pself *uiMgr) CreateInput(path string, text string) Object {
	arg0Str := C.CString(path)
	arg0 := (GdString)(arg0Str)
	defer C.free(unsafe.Pointer(arg0Str))
	arg1Str := C.CString(text)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	retValue := CallUiCreateInput(arg0, arg1)
	return ToObject(retValue)
}
func (pself *uiMgr) DestroyNode(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallUiDestroyNode(arg0)
	return ToBool(retValue)
}
func (pself *uiMgr) GetType(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetType(arg0)
	return ToInt64(retValue)
}
func (pself *uiMgr) SetText(obj Object, text string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(text)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallUiSetText(arg0, arg1)
}
func (pself *uiMgr) GetText(obj Object) string {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetText(arg0)
	return ToString(retValue)
}
func (pself *uiMgr) SetTexture(obj Object, path string) {
	arg0 := ToGdObj(obj)
	arg1Str := C.CString(path)
	arg1 := (GdString)(arg1Str)
	defer C.free(unsafe.Pointer(arg1Str))
	CallUiSetTexture(arg0, arg1)
}
func (pself *uiMgr) GetTexture(obj Object) string {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetTexture(arg0)
	return ToString(retValue)
}
func (pself *uiMgr) SetColor(obj Object, color Color) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdColor(color)
	CallUiSetColor(arg0, arg1)
}
func (pself *uiMgr) GetColor(obj Object) Color {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetColor(arg0)
	return ToColor(retValue)
}
func (pself *uiMgr) SetFontSize(obj Object, size int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(size)
	CallUiSetFontSize(arg0, arg1)
}
func (pself *uiMgr) GetFontSize(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetFontSize(arg0)
	return ToInt64(retValue)
}
func (pself *uiMgr) SetVisible(obj Object, visible bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(visible)
	CallUiSetVisible(arg0, arg1)
}
func (pself *uiMgr) GetVisible(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetVisible(arg0)
	return ToBool(retValue)
}
func (pself *uiMgr) SetInteractable(obj Object, interactable bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(interactable)
	CallUiSetInteractable(arg0, arg1)
}
func (pself *uiMgr) GetInteractable(obj Object) bool {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetInteractable(arg0)
	return ToBool(retValue)
}
func (pself *uiMgr) SetRect(obj Object, rect Rect2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdRect2(rect)
	CallUiSetRect(arg0, arg1)
}
func (pself *uiMgr) GetRect(obj Object) Rect2 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetRect(arg0)
	return ToRect2(retValue)
}
func (pself *uiMgr) GetLayoutDirection(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetLayoutDirection(arg0)
	return ToInt64(retValue)
}
func (pself *uiMgr) SetLayoutDirection(obj Object, value int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(value)
	CallUiSetLayoutDirection(arg0, arg1)
}
func (pself *uiMgr) GetLayoutMode(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetLayoutMode(arg0)
	return ToInt64(retValue)
}
func (pself *uiMgr) SetLayoutMode(obj Object, value int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(value)
	CallUiSetLayoutMode(arg0, arg1)
}
func (pself *uiMgr) GetAnchorsPreset(obj Object) int64 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetAnchorsPreset(arg0)
	return ToInt64(retValue)
}
func (pself *uiMgr) SetAnchorsPreset(obj Object, value int64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdInt(value)
	CallUiSetAnchorsPreset(arg0, arg1)
}
func (pself *uiMgr) GetScale(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetScale(arg0)
	return ToVec2(retValue)
}
func (pself *uiMgr) SetScale(obj Object, value Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(value)
	CallUiSetScale(arg0, arg1)
}
func (pself *uiMgr) GetPosition(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetPosition(arg0)
	return ToVec2(retValue)
}
func (pself *uiMgr) SetPosition(obj Object, value Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(value)
	CallUiSetPosition(arg0, arg1)
}
func (pself *uiMgr) GetSize(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetSize(arg0)
	return ToVec2(retValue)
}
func (pself *uiMgr) SetSize(obj Object, value Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(value)
	CallUiSetSize(arg0, arg1)
}
func (pself *uiMgr) GetGlobalPosition(obj Object) Vec2 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetGlobalPosition(arg0)
	return ToVec2(retValue)
}
func (pself *uiMgr) SetGlobalPosition(obj Object, value Vec2) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdVec2(value)
	CallUiSetGlobalPosition(arg0, arg1)
}
func (pself *uiMgr) GetRotation(obj Object) float64 {
	arg0 := ToGdObj(obj)
	retValue := CallUiGetRotation(arg0)
	return ToFloat64(retValue)
}
func (pself *uiMgr) SetRotation(obj Object, value float64) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdFloat(value)
	CallUiSetRotation(arg0, arg1)
}
func (pself *uiMgr) GetFlip(obj Object, horizontal bool) bool {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(horizontal)
	retValue := CallUiGetFlip(arg0, arg1)
	return ToBool(retValue)
}
func (pself *uiMgr) SetFlip(obj Object, horizontal bool, is_flip bool) {
	arg0 := ToGdObj(obj)
	arg1 := ToGdBool(horizontal)
	arg2 := ToGdBool(is_flip)
	CallUiSetFlip(arg0, arg1, arg2)
}
