// export by github.com/goplus/ixgo/cmd/qexp

package engine

import (
	q "github.com/goplus/spx/v2/pkg/spx/pkg/engine"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "engine",
		Path: "github.com/goplus/spx/v2/pkg/spx/pkg/engine",
		Deps: map[string]string{
			"github.com/goplus/spbase/mathf":            "mathf",
			"github.com/goplus/spx/v2/internal/keycode": "keycode",
			"github.com/goplus/spx/v2/internal/log":     "log",
			"math":                                      "math",
			"reflect":                                   "reflect",
			"runtime/debug":                             "debug",
			"sort":                                      "sort",
			"sync":                                      "sync",
		},
		Interfaces: map[string]reflect.Type{
			"IAudioMgr":         reflect.TypeOf((*q.IAudioMgr)(nil)).Elem(),
			"ICameraMgr":        reflect.TypeOf((*q.ICameraMgr)(nil)).Elem(),
			"IDebugMgr":         reflect.TypeOf((*q.IDebugMgr)(nil)).Elem(),
			"IExtMgr":           reflect.TypeOf((*q.IExtMgr)(nil)).Elem(),
			"IInputMgr":         reflect.TypeOf((*q.IInputMgr)(nil)).Elem(),
			"ILifeCycle":        reflect.TypeOf((*q.ILifeCycle)(nil)).Elem(),
			"IManager":          reflect.TypeOf((*q.IManager)(nil)).Elem(),
			"INavigationMgr":    reflect.TypeOf((*q.INavigationMgr)(nil)).Elem(),
			"IPenMgr":           reflect.TypeOf((*q.IPenMgr)(nil)).Elem(),
			"IPhysicsMgr":       reflect.TypeOf((*q.IPhysicsMgr)(nil)).Elem(),
			"IPlatformMgr":      reflect.TypeOf((*q.IPlatformMgr)(nil)).Elem(),
			"IResMgr":           reflect.TypeOf((*q.IResMgr)(nil)).Elem(),
			"ISceneMgr":         reflect.TypeOf((*q.ISceneMgr)(nil)).Elem(),
			"ISpriteMgr":        reflect.TypeOf((*q.ISpriteMgr)(nil)).Elem(),
			"ISpriter":          reflect.TypeOf((*q.ISpriter)(nil)).Elem(),
			"ITilemapMgr":       reflect.TypeOf((*q.ITilemapMgr)(nil)).Elem(),
			"ITilemapparserMgr": reflect.TypeOf((*q.ITilemapparserMgr)(nil)).Elem(),
			"IUiMgr":            reflect.TypeOf((*q.IUiMgr)(nil)).Elem(),
			"IUiNode":           reflect.TypeOf((*q.IUiNode)(nil)).Elem(),
			"RuntimeBridge":     reflect.TypeOf((*q.RuntimeBridge)(nil)).Elem(),
		},
		NamedTypes: map[string]reflect.Type{
			"Action0":          reflect.TypeOf((*q.Action0)(nil)).Elem(),
			"CallbackInfo":     reflect.TypeOf((*q.CallbackInfo)(nil)).Elem(),
			"CoreCallbackInfo": reflect.TypeOf((*q.CoreCallbackInfo)(nil)).Elem(),
			"Event0":           reflect.TypeOf((*q.Event0)(nil)).Elem(),
			"KeyCode":          reflect.TypeOf((*q.KeyCode)(nil)).Elem(),
			"Node":             reflect.TypeOf((*q.Node)(nil)).Elem(),
			"Sprite":           reflect.TypeOf((*q.Sprite)(nil)).Elem(),
			"UiNode":           reflect.TypeOf((*q.UiNode)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{
			"Array":  reflect.TypeOf((*q.Array)(nil)).Elem(),
			"Object": reflect.TypeOf((*q.Object)(nil)).Elem(),
		},
		Vars: map[string]reflect.Value{
			"AudioMgr":           reflect.ValueOf(&q.AudioMgr),
			"CameraMgr":          reflect.ValueOf(&q.CameraMgr),
			"DebugMgr":           reflect.ValueOf(&q.DebugMgr),
			"ExtMgr":             reflect.ValueOf(&q.ExtMgr),
			"Id2Sprites":         reflect.ValueOf(&q.Id2Sprites),
			"Id2UiNodes":         reflect.ValueOf(&q.Id2UiNodes),
			"InputMgr":           reflect.ValueOf(&q.InputMgr),
			"NavigationMgr":      reflect.ValueOf(&q.NavigationMgr),
			"PenMgr":             reflect.ValueOf(&q.PenMgr),
			"PhysicsMgr":         reflect.ValueOf(&q.PhysicsMgr),
			"PlatformMgr":        reflect.ValueOf(&q.PlatformMgr),
			"ResMgr":             reflect.ValueOf(&q.ResMgr),
			"SceneMgr":           reflect.ValueOf(&q.SceneMgr),
			"SpriteMgr":          reflect.ValueOf(&q.SpriteMgr),
			"TilemapMgr":         reflect.ValueOf(&q.TilemapMgr),
			"TilemapparserMgr":   reflect.ValueOf(&q.TilemapparserMgr),
			"TimeSinceGameStart": reflect.ValueOf(&q.TimeSinceGameStart),
			"UiMgr":              reflect.ValueOf(&q.UiMgr),
		},
		Funcs: map[string]reflect.Value{
			"Abs":                         reflect.ValueOf(q.Abs),
			"AdvanceTimeSinceGameStart":   reflect.ValueOf(q.AdvanceTimeSinceGameStart),
			"Angle":                       reflect.ValueOf(q.Angle),
			"AngleToPoint":                reflect.ValueOf(q.AngleToPoint),
			"BindSceneInstantiatedSprite": reflect.ValueOf(q.BindSceneInstantiatedSprite),
			"ClearAllSprites":             reflect.ValueOf(q.ClearAllSprites),
			"DealySpriteCall":             reflect.ValueOf(q.DealySpriteCall),
			"DegToRad":                    reflect.ValueOf(q.DegToRad),
			"DelayCall":                   reflect.ValueOf(q.DelayCall),
			"DeleteSprite":                reflect.ValueOf(q.DeleteSprite),
			"DeleteUINode":                reflect.ValueOf(q.DeleteUINode),
			"GetSprite":                   reflect.ValueOf(q.GetSprite),
			"GetUINode":                   reflect.ValueOf(q.GetUINode),
			"InitSpriteInstance":          reflect.ValueOf(q.InitSpriteInstance),
			"InitUINodeInstance":          reflect.ValueOf(q.InitUINodeInstance),
			"InternalUpdateEngine":        reflect.ValueOf(q.InternalUpdateEngine),
			"NewEvent0":                   reflect.ValueOf(q.NewEvent0),
			"PrintStack":                  reflect.ValueOf(q.PrintStack),
			"RadToDeg":                    reflect.ValueOf(q.RadToDeg),
			"SetRuntimeBridge":            reflect.ValueOf(q.SetRuntimeBridge),
			"Sign":                        reflect.ValueOf(q.Sign),
			"Sprites":                     reflect.ValueOf(q.Sprites),
			"TimeSinceGameStarted":        reflect.ValueOf(q.TimeSinceGameStarted),
			"TweenPos":                    reflect.ValueOf(q.TweenPos),
			"TweenPos2":                   reflect.ValueOf(q.TweenPos2),
			"UiNodes":                     reflect.ValueOf(q.UiNodes),
		},
		TypedConsts: map[string]ixgo.TypedConst{
			"Key0":            {Typ: reflect.TypeOf(q.Key0), Value: constant.MakeInt64(int64(q.Key0))},
			"Key1":            {Typ: reflect.TypeOf(q.Key1), Value: constant.MakeInt64(int64(q.Key1))},
			"Key2":            {Typ: reflect.TypeOf(q.Key2), Value: constant.MakeInt64(int64(q.Key2))},
			"Key3":            {Typ: reflect.TypeOf(q.Key3), Value: constant.MakeInt64(int64(q.Key3))},
			"Key4":            {Typ: reflect.TypeOf(q.Key4), Value: constant.MakeInt64(int64(q.Key4))},
			"Key5":            {Typ: reflect.TypeOf(q.Key5), Value: constant.MakeInt64(int64(q.Key5))},
			"Key6":            {Typ: reflect.TypeOf(q.Key6), Value: constant.MakeInt64(int64(q.Key6))},
			"Key7":            {Typ: reflect.TypeOf(q.Key7), Value: constant.MakeInt64(int64(q.Key7))},
			"Key8":            {Typ: reflect.TypeOf(q.Key8), Value: constant.MakeInt64(int64(q.Key8))},
			"Key9":            {Typ: reflect.TypeOf(q.Key9), Value: constant.MakeInt64(int64(q.Key9))},
			"KeyA":            {Typ: reflect.TypeOf(q.KeyA), Value: constant.MakeInt64(int64(q.KeyA))},
			"KeyAlt":          {Typ: reflect.TypeOf(q.KeyAlt), Value: constant.MakeInt64(int64(q.KeyAlt))},
			"KeyAmpersand":    {Typ: reflect.TypeOf(q.KeyAmpersand), Value: constant.MakeInt64(int64(q.KeyAmpersand))},
			"KeyApostrophe":   {Typ: reflect.TypeOf(q.KeyApostrophe), Value: constant.MakeInt64(int64(q.KeyApostrophe))},
			"KeyAsterisk":     {Typ: reflect.TypeOf(q.KeyAsterisk), Value: constant.MakeInt64(int64(q.KeyAsterisk))},
			"KeyAt":           {Typ: reflect.TypeOf(q.KeyAt), Value: constant.MakeInt64(int64(q.KeyAt))},
			"KeyB":            {Typ: reflect.TypeOf(q.KeyB), Value: constant.MakeInt64(int64(q.KeyB))},
			"KeyBack":         {Typ: reflect.TypeOf(q.KeyBack), Value: constant.MakeInt64(int64(q.KeyBack))},
			"KeyBackslash":    {Typ: reflect.TypeOf(q.KeyBackslash), Value: constant.MakeInt64(int64(q.KeyBackslash))},
			"KeyBackspace":    {Typ: reflect.TypeOf(q.KeyBackspace), Value: constant.MakeInt64(int64(q.KeyBackspace))},
			"KeyBacktab":      {Typ: reflect.TypeOf(q.KeyBacktab), Value: constant.MakeInt64(int64(q.KeyBacktab))},
			"KeyBracketLeft":  {Typ: reflect.TypeOf(q.KeyBracketLeft), Value: constant.MakeInt64(int64(q.KeyBracketLeft))},
			"KeyBracketRight": {Typ: reflect.TypeOf(q.KeyBracketRight), Value: constant.MakeInt64(int64(q.KeyBracketRight))},
			"KeyC":            {Typ: reflect.TypeOf(q.KeyC), Value: constant.MakeInt64(int64(q.KeyC))},
			"KeyCapsLock":     {Typ: reflect.TypeOf(q.KeyCapsLock), Value: constant.MakeInt64(int64(q.KeyCapsLock))},
			"KeyClear":        {Typ: reflect.TypeOf(q.KeyClear), Value: constant.MakeInt64(int64(q.KeyClear))},
			"KeyCmdOrCtrl":    {Typ: reflect.TypeOf(q.KeyCmdOrCtrl), Value: constant.MakeInt64(int64(q.KeyCmdOrCtrl))},
			"KeyColon":        {Typ: reflect.TypeOf(q.KeyColon), Value: constant.MakeInt64(int64(q.KeyColon))},
			"KeyComma":        {Typ: reflect.TypeOf(q.KeyComma), Value: constant.MakeInt64(int64(q.KeyComma))},
			"KeyControl":      {Typ: reflect.TypeOf(q.KeyControl), Value: constant.MakeInt64(int64(q.KeyControl))},
			"KeyCtrl":         {Typ: reflect.TypeOf(q.KeyCtrl), Value: constant.MakeInt64(int64(q.KeyCtrl))},
			"KeyD":            {Typ: reflect.TypeOf(q.KeyD), Value: constant.MakeInt64(int64(q.KeyD))},
			"KeyDelete":       {Typ: reflect.TypeOf(q.KeyDelete), Value: constant.MakeInt64(int64(q.KeyDelete))},
			"KeyDollar":       {Typ: reflect.TypeOf(q.KeyDollar), Value: constant.MakeInt64(int64(q.KeyDollar))},
			"KeyDown":         {Typ: reflect.TypeOf(q.KeyDown), Value: constant.MakeInt64(int64(q.KeyDown))},
			"KeyE":            {Typ: reflect.TypeOf(q.KeyE), Value: constant.MakeInt64(int64(q.KeyE))},
			"KeyEnd":          {Typ: reflect.TypeOf(q.KeyEnd), Value: constant.MakeInt64(int64(q.KeyEnd))},
			"KeyEnter":        {Typ: reflect.TypeOf(q.KeyEnter), Value: constant.MakeInt64(int64(q.KeyEnter))},
			"KeyEqual":        {Typ: reflect.TypeOf(q.KeyEqual), Value: constant.MakeInt64(int64(q.KeyEqual))},
			"KeyEscape":       {Typ: reflect.TypeOf(q.KeyEscape), Value: constant.MakeInt64(int64(q.KeyEscape))},
			"KeyExclam":       {Typ: reflect.TypeOf(q.KeyExclam), Value: constant.MakeInt64(int64(q.KeyExclam))},
			"KeyF":            {Typ: reflect.TypeOf(q.KeyF), Value: constant.MakeInt64(int64(q.KeyF))},
			"KeyF1":           {Typ: reflect.TypeOf(q.KeyF1), Value: constant.MakeInt64(int64(q.KeyF1))},
			"KeyF10":          {Typ: reflect.TypeOf(q.KeyF10), Value: constant.MakeInt64(int64(q.KeyF10))},
			"KeyF11":          {Typ: reflect.TypeOf(q.KeyF11), Value: constant.MakeInt64(int64(q.KeyF11))},
			"KeyF12":          {Typ: reflect.TypeOf(q.KeyF12), Value: constant.MakeInt64(int64(q.KeyF12))},
			"KeyF13":          {Typ: reflect.TypeOf(q.KeyF13), Value: constant.MakeInt64(int64(q.KeyF13))},
			"KeyF14":          {Typ: reflect.TypeOf(q.KeyF14), Value: constant.MakeInt64(int64(q.KeyF14))},
			"KeyF15":          {Typ: reflect.TypeOf(q.KeyF15), Value: constant.MakeInt64(int64(q.KeyF15))},
			"KeyF16":          {Typ: reflect.TypeOf(q.KeyF16), Value: constant.MakeInt64(int64(q.KeyF16))},
			"KeyF17":          {Typ: reflect.TypeOf(q.KeyF17), Value: constant.MakeInt64(int64(q.KeyF17))},
			"KeyF18":          {Typ: reflect.TypeOf(q.KeyF18), Value: constant.MakeInt64(int64(q.KeyF18))},
			"KeyF19":          {Typ: reflect.TypeOf(q.KeyF19), Value: constant.MakeInt64(int64(q.KeyF19))},
			"KeyF2":           {Typ: reflect.TypeOf(q.KeyF2), Value: constant.MakeInt64(int64(q.KeyF2))},
			"KeyF20":          {Typ: reflect.TypeOf(q.KeyF20), Value: constant.MakeInt64(int64(q.KeyF20))},
			"KeyF21":          {Typ: reflect.TypeOf(q.KeyF21), Value: constant.MakeInt64(int64(q.KeyF21))},
			"KeyF22":          {Typ: reflect.TypeOf(q.KeyF22), Value: constant.MakeInt64(int64(q.KeyF22))},
			"KeyF23":          {Typ: reflect.TypeOf(q.KeyF23), Value: constant.MakeInt64(int64(q.KeyF23))},
			"KeyF24":          {Typ: reflect.TypeOf(q.KeyF24), Value: constant.MakeInt64(int64(q.KeyF24))},
			"KeyF25":          {Typ: reflect.TypeOf(q.KeyF25), Value: constant.MakeInt64(int64(q.KeyF25))},
			"KeyF26":          {Typ: reflect.TypeOf(q.KeyF26), Value: constant.MakeInt64(int64(q.KeyF26))},
			"KeyF27":          {Typ: reflect.TypeOf(q.KeyF27), Value: constant.MakeInt64(int64(q.KeyF27))},
			"KeyF28":          {Typ: reflect.TypeOf(q.KeyF28), Value: constant.MakeInt64(int64(q.KeyF28))},
			"KeyF29":          {Typ: reflect.TypeOf(q.KeyF29), Value: constant.MakeInt64(int64(q.KeyF29))},
			"KeyF3":           {Typ: reflect.TypeOf(q.KeyF3), Value: constant.MakeInt64(int64(q.KeyF3))},
			"KeyF30":          {Typ: reflect.TypeOf(q.KeyF30), Value: constant.MakeInt64(int64(q.KeyF30))},
			"KeyF31":          {Typ: reflect.TypeOf(q.KeyF31), Value: constant.MakeInt64(int64(q.KeyF31))},
			"KeyF32":          {Typ: reflect.TypeOf(q.KeyF32), Value: constant.MakeInt64(int64(q.KeyF32))},
			"KeyF33":          {Typ: reflect.TypeOf(q.KeyF33), Value: constant.MakeInt64(int64(q.KeyF33))},
			"KeyF34":          {Typ: reflect.TypeOf(q.KeyF34), Value: constant.MakeInt64(int64(q.KeyF34))},
			"KeyF35":          {Typ: reflect.TypeOf(q.KeyF35), Value: constant.MakeInt64(int64(q.KeyF35))},
			"KeyF4":           {Typ: reflect.TypeOf(q.KeyF4), Value: constant.MakeInt64(int64(q.KeyF4))},
			"KeyF5":           {Typ: reflect.TypeOf(q.KeyF5), Value: constant.MakeInt64(int64(q.KeyF5))},
			"KeyF6":           {Typ: reflect.TypeOf(q.KeyF6), Value: constant.MakeInt64(int64(q.KeyF6))},
			"KeyF7":           {Typ: reflect.TypeOf(q.KeyF7), Value: constant.MakeInt64(int64(q.KeyF7))},
			"KeyF8":           {Typ: reflect.TypeOf(q.KeyF8), Value: constant.MakeInt64(int64(q.KeyF8))},
			"KeyF9":           {Typ: reflect.TypeOf(q.KeyF9), Value: constant.MakeInt64(int64(q.KeyF9))},
			"KeyFavorites":    {Typ: reflect.TypeOf(q.KeyFavorites), Value: constant.MakeInt64(int64(q.KeyFavorites))},
			"KeyForward":      {Typ: reflect.TypeOf(q.KeyForward), Value: constant.MakeInt64(int64(q.KeyForward))},
			"KeyG":            {Typ: reflect.TypeOf(q.KeyG), Value: constant.MakeInt64(int64(q.KeyG))},
			"KeyGlobe":        {Typ: reflect.TypeOf(q.KeyGlobe), Value: constant.MakeInt64(int64(q.KeyGlobe))},
			"KeyGraveAccent":  {Typ: reflect.TypeOf(q.KeyGraveAccent), Value: constant.MakeInt64(int64(q.KeyGraveAccent))},
			"KeyGreater":      {Typ: reflect.TypeOf(q.KeyGreater), Value: constant.MakeInt64(int64(q.KeyGreater))},
			"KeyH":            {Typ: reflect.TypeOf(q.KeyH), Value: constant.MakeInt64(int64(q.KeyH))},
			"KeyHelp":         {Typ: reflect.TypeOf(q.KeyHelp), Value: constant.MakeInt64(int64(q.KeyHelp))},
			"KeyHome":         {Typ: reflect.TypeOf(q.KeyHome), Value: constant.MakeInt64(int64(q.KeyHome))},
			"KeyHomePage":     {Typ: reflect.TypeOf(q.KeyHomePage), Value: constant.MakeInt64(int64(q.KeyHomePage))},
			"KeyHyper":        {Typ: reflect.TypeOf(q.KeyHyper), Value: constant.MakeInt64(int64(q.KeyHyper))},
			"KeyI":            {Typ: reflect.TypeOf(q.KeyI), Value: constant.MakeInt64(int64(q.KeyI))},
			"KeyInsert":       {Typ: reflect.TypeOf(q.KeyInsert), Value: constant.MakeInt64(int64(q.KeyInsert))},
			"KeyJ":            {Typ: reflect.TypeOf(q.KeyJ), Value: constant.MakeInt64(int64(q.KeyJ))},
			"KeyJISEisu":      {Typ: reflect.TypeOf(q.KeyJISEisu), Value: constant.MakeInt64(int64(q.KeyJISEisu))},
			"KeyJISKana":      {Typ: reflect.TypeOf(q.KeyJISKana), Value: constant.MakeInt64(int64(q.KeyJISKana))},
			"KeyK":            {Typ: reflect.TypeOf(q.KeyK), Value: constant.MakeInt64(int64(q.KeyK))},
			"KeyKP0":          {Typ: reflect.TypeOf(q.KeyKP0), Value: constant.MakeInt64(int64(q.KeyKP0))},
			"KeyKP1":          {Typ: reflect.TypeOf(q.KeyKP1), Value: constant.MakeInt64(int64(q.KeyKP1))},
			"KeyKP2":          {Typ: reflect.TypeOf(q.KeyKP2), Value: constant.MakeInt64(int64(q.KeyKP2))},
			"KeyKP3":          {Typ: reflect.TypeOf(q.KeyKP3), Value: constant.MakeInt64(int64(q.KeyKP3))},
			"KeyKP4":          {Typ: reflect.TypeOf(q.KeyKP4), Value: constant.MakeInt64(int64(q.KeyKP4))},
			"KeyKP5":          {Typ: reflect.TypeOf(q.KeyKP5), Value: constant.MakeInt64(int64(q.KeyKP5))},
			"KeyKP6":          {Typ: reflect.TypeOf(q.KeyKP6), Value: constant.MakeInt64(int64(q.KeyKP6))},
			"KeyKP7":          {Typ: reflect.TypeOf(q.KeyKP7), Value: constant.MakeInt64(int64(q.KeyKP7))},
			"KeyKP8":          {Typ: reflect.TypeOf(q.KeyKP8), Value: constant.MakeInt64(int64(q.KeyKP8))},
			"KeyKP9":          {Typ: reflect.TypeOf(q.KeyKP9), Value: constant.MakeInt64(int64(q.KeyKP9))},
			"KeyKPAdd":        {Typ: reflect.TypeOf(q.KeyKPAdd), Value: constant.MakeInt64(int64(q.KeyKPAdd))},
			"KeyKPDecimal":    {Typ: reflect.TypeOf(q.KeyKPDecimal), Value: constant.MakeInt64(int64(q.KeyKPDecimal))},
			"KeyKPDivide":     {Typ: reflect.TypeOf(q.KeyKPDivide), Value: constant.MakeInt64(int64(q.KeyKPDivide))},
			"KeyKPEnter":      {Typ: reflect.TypeOf(q.KeyKPEnter), Value: constant.MakeInt64(int64(q.KeyKPEnter))},
			"KeyKPEqual":      {Typ: reflect.TypeOf(q.KeyKPEqual), Value: constant.MakeInt64(int64(q.KeyKPEqual))},
			"KeyKPMultiply":   {Typ: reflect.TypeOf(q.KeyKPMultiply), Value: constant.MakeInt64(int64(q.KeyKPMultiply))},
			"KeyKPPeriod":     {Typ: reflect.TypeOf(q.KeyKPPeriod), Value: constant.MakeInt64(int64(q.KeyKPPeriod))},
			"KeyKPSubtract":   {Typ: reflect.TypeOf(q.KeyKPSubtract), Value: constant.MakeInt64(int64(q.KeyKPSubtract))},
			"KeyKeyboard":     {Typ: reflect.TypeOf(q.KeyKeyboard), Value: constant.MakeInt64(int64(q.KeyKeyboard))},
			"KeyL":            {Typ: reflect.TypeOf(q.KeyL), Value: constant.MakeInt64(int64(q.KeyL))},
			"KeyLaunch0":      {Typ: reflect.TypeOf(q.KeyLaunch0), Value: constant.MakeInt64(int64(q.KeyLaunch0))},
			"KeyLaunch1":      {Typ: reflect.TypeOf(q.KeyLaunch1), Value: constant.MakeInt64(int64(q.KeyLaunch1))},
			"KeyLaunch2":      {Typ: reflect.TypeOf(q.KeyLaunch2), Value: constant.MakeInt64(int64(q.KeyLaunch2))},
			"KeyLaunch3":      {Typ: reflect.TypeOf(q.KeyLaunch3), Value: constant.MakeInt64(int64(q.KeyLaunch3))},
			"KeyLaunch4":      {Typ: reflect.TypeOf(q.KeyLaunch4), Value: constant.MakeInt64(int64(q.KeyLaunch4))},
			"KeyLaunch5":      {Typ: reflect.TypeOf(q.KeyLaunch5), Value: constant.MakeInt64(int64(q.KeyLaunch5))},
			"KeyLaunch6":      {Typ: reflect.TypeOf(q.KeyLaunch6), Value: constant.MakeInt64(int64(q.KeyLaunch6))},
			"KeyLaunch7":      {Typ: reflect.TypeOf(q.KeyLaunch7), Value: constant.MakeInt64(int64(q.KeyLaunch7))},
			"KeyLaunch8":      {Typ: reflect.TypeOf(q.KeyLaunch8), Value: constant.MakeInt64(int64(q.KeyLaunch8))},
			"KeyLaunch9":      {Typ: reflect.TypeOf(q.KeyLaunch9), Value: constant.MakeInt64(int64(q.KeyLaunch9))},
			"KeyLaunchA":      {Typ: reflect.TypeOf(q.KeyLaunchA), Value: constant.MakeInt64(int64(q.KeyLaunchA))},
			"KeyLaunchB":      {Typ: reflect.TypeOf(q.KeyLaunchB), Value: constant.MakeInt64(int64(q.KeyLaunchB))},
			"KeyLaunchC":      {Typ: reflect.TypeOf(q.KeyLaunchC), Value: constant.MakeInt64(int64(q.KeyLaunchC))},
			"KeyLaunchD":      {Typ: reflect.TypeOf(q.KeyLaunchD), Value: constant.MakeInt64(int64(q.KeyLaunchD))},
			"KeyLaunchE":      {Typ: reflect.TypeOf(q.KeyLaunchE), Value: constant.MakeInt64(int64(q.KeyLaunchE))},
			"KeyLaunchF":      {Typ: reflect.TypeOf(q.KeyLaunchF), Value: constant.MakeInt64(int64(q.KeyLaunchF))},
			"KeyLaunchMail":   {Typ: reflect.TypeOf(q.KeyLaunchMail), Value: constant.MakeInt64(int64(q.KeyLaunchMail))},
			"KeyLaunchMedia":  {Typ: reflect.TypeOf(q.KeyLaunchMedia), Value: constant.MakeInt64(int64(q.KeyLaunchMedia))},
			"KeyLeft":         {Typ: reflect.TypeOf(q.KeyLeft), Value: constant.MakeInt64(int64(q.KeyLeft))},
			"KeyLeftBracket":  {Typ: reflect.TypeOf(q.KeyLeftBracket), Value: constant.MakeInt64(int64(q.KeyLeftBracket))},
			"KeyLess":         {Typ: reflect.TypeOf(q.KeyLess), Value: constant.MakeInt64(int64(q.KeyLess))},
			"KeyM":            {Typ: reflect.TypeOf(q.KeyM), Value: constant.MakeInt64(int64(q.KeyM))},
			"KeyMediaNext":    {Typ: reflect.TypeOf(q.KeyMediaNext), Value: constant.MakeInt64(int64(q.KeyMediaNext))},
			"KeyMediaPlay":    {Typ: reflect.TypeOf(q.KeyMediaPlay), Value: constant.MakeInt64(int64(q.KeyMediaPlay))},
			"KeyMediaPrev":    {Typ: reflect.TypeOf(q.KeyMediaPrev), Value: constant.MakeInt64(int64(q.KeyMediaPrev))},
			"KeyMediaRecord":  {Typ: reflect.TypeOf(q.KeyMediaRecord), Value: constant.MakeInt64(int64(q.KeyMediaRecord))},
			"KeyMediaStop":    {Typ: reflect.TypeOf(q.KeyMediaStop), Value: constant.MakeInt64(int64(q.KeyMediaStop))},
			"KeyMenu":         {Typ: reflect.TypeOf(q.KeyMenu), Value: constant.MakeInt64(int64(q.KeyMenu))},
			"KeyMeta":         {Typ: reflect.TypeOf(q.KeyMeta), Value: constant.MakeInt64(int64(q.KeyMeta))},
			"KeyMinus":        {Typ: reflect.TypeOf(q.KeyMinus), Value: constant.MakeInt64(int64(q.KeyMinus))},
			"KeyN":            {Typ: reflect.TypeOf(q.KeyN), Value: constant.MakeInt64(int64(q.KeyN))},
			"KeyNone":         {Typ: reflect.TypeOf(q.KeyNone), Value: constant.MakeInt64(int64(q.KeyNone))},
			"KeyNumLock":      {Typ: reflect.TypeOf(q.KeyNumLock), Value: constant.MakeInt64(int64(q.KeyNumLock))},
			"KeyNumberSign":   {Typ: reflect.TypeOf(q.KeyNumberSign), Value: constant.MakeInt64(int64(q.KeyNumberSign))},
			"KeyO":            {Typ: reflect.TypeOf(q.KeyO), Value: constant.MakeInt64(int64(q.KeyO))},
			"KeyOpenURL":      {Typ: reflect.TypeOf(q.KeyOpenURL), Value: constant.MakeInt64(int64(q.KeyOpenURL))},
			"KeyP":            {Typ: reflect.TypeOf(q.KeyP), Value: constant.MakeInt64(int64(q.KeyP))},
			"KeyPageDown":     {Typ: reflect.TypeOf(q.KeyPageDown), Value: constant.MakeInt64(int64(q.KeyPageDown))},
			"KeyPageUp":       {Typ: reflect.TypeOf(q.KeyPageUp), Value: constant.MakeInt64(int64(q.KeyPageUp))},
			"KeyParenLeft":    {Typ: reflect.TypeOf(q.KeyParenLeft), Value: constant.MakeInt64(int64(q.KeyParenLeft))},
			"KeyParenRight":   {Typ: reflect.TypeOf(q.KeyParenRight), Value: constant.MakeInt64(int64(q.KeyParenRight))},
			"KeyPause":        {Typ: reflect.TypeOf(q.KeyPause), Value: constant.MakeInt64(int64(q.KeyPause))},
			"KeyPercent":      {Typ: reflect.TypeOf(q.KeyPercent), Value: constant.MakeInt64(int64(q.KeyPercent))},
			"KeyPeriod":       {Typ: reflect.TypeOf(q.KeyPeriod), Value: constant.MakeInt64(int64(q.KeyPeriod))},
			"KeyPlus":         {Typ: reflect.TypeOf(q.KeyPlus), Value: constant.MakeInt64(int64(q.KeyPlus))},
			"KeyPrint":        {Typ: reflect.TypeOf(q.KeyPrint), Value: constant.MakeInt64(int64(q.KeyPrint))},
			"KeyPrintScreen":  {Typ: reflect.TypeOf(q.KeyPrintScreen), Value: constant.MakeInt64(int64(q.KeyPrintScreen))},
			"KeyQ":            {Typ: reflect.TypeOf(q.KeyQ), Value: constant.MakeInt64(int64(q.KeyQ))},
			"KeyQuestion":     {Typ: reflect.TypeOf(q.KeyQuestion), Value: constant.MakeInt64(int64(q.KeyQuestion))},
			"KeyQuoteDbl":     {Typ: reflect.TypeOf(q.KeyQuoteDbl), Value: constant.MakeInt64(int64(q.KeyQuoteDbl))},
			"KeyR":            {Typ: reflect.TypeOf(q.KeyR), Value: constant.MakeInt64(int64(q.KeyR))},
			"KeyRefresh":      {Typ: reflect.TypeOf(q.KeyRefresh), Value: constant.MakeInt64(int64(q.KeyRefresh))},
			"KeyRight":        {Typ: reflect.TypeOf(q.KeyRight), Value: constant.MakeInt64(int64(q.KeyRight))},
			"KeyRightBracket": {Typ: reflect.TypeOf(q.KeyRightBracket), Value: constant.MakeInt64(int64(q.KeyRightBracket))},
			"KeyS":            {Typ: reflect.TypeOf(q.KeyS), Value: constant.MakeInt64(int64(q.KeyS))},
			"KeyScrollLock":   {Typ: reflect.TypeOf(q.KeyScrollLock), Value: constant.MakeInt64(int64(q.KeyScrollLock))},
			"KeySearch":       {Typ: reflect.TypeOf(q.KeySearch), Value: constant.MakeInt64(int64(q.KeySearch))},
			"KeySemicolon":    {Typ: reflect.TypeOf(q.KeySemicolon), Value: constant.MakeInt64(int64(q.KeySemicolon))},
			"KeyShift":        {Typ: reflect.TypeOf(q.KeyShift), Value: constant.MakeInt64(int64(q.KeyShift))},
			"KeySlash":        {Typ: reflect.TypeOf(q.KeySlash), Value: constant.MakeInt64(int64(q.KeySlash))},
			"KeySpace":        {Typ: reflect.TypeOf(q.KeySpace), Value: constant.MakeInt64(int64(q.KeySpace))},
			"KeySpecial":      {Typ: reflect.TypeOf(q.KeySpecial), Value: constant.MakeInt64(int64(q.KeySpecial))},
			"KeyStandby":      {Typ: reflect.TypeOf(q.KeyStandby), Value: constant.MakeInt64(int64(q.KeyStandby))},
			"KeyStop":         {Typ: reflect.TypeOf(q.KeyStop), Value: constant.MakeInt64(int64(q.KeyStop))},
			"KeySysReq":       {Typ: reflect.TypeOf(q.KeySysReq), Value: constant.MakeInt64(int64(q.KeySysReq))},
			"KeyT":            {Typ: reflect.TypeOf(q.KeyT), Value: constant.MakeInt64(int64(q.KeyT))},
			"KeyTab":          {Typ: reflect.TypeOf(q.KeyTab), Value: constant.MakeInt64(int64(q.KeyTab))},
			"KeyU":            {Typ: reflect.TypeOf(q.KeyU), Value: constant.MakeInt64(int64(q.KeyU))},
			"KeyUnknown":      {Typ: reflect.TypeOf(q.KeyUnknown), Value: constant.MakeInt64(int64(q.KeyUnknown))},
			"KeyUp":           {Typ: reflect.TypeOf(q.KeyUp), Value: constant.MakeInt64(int64(q.KeyUp))},
			"KeyV":            {Typ: reflect.TypeOf(q.KeyV), Value: constant.MakeInt64(int64(q.KeyV))},
			"KeyVolumeDown":   {Typ: reflect.TypeOf(q.KeyVolumeDown), Value: constant.MakeInt64(int64(q.KeyVolumeDown))},
			"KeyVolumeMute":   {Typ: reflect.TypeOf(q.KeyVolumeMute), Value: constant.MakeInt64(int64(q.KeyVolumeMute))},
			"KeyVolumeUp":     {Typ: reflect.TypeOf(q.KeyVolumeUp), Value: constant.MakeInt64(int64(q.KeyVolumeUp))},
			"KeyW":            {Typ: reflect.TypeOf(q.KeyW), Value: constant.MakeInt64(int64(q.KeyW))},
			"KeyX":            {Typ: reflect.TypeOf(q.KeyX), Value: constant.MakeInt64(int64(q.KeyX))},
			"KeyY":            {Typ: reflect.TypeOf(q.KeyY), Value: constant.MakeInt64(int64(q.KeyY))},
			"KeyZ":            {Typ: reflect.TypeOf(q.KeyZ), Value: constant.MakeInt64(int64(q.KeyZ))},
		},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"Float2IntFactor": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Float2IntFactor))},
		},
	})
}
