//go:build pure_engine
// +build pure_engine

/*
 * Copyright (c) 2021 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*------------------------------------------------------------------------------
//   This code was generated by spx template sync_pure.gen.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//----------------------------------------------------------------------------*/

// Code generated by spx codegen; DO NOT EDIT.

package enginewrap

import (
	. "github.com/goplus/spbase/mathf"
	gdx "github.com/goplus/spx/v2/pkg/spx/pkg/engine"
)

/* // copy these code to dst file
var(
audioMgr enginewrap.AudioMgrImpl
cameraMgr enginewrap.CameraMgrImpl
debugMgr enginewrap.DebugMgrImpl
extMgr enginewrap.ExtMgrImpl
inputMgr enginewrap.InputMgrImpl
navigationMgr enginewrap.NavigationMgrImpl
penMgr enginewrap.PenMgrImpl
physicsMgr enginewrap.PhysicsMgrImpl
platformMgr enginewrap.PlatformMgrImpl
resMgr enginewrap.ResMgrImpl
sceneMgr enginewrap.SceneMgrImpl
spriteMgr enginewrap.SpriteMgrImpl
tilemapMgr enginewrap.TilemapMgrImpl
tilemapparserMgr enginewrap.TilemapparserMgrImpl
uiMgr enginewrap.UiMgrImpl

)
*/

var (
	audioMgr         AudioMgrImpl
	cameraMgr        CameraMgrImpl
	debugMgr         DebugMgrImpl
	extMgr           ExtMgrImpl
	inputMgr         InputMgrImpl
	navigationMgr    NavigationMgrImpl
	penMgr           PenMgrImpl
	physicsMgr       PhysicsMgrImpl
	platformMgr      PlatformMgrImpl
	resMgr           ResMgrImpl
	sceneMgr         SceneMgrImpl
	spriteMgr        SpriteMgrImpl
	tilemapMgr       TilemapMgrImpl
	tilemapparserMgr TilemapparserMgrImpl
	uiMgr            UiMgrImpl
)

type audioMgrImpl struct {
}
type AudioMgrImpl struct {
	audioMgrImpl
}
type cameraMgrImpl struct {
}
type CameraMgrImpl struct {
	cameraMgrImpl
}
type debugMgrImpl struct {
}
type DebugMgrImpl struct {
	debugMgrImpl
}
type extMgrImpl struct {
}
type ExtMgrImpl struct {
	extMgrImpl
}
type inputMgrImpl struct {
}
type InputMgrImpl struct {
	inputMgrImpl
}
type navigationMgrImpl struct {
}
type NavigationMgrImpl struct {
	navigationMgrImpl
}
type penMgrImpl struct {
}
type PenMgrImpl struct {
	penMgrImpl
}
type physicsMgrImpl struct {
}
type PhysicsMgrImpl struct {
	physicsMgrImpl
}
type platformMgrImpl struct {
}
type PlatformMgrImpl struct {
	platformMgrImpl
}
type resMgrImpl struct {
}
type ResMgrImpl struct {
	resMgrImpl
}
type sceneMgrImpl struct {
}
type SceneMgrImpl struct {
	sceneMgrImpl
}
type spriteMgrImpl struct {
}
type SpriteMgrImpl struct {
	spriteMgrImpl
}
type tilemapMgrImpl struct {
}
type TilemapMgrImpl struct {
	tilemapMgrImpl
}
type tilemapparserMgrImpl struct {
}
type TilemapparserMgrImpl struct {
	tilemapparserMgrImpl
}
type uiMgrImpl struct {
}
type UiMgrImpl struct {
	uiMgrImpl
}

// IAudioMgr
func (*audioMgrImpl) StopAll() {}
func (*audioMgrImpl) CreateAudio() gdx.Object {
	return 0
}
func (*audioMgrImpl) DestroyAudio(obj gdx.Object)            {}
func (*audioMgrImpl) SetPitch(obj gdx.Object, pitch float64) {}
func (*audioMgrImpl) GetPitch(obj gdx.Object) float64 {
	return 0
}
func (*audioMgrImpl) SetPan(obj gdx.Object, pan float64) {}
func (*audioMgrImpl) GetPan(obj gdx.Object) float64 {
	return 0
}
func (*audioMgrImpl) SetVolume(obj gdx.Object, volume float64) {}
func (*audioMgrImpl) GetVolume(obj gdx.Object) float64 {
	return 0
}
func (*audioMgrImpl) PlayWithAttenuation(obj gdx.Object, path string, owner_id gdx.Object, attenuation float64, max_distance float64) int64 {
	return 0
}
func (*audioMgrImpl) Play(obj gdx.Object, path string) int64 {
	return 0
}
func (*audioMgrImpl) Pause(aid int64)              {}
func (*audioMgrImpl) Resume(aid int64)             {}
func (*audioMgrImpl) Stop(aid int64)               {}
func (*audioMgrImpl) SetLoop(aid int64, loop bool) {}
func (*audioMgrImpl) GetLoop(aid int64) bool {
	return false
}
func (*audioMgrImpl) GetTimer(aid int64) float64 {
	return 0
}
func (*audioMgrImpl) SetTimer(aid int64, time float64) {}
func (*audioMgrImpl) IsPlaying(aid int64) bool {
	return false
}

// ICameraMgr
func (*cameraMgrImpl) GetCameraPosition() Vec2 {
	return Vec2{}
}
func (*cameraMgrImpl) SetCameraPosition(position Vec2) {}
func (*cameraMgrImpl) GetCameraZoom() Vec2 {
	return Vec2{}
}
func (*cameraMgrImpl) SetCameraZoom(size Vec2) {}
func (*cameraMgrImpl) GetViewportRect() Rect2 {
	return Rect2{}
}
func (*cameraMgrImpl) GetGlobalCameraRect() Rect2 {
	return Rect2{}
}
func (*cameraMgrImpl) GetStageLimitsRect() Rect2 {
	return Rect2{}
}
func (*cameraMgrImpl) SetCameraLimit(side int64, limit int64) {}
func (*cameraMgrImpl) SetCameraSmoothing(enabled bool)        {}

// IDebugMgr
func (*debugMgrImpl) DebugDrawCircle(pos Vec2, radius float64, color Color) {}
func (*debugMgrImpl) DebugDrawRect(pos Vec2, size Vec2, color Color)        {}
func (*debugMgrImpl) DebugDrawLine(from Vec2, to Vec2, color Color)         {}

// IExtMgr
func (*extMgrImpl) RequestExit(exit_code int64)  {}
func (*extMgrImpl) RequestReset(exit_code int64) {}
func (*extMgrImpl) RequestRestart()              {}
func (*extMgrImpl) OnRuntimePanic(msg string)    {}
func (*extMgrImpl) Pause()                       {}
func (*extMgrImpl) Resume()                      {}
func (*extMgrImpl) IsPaused() bool {
	return false
}
func (*extMgrImpl) NextFrame()                    {}
func (*extMgrImpl) SetLayerSorterMode(mode int64) {}

// IInputMgr
func (*inputMgrImpl) GetGlobalMousePos() Vec2 {
	return Vec2{}
}
func (*inputMgrImpl) GetKey(key int64) bool {
	return false
}
func (*inputMgrImpl) GetMouseState(mouse_id int64) bool {
	return false
}
func (*inputMgrImpl) GetKeyState(key int64) int64 {
	return 0
}
func (*inputMgrImpl) GetAxis(neg_action string, pos_action string) float64 {
	return 0
}
func (*inputMgrImpl) IsActionPressed(action string) bool {
	return false
}
func (*inputMgrImpl) IsActionJustPressed(action string) bool {
	return false
}
func (*inputMgrImpl) IsActionJustReleased(action string) bool {
	return false
}

// INavigationMgr
func (*navigationMgrImpl) SetupPathFinderWithSize(grid_size Vec2, cell_size Vec2, with_jump bool, with_debug bool) {
}
func (*navigationMgrImpl) SetupPathFinder(with_jump bool)           {}
func (*navigationMgrImpl) SetObstacle(obj gdx.Object, enabled bool) {}
func (*navigationMgrImpl) FindPath(p_from Vec2, p_to Vec2, with_jump bool) gdx.Array {
	return nil
}

// IPenMgr
func (*penMgrImpl) DestroyAllPens() {}
func (*penMgrImpl) CreatePen() gdx.Object {
	return 0
}
func (*penMgrImpl) DestroyPen(obj gdx.Object)                                  {}
func (*penMgrImpl) PenStamp(obj gdx.Object)                                    {}
func (*penMgrImpl) MovePenTo(obj gdx.Object, position Vec2)                    {}
func (*penMgrImpl) PenDown(obj gdx.Object, move_by_mouse bool)                 {}
func (*penMgrImpl) PenUp(obj gdx.Object)                                       {}
func (*penMgrImpl) SetPenColorTo(obj gdx.Object, color Color)                  {}
func (*penMgrImpl) ChangePenBy(obj gdx.Object, property int64, amount float64) {}
func (*penMgrImpl) SetPenTo(obj gdx.Object, property int64, value float64)     {}
func (*penMgrImpl) ChangePenSizeBy(obj gdx.Object, amount float64)             {}
func (*penMgrImpl) SetPenSizeTo(obj gdx.Object, size float64)                  {}
func (*penMgrImpl) SetPenStampTexture(obj gdx.Object, texture_path string)     {}

// IPhysicsMgr
func (*physicsMgrImpl) Raycast(from Vec2, to Vec2, collision_mask int64) gdx.Object {
	return 0
}
func (*physicsMgrImpl) CheckCollision(from Vec2, to Vec2, collision_mask int64, collide_with_areas bool, collide_with_bodies bool) bool {
	return false
}
func (*physicsMgrImpl) CheckTouchedCameraBoundaries(obj gdx.Object) int64 {
	return 0
}
func (*physicsMgrImpl) CheckTouchedCameraBoundary(obj gdx.Object, board_type int64) bool {
	return false
}
func (*physicsMgrImpl) CheckNearestTouchedCameraBoundary(obj gdx.Object) int64 {
	return 0
}
func (*physicsMgrImpl) CheckTouchedStageBoundaries(obj gdx.Object) int64 {
	return 0
}
func (*physicsMgrImpl) CheckTouchedStageBoundary(obj gdx.Object, board_type int64) bool {
	return false
}
func (*physicsMgrImpl) CheckNearestTouchedStageBoundary(obj gdx.Object) int64 {
	return 0
}
func (*physicsMgrImpl) SetCollisionSystemType(is_collision_by_alpha bool) {}
func (*physicsMgrImpl) SetGlobalGravity(gravity float64)                  {}
func (*physicsMgrImpl) GetGlobalGravity() float64 {
	return 0
}
func (*physicsMgrImpl) SetGlobalFriction(friction float64) {}
func (*physicsMgrImpl) GetGlobalFriction() float64 {
	return 0
}
func (*physicsMgrImpl) SetGlobalAirDrag(air_drag float64) {}
func (*physicsMgrImpl) GetGlobalAirDrag() float64 {
	return 0
}
func (*physicsMgrImpl) CheckCollisionRect(pos Vec2, size Vec2, collision_mask int64) gdx.Array {
	return nil
}
func (*physicsMgrImpl) CheckCollisionCircle(pos Vec2, radius float64, collision_mask int64) gdx.Array {
	return nil
}
func (*physicsMgrImpl) RaycastWithDetails(from Vec2, to Vec2, ignore_sprites gdx.Array, collision_mask int64, collide_with_areas bool, collide_with_bodies bool) gdx.Array {
	return nil
}

// IPlatformMgr
func (*platformMgrImpl) SetStretchMode(enable bool)                       {}
func (*platformMgrImpl) SetStretchAspect(is_keep bool)                    {}
func (*platformMgrImpl) SetStretchContentScale(width int64, height int64) {}
func (*platformMgrImpl) SetWindowPosition(pos Vec2)                       {}
func (*platformMgrImpl) GetWindowPosition() Vec2 {
	return Vec2{}
}
func (*platformMgrImpl) SetWindowSize(width int64, height int64, with_content_scale bool) {}
func (*platformMgrImpl) GetWindowSize() Vec2 {
	return Vec2{}
}
func (*platformMgrImpl) SetWindowTitle(title string) {}
func (*platformMgrImpl) GetWindowTitle() string {
	return ""
}
func (*platformMgrImpl) SetWindowFullscreen(enable bool) {}
func (*platformMgrImpl) IsWindowFullscreen() bool {
	return false
}
func (*platformMgrImpl) SetDebugMode(enable bool) {}
func (*platformMgrImpl) IsDebugMode() bool {
	return false
}
func (*platformMgrImpl) GetTimeScale() float64 {
	return 0
}
func (*platformMgrImpl) SetTimeScale(time_scale float64) {}
func (*platformMgrImpl) GetMaxFps() int64 {
	return 0
}
func (*platformMgrImpl) SetMaxFps(fps int64) {}
func (*platformMgrImpl) GetPersistantDataDir() string {
	return ""
}
func (*platformMgrImpl) SetPersistantDataDir(path string) {}
func (*platformMgrImpl) IsInPersistantDataDir(path string) bool {
	return false
}

// IResMgr
func (*resMgrImpl) CreateAnimation(p_sprite_type string, p_anim_name string, p_json_ctx string, fps int64, is_atlas bool) {
}
func (*resMgrImpl) SetLoadMode(is_direct_mode bool) {}
func (*resMgrImpl) GetLoadMode() bool {
	return false
}
func (*resMgrImpl) GetBoundFromAlpha(p_path string) Rect2 {
	return Rect2{}
}
func (*resMgrImpl) GetImageSize(p_path string) Vec2 {
	return Vec2{}
}
func (*resMgrImpl) ReadAllText(p_path string) string {
	return ""
}
func (*resMgrImpl) HasFile(p_path string) bool {
	return false
}
func (*resMgrImpl) ReloadTexture(path string)                           {}
func (*resMgrImpl) FreeStr(str string)                                  {}
func (*resMgrImpl) SetDefaultFont(font_path string)                     {}
func (*resMgrImpl) RegisterSvgFontFace(font_path string, family string) {}

// ISceneMgr
func (*sceneMgrImpl) ChangeSceneToFile(path string) {}
func (*sceneMgrImpl) DestroyAllSprites()            {}
func (*sceneMgrImpl) ReloadCurrentScene() int64 {
	return 0
}
func (*sceneMgrImpl) UnloadCurrentScene()                                          {}
func (*sceneMgrImpl) ClearPureSprites()                                            {}
func (*sceneMgrImpl) CreatePureSprite(texture_path string, pos Vec2, zindex int64) {}
func (*sceneMgrImpl) DestroyPureSprite(id gdx.Object)                              {}
func (*sceneMgrImpl) CreateRenderSprite(texture_path string, pos Vec2, degree float64, scale Vec2, zindex int64, pivot Vec2) gdx.Object {
	return 0
}
func (*sceneMgrImpl) CreateStaticSprite(texture_path string, pos Vec2, degree float64, scale Vec2, zindex int64, pivot Vec2, collider_type int64, collider_pivot Vec2, collider_params gdx.Array) gdx.Object {
	return 0
}

// ISpriteMgr
func (*spriteMgrImpl) SetDontDestroyOnLoad(obj gdx.Object)          {}
func (*spriteMgrImpl) SetProcess(obj gdx.Object, is_on bool)        {}
func (*spriteMgrImpl) SetPhysicProcess(obj gdx.Object, is_on bool)  {}
func (*spriteMgrImpl) SetTypeName(obj gdx.Object, type_name string) {}
func (*spriteMgrImpl) SetPivot(obj gdx.Object, pivot Vec2)          {}
func (*spriteMgrImpl) GetPivot(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) SetChildPosition(obj gdx.Object, path string, pos Vec2) {}
func (*spriteMgrImpl) GetChildPosition(obj gdx.Object, path string) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) SetChildRotation(obj gdx.Object, path string, rot float64) {}
func (*spriteMgrImpl) GetChildRotation(obj gdx.Object, path string) float64 {
	return 0
}
func (*spriteMgrImpl) SetChildScale(obj gdx.Object, path string, scale Vec2) {}
func (*spriteMgrImpl) GetChildScale(obj gdx.Object, path string) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) CheckCollision(obj gdx.Object, target gdx.Object, is_src_trigger bool, is_dst_trigger bool) bool {
	return false
}
func (*spriteMgrImpl) CheckCollisionWithPoint(obj gdx.Object, point Vec2, is_trigger bool) bool {
	return false
}
func (*spriteMgrImpl) SetDebugCollisionVisible(obj gdx.Object, visible bool) {}
func (*spriteMgrImpl) IsDebugCollisionVisible(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) CreateBackdrop(path string) gdx.Object {
	return 0
}
func (*spriteMgrImpl) CreateSprite(path string, pos Vec2) gdx.Object {
	return 0
}
func (*spriteMgrImpl) CreateBareSprite(pos Vec2) gdx.Object {
	return 0
}
func (*spriteMgrImpl) CloneSprite(obj gdx.Object) gdx.Object {
	return 0
}
func (*spriteMgrImpl) DestroySprite(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) IsSpriteAlive(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) SetPosition(obj gdx.Object, pos Vec2) {}
func (*spriteMgrImpl) GetPosition(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) SetRotation(obj gdx.Object, rot float64) {}
func (*spriteMgrImpl) GetRotation(obj gdx.Object) float64 {
	return 0
}
func (*spriteMgrImpl) SetScale(obj gdx.Object, scale Vec2) {}
func (*spriteMgrImpl) GetScale(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) SetRenderScale(obj gdx.Object, scale Vec2) {}
func (*spriteMgrImpl) GetRenderScale(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) SetColor(obj gdx.Object, color Color) {}
func (*spriteMgrImpl) GetColor(obj gdx.Object) Color {
	return Color{}
}
func (*spriteMgrImpl) SetMaterialShader(obj gdx.Object, path string) {}
func (*spriteMgrImpl) GetMaterialShader(obj gdx.Object) string {
	return ""
}
func (*spriteMgrImpl) SetMaterialParams(obj gdx.Object, effect string, amount float64) {}
func (*spriteMgrImpl) GetMaterialParams(obj gdx.Object, effect string) float64 {
	return 0
}
func (*spriteMgrImpl) SetMaterialParamsVec(obj gdx.Object, effect string, x float64, y float64, z float64, w float64) {
}
func (*spriteMgrImpl) SetMaterialParamsVec4(obj gdx.Object, effect string, vec4 Vec4) {}
func (*spriteMgrImpl) GetMaterialParamsVec4(obj gdx.Object, effect string) Vec4 {
	return Vec4{}
}
func (*spriteMgrImpl) SetMaterialParamsColor(obj gdx.Object, effect string, color Color) {}
func (*spriteMgrImpl) GetMaterialParamsColor(obj gdx.Object, effect string) Color {
	return Color{}
}
func (*spriteMgrImpl) SetTextureAtlas(obj gdx.Object, path string, rect2 Rect2)       {}
func (*spriteMgrImpl) SetTexture(obj gdx.Object, path string)                         {}
func (*spriteMgrImpl) SetTextureAtlasDirect(obj gdx.Object, path string, rect2 Rect2) {}
func (*spriteMgrImpl) SetTextureDirect(obj gdx.Object, path string)                   {}
func (*spriteMgrImpl) GetTexture(obj gdx.Object) string {
	return ""
}
func (*spriteMgrImpl) SetVisible(obj gdx.Object, visible bool) {}
func (*spriteMgrImpl) GetVisible(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) GetZIndex(obj gdx.Object) int64 {
	return 0
}
func (*spriteMgrImpl) SetZIndex(obj gdx.Object, z int64) {}
func (*spriteMgrImpl) PlayAnim(obj gdx.Object, p_name string, p_speed float64, isLoop bool, p_revert bool) {
}
func (*spriteMgrImpl) PlayBackwardsAnim(obj gdx.Object, p_name string) {}
func (*spriteMgrImpl) PauseAnim(obj gdx.Object)                        {}
func (*spriteMgrImpl) StopAnim(obj gdx.Object)                         {}
func (*spriteMgrImpl) IsPlayingAnim(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) SetAnim(obj gdx.Object, p_name string) {}
func (*spriteMgrImpl) GetAnim(obj gdx.Object) string {
	return ""
}
func (*spriteMgrImpl) SetAnimFrame(obj gdx.Object, p_frame int64) {}
func (*spriteMgrImpl) GetAnimFrame(obj gdx.Object) int64 {
	return 0
}
func (*spriteMgrImpl) SetAnimSpeedScale(obj gdx.Object, p_speed_scale float64) {}
func (*spriteMgrImpl) GetAnimSpeedScale(obj gdx.Object) float64 {
	return 0
}
func (*spriteMgrImpl) GetAnimPlayingSpeed(obj gdx.Object) float64 {
	return 0
}
func (*spriteMgrImpl) SetAnimCentered(obj gdx.Object, p_center bool) {}
func (*spriteMgrImpl) IsAnimCentered(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) SetAnimOffset(obj gdx.Object, p_offset Vec2) {}
func (*spriteMgrImpl) GetAnimOffset(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) SetAnimFlipH(obj gdx.Object, p_flip bool) {}
func (*spriteMgrImpl) IsAnimFlippedH(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) SetAnimFlipV(obj gdx.Object, p_flip bool) {}
func (*spriteMgrImpl) IsAnimFlippedV(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) GetCurrentAnimName(obj gdx.Object) string {
	return ""
}
func (*spriteMgrImpl) SetVelocity(obj gdx.Object, velocity Vec2) {}
func (*spriteMgrImpl) GetVelocity(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) IsOnFloor(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) IsOnFloorOnly(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) IsOnWall(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) IsOnWallOnly(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) IsOnCeiling(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) IsOnCeilingOnly(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) GetLastMotion(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) GetPositionDelta(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) GetFloorNormal(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) GetWallNormal(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) GetRealVelocity(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*spriteMgrImpl) MoveAndSlide(obj gdx.Object)                {}
func (*spriteMgrImpl) SetGravity(obj gdx.Object, gravity float64) {}
func (*spriteMgrImpl) GetGravity(obj gdx.Object) float64 {
	return 0
}
func (*spriteMgrImpl) SetMass(obj gdx.Object, mass float64) {}
func (*spriteMgrImpl) GetMass(obj gdx.Object) float64 {
	return 0
}
func (*spriteMgrImpl) AddForce(obj gdx.Object, force Vec2)       {}
func (*spriteMgrImpl) AddImpulse(obj gdx.Object, impulse Vec2)   {}
func (*spriteMgrImpl) SetPhysicsMode(obj gdx.Object, mode int64) {}
func (*spriteMgrImpl) GetPhysicsMode(obj gdx.Object) int64 {
	return 0
}
func (*spriteMgrImpl) SetUseGravity(obj gdx.Object, enabled bool) {}
func (*spriteMgrImpl) IsUseGravity(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) SetGravityScale(obj gdx.Object, scale float64) {}
func (*spriteMgrImpl) GetGravityScale(obj gdx.Object) float64 {
	return 0
}
func (*spriteMgrImpl) SetDrag(obj gdx.Object, drag float64) {}
func (*spriteMgrImpl) GetDrag(obj gdx.Object) float64 {
	return 0
}
func (*spriteMgrImpl) SetFriction(obj gdx.Object, friction float64) {}
func (*spriteMgrImpl) GetFriction(obj gdx.Object) float64 {
	return 0
}
func (*spriteMgrImpl) SetCollisionLayer(obj gdx.Object, layer int64) {}
func (*spriteMgrImpl) GetCollisionLayer(obj gdx.Object) int64 {
	return 0
}
func (*spriteMgrImpl) SetCollisionMask(obj gdx.Object, mask int64) {}
func (*spriteMgrImpl) GetCollisionMask(obj gdx.Object) int64 {
	return 0
}
func (*spriteMgrImpl) SetTriggerLayer(obj gdx.Object, layer int64) {}
func (*spriteMgrImpl) GetTriggerLayer(obj gdx.Object) int64 {
	return 0
}
func (*spriteMgrImpl) SetTriggerMask(obj gdx.Object, mask int64) {}
func (*spriteMgrImpl) GetTriggerMask(obj gdx.Object) int64 {
	return 0
}
func (*spriteMgrImpl) SetColliderRect(obj gdx.Object, center Vec2, size Vec2)           {}
func (*spriteMgrImpl) SetColliderCircle(obj gdx.Object, center Vec2, radius float64)    {}
func (*spriteMgrImpl) SetColliderCapsule(obj gdx.Object, center Vec2, size Vec2)        {}
func (*spriteMgrImpl) SetColliderPolygon(obj gdx.Object, center Vec2, points gdx.Array) {}
func (*spriteMgrImpl) SetCollisionEnabled(obj gdx.Object, enabled bool)                 {}
func (*spriteMgrImpl) IsCollisionEnabled(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) SetTriggerRect(obj gdx.Object, center Vec2, size Vec2)           {}
func (*spriteMgrImpl) SetTriggerCircle(obj gdx.Object, center Vec2, radius float64)    {}
func (*spriteMgrImpl) SetTriggerCapsule(obj gdx.Object, center Vec2, size Vec2)        {}
func (*spriteMgrImpl) SetTriggerPolygon(obj gdx.Object, center Vec2, points gdx.Array) {}
func (*spriteMgrImpl) SetTriggerEnabled(obj gdx.Object, trigger bool)                  {}
func (*spriteMgrImpl) IsTriggerEnabled(obj gdx.Object) bool {
	return false
}
func (*spriteMgrImpl) CheckCollisionByColor(obj gdx.Object, color Color, color_threshold float64, alpha_threshold float64) bool {
	return false
}
func (*spriteMgrImpl) CheckCollisionByColors(obj gdx.Object, sprite_color Color, target_color Color, color_threshold float64, alpha_threshold float64) bool {
	return false
}
func (*spriteMgrImpl) CheckCollisionByAlpha(obj gdx.Object, alpha_threshold float64) bool {
	return false
}
func (*spriteMgrImpl) CheckCollisionWithSprite(obj gdx.Object, obj_b gdx.Object, alpha_threshold float64, use_pixel_perfect bool) bool {
	return false
}
func (*spriteMgrImpl) SetPixelCollisionSamplingStep(step int64) {}
func (*spriteMgrImpl) GetPixelCollisionSamplingStep() int64 {
	return 0
}
func (*spriteMgrImpl) BatchUpdateTransforms(buffer []float32) {}
func (*spriteMgrImpl) BatchUpdateVisuals(buffer []float32)    {}
func (*spriteMgrImpl) BatchRetrievePositions(objs gdx.Array) gdx.Array {
	return nil
}

// ITilemapMgr
func (*tilemapMgrImpl) OpenDrawTilesWithSize(tile_size int64)                                    {}
func (*tilemapMgrImpl) OpenDrawTiles()                                                           {}
func (*tilemapMgrImpl) SetLayerIndex(index int64)                                                {}
func (*tilemapMgrImpl) SetTile(texture_path string, with_collision bool)                         {}
func (*tilemapMgrImpl) SetTileWithCollisionInfo(texture_path string, collision_points gdx.Array) {}
func (*tilemapMgrImpl) SetLayerOffset(index int64, offset Vec2)                                  {}
func (*tilemapMgrImpl) GetLayerOffset(index int64) Vec2 {
	return Vec2{}
}
func (*tilemapMgrImpl) PlaceTiles(positions gdx.Array, texture_path string) {}
func (*tilemapMgrImpl) PlaceTilesWithLayer(positions gdx.Array, texture_path string, layer_index int64) {
}
func (*tilemapMgrImpl) PlaceTile(pos Vec2, texture_path string)                             {}
func (*tilemapMgrImpl) PlaceTileWithLayer(pos Vec2, texture_path string, layer_index int64) {}
func (*tilemapMgrImpl) EraseTile(pos Vec2)                                                  {}
func (*tilemapMgrImpl) EraseTileWithLayer(pos Vec2, layer_index int64)                      {}
func (*tilemapMgrImpl) GetTile(pos Vec2) string {
	return ""
}
func (*tilemapMgrImpl) GetTileWithLayer(pos Vec2, layer_index int64) string {
	return ""
}
func (*tilemapMgrImpl) CloseDrawTiles()        {}
func (*tilemapMgrImpl) ExitTilemapEditorMode() {}

// ITilemapparserMgr
func (*tilemapparserMgrImpl) LoadTilemap(json_path string) {}
func (*tilemapparserMgrImpl) UnloadTilemap(name string)    {}
func (*tilemapparserMgrImpl) DestroyAllTilemaps()          {}
func (*tilemapparserMgrImpl) HasTilemap(name string) bool {
	return false
}
func (*tilemapparserMgrImpl) GetTilemapLayerCount(name string) int64 {
	return 0
}

// IUiMgr
func (*uiMgrImpl) BindNode(obj gdx.Object, rel_path string) gdx.Object {
	return 0
}
func (*uiMgrImpl) CreateNode(path string) gdx.Object {
	return 0
}
func (*uiMgrImpl) CreateButton(path string, text string) gdx.Object {
	return 0
}
func (*uiMgrImpl) CreateLabel(path string, text string) gdx.Object {
	return 0
}
func (*uiMgrImpl) CreateImage(path string) gdx.Object {
	return 0
}
func (*uiMgrImpl) CreateToggle(path string, value bool) gdx.Object {
	return 0
}
func (*uiMgrImpl) CreateSlider(path string, value float64) gdx.Object {
	return 0
}
func (*uiMgrImpl) CreateInput(path string, text string) gdx.Object {
	return 0
}
func (*uiMgrImpl) DestroyNode(obj gdx.Object) bool {
	return false
}
func (*uiMgrImpl) GetType(obj gdx.Object) int64 {
	return 0
}
func (*uiMgrImpl) SetText(obj gdx.Object, text string) {}
func (*uiMgrImpl) GetText(obj gdx.Object) string {
	return ""
}
func (*uiMgrImpl) SetTexture(obj gdx.Object, path string) {}
func (*uiMgrImpl) GetTexture(obj gdx.Object) string {
	return ""
}
func (*uiMgrImpl) SetColor(obj gdx.Object, color Color) {}
func (*uiMgrImpl) GetColor(obj gdx.Object) Color {
	return Color{}
}
func (*uiMgrImpl) SetFontSize(obj gdx.Object, size int64) {}
func (*uiMgrImpl) GetFontSize(obj gdx.Object) int64 {
	return 0
}
func (*uiMgrImpl) SetVisible(obj gdx.Object, visible bool) {}
func (*uiMgrImpl) GetVisible(obj gdx.Object) bool {
	return false
}
func (*uiMgrImpl) SetInteractable(obj gdx.Object, interactable bool) {}
func (*uiMgrImpl) GetInteractable(obj gdx.Object) bool {
	return false
}
func (*uiMgrImpl) SetRect(obj gdx.Object, rect Rect2) {}
func (*uiMgrImpl) GetRect(obj gdx.Object) Rect2 {
	return Rect2{}
}
func (*uiMgrImpl) GetLayoutDirection(obj gdx.Object) int64 {
	return 0
}
func (*uiMgrImpl) SetLayoutDirection(obj gdx.Object, value int64) {}
func (*uiMgrImpl) GetLayoutMode(obj gdx.Object) int64 {
	return 0
}
func (*uiMgrImpl) SetLayoutMode(obj gdx.Object, value int64) {}
func (*uiMgrImpl) GetAnchorsPreset(obj gdx.Object) int64 {
	return 0
}
func (*uiMgrImpl) SetAnchorsPreset(obj gdx.Object, value int64) {}
func (*uiMgrImpl) GetScale(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*uiMgrImpl) SetScale(obj gdx.Object, value Vec2) {}
func (*uiMgrImpl) GetPosition(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*uiMgrImpl) SetPosition(obj gdx.Object, value Vec2) {}
func (*uiMgrImpl) GetSize(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*uiMgrImpl) SetSize(obj gdx.Object, value Vec2) {}
func (*uiMgrImpl) GetGlobalPosition(obj gdx.Object) Vec2 {
	return Vec2{}
}
func (*uiMgrImpl) SetGlobalPosition(obj gdx.Object, value Vec2) {}
func (*uiMgrImpl) GetRotation(obj gdx.Object) float64 {
	return 0
}
func (*uiMgrImpl) SetRotation(obj gdx.Object, value float64) {}
func (*uiMgrImpl) GetFlip(obj gdx.Object, horizontal bool) bool {
	return false
}
func (*uiMgrImpl) SetFlip(obj gdx.Object, horizontal bool, is_flip bool) {}
