/*
 * Copyright (c) 2021 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// export by github.com/goplus/ixgo/cmd/qexp

package spx

import (
	q "github.com/goplus/spx/v2"

	"go/constant"
	"go/token"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "spx",
		Path: "github.com/goplus/spx/v2",
		Deps: map[string]string{
			"context":                           "context",
			"errors":                            "errors",
			"flag":                              "flag",
			"fmt":                               "fmt",
			"github.com/goplus/spbase/mathf":    "mathf",
			"github.com/goplus/spx/v2/fs":       "fs",
			"github.com/goplus/spx/v2/fs/asset": "asset",
			"github.com/goplus/spx/v2/fs/zip":   "zip",
			"github.com/goplus/spx/v2/internal/animation":       "animation",
			"github.com/goplus/spx/v2/internal/assets":          "assets",
			"github.com/goplus/spx/v2/internal/audio":           "audio",
			"github.com/goplus/spx/v2/internal/base/collision":  "collision",
			"github.com/goplus/spx/v2/internal/base/defaults":   "defaults",
			"github.com/goplus/spx/v2/internal/base/sliceutil":  "sliceutil",
			"github.com/goplus/spx/v2/internal/core/event":      "event",
			"github.com/goplus/spx/v2/internal/core/project":    "project",
			"github.com/goplus/spx/v2/internal/core/runtime":    "runtime",
			"github.com/goplus/spx/v2/internal/core/state":      "state",
			"github.com/goplus/spx/v2/internal/coroutine":       "coroutine",
			"github.com/goplus/spx/v2/internal/debug":           "debug",
			"github.com/goplus/spx/v2/internal/engine":          "engine",
			"github.com/goplus/spx/v2/internal/engine/platform": "platform",
			"github.com/goplus/spx/v2/internal/engine/profiler": "profiler",
			"github.com/goplus/spx/v2/internal/enginewrap":      "enginewrap",
			"github.com/goplus/spx/v2/internal/input":           "input",
			"github.com/goplus/spx/v2/internal/input/keycode":   "keycode",
			"github.com/goplus/spx/v2/internal/log":             "log",
			"github.com/goplus/spx/v2/internal/tilemap":         "tilemap",
			"github.com/goplus/spx/v2/internal/time":            "time",
			"github.com/goplus/spx/v2/internal/tools":           "tools",
			"github.com/goplus/spx/v2/internal/ui":              "ui",
			"github.com/goplus/spx/v2/pkg/spx/pkg/engine":       "engine",
			"maps":      "maps",
			"math":      "math",
			"math/rand": "rand",
			"os":        "os",
			"path":      "path",
			"reflect":   "reflect",
			"slices":    "slices",
			"strconv":   "strconv",
			"strings":   "strings",
			"sync":      "sync",
			"syscall":   "syscall",
			"time":      "time",
			"unsafe":    "unsafe",
		},
		Interfaces: map[string]reflect.Type{
			"Camera":      reflect.TypeOf((*q.Camera)(nil)).Elem(),
			"Gamer":       reflect.TypeOf((*q.Gamer)(nil)).Elem(),
			"Shape":       reflect.TypeOf((*q.Shape)(nil)).Elem(),
			"ShapeGetter": reflect.TypeOf((*q.ShapeGetter)(nil)).Elem(),
			"Sprite":      reflect.TypeOf((*q.Sprite)(nil)).Elem(),
			"Widget":      reflect.TypeOf((*q.Widget)(nil)).Elem(),
		},
		NamedTypes: map[string]reflect.Type{
			"Color":           reflect.TypeOf((*q.Color)(nil)).Elem(),
			"EffectKind":      reflect.TypeOf((*q.EffectKind)(nil)).Elem(),
			"Game":            reflect.TypeOf((*q.Game)(nil)).Elem(),
			"List":            reflect.TypeOf((*q.List)(nil)).Elem(),
			"Monitor":         reflect.TypeOf((*q.Monitor)(nil)).Elem(),
			"PenColorParam":   reflect.TypeOf((*q.PenColorParam)(nil)).Elem(),
			"RotationStyle":   reflect.TypeOf((*q.RotationStyle)(nil)).Elem(),
			"SoundEffectKind": reflect.TypeOf((*q.SoundEffectKind)(nil)).Elem(),
			"SpriteImpl":      reflect.TypeOf((*q.SpriteImpl)(nil)).Elem(),
			"Value":           reflect.TypeOf((*q.Value)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{
			"BackdropName":        reflect.TypeOf((*q.BackdropName)(nil)).Elem(),
			"ColliderShapeType":   reflect.TypeOf((*q.ColliderShapeType)(nil)).Elem(),
			"Config":              reflect.TypeOf((*q.Config)(nil)).Elem(),
			"DecoratorJSON":       reflect.TypeOf((*q.DecoratorJSON)(nil)).Elem(),
			"Direction":           reflect.TypeOf((*q.Direction)(nil)).Elem(),
			"IEventSinks":         reflect.TypeOf((*q.IEventSinks)(nil)).Elem(),
			"Key":                 reflect.TypeOf((*q.Key)(nil)).Elem(),
			"MsgName":             reflect.TypeOf((*q.MsgName)(nil)).Elem(),
			"PhysicsMode":         reflect.TypeOf((*q.PhysicsMode)(nil)).Elem(),
			"Pos":                 reflect.TypeOf((*q.Pos)(nil)).Elem(),
			"PropertyName":        reflect.TypeOf((*q.PropertyName)(nil)).Elem(),
			"SoundName":           reflect.TypeOf((*q.SoundName)(nil)).Elem(),
			"SpriteAnimationName": reflect.TypeOf((*q.SpriteAnimationName)(nil)).Elem(),
			"SpriteCostumeName":   reflect.TypeOf((*q.SpriteCostumeName)(nil)).Elem(),
			"SpriteName":          reflect.TypeOf((*q.SpriteName)(nil)).Elem(),
			"StopKind":            reflect.TypeOf((*q.StopKind)(nil)).Elem(),
			"WidgetName":          reflect.TypeOf((*q.WidgetName)(nil)).Elem(),
		},
		Vars: map[string]reflect.Value{},
		Funcs: map[string]reflect.Value{
			"Exit__0":          reflect.ValueOf(q.Exit__0),
			"Exit__1":          reflect.ValueOf(q.Exit__1),
			"Forever":          reflect.ValueOf(q.Forever),
			"GetWidget":        reflect.ValueOf(q.GetWidget),
			"HSB":              reflect.ValueOf(q.HSB),
			"HSBA":             reflect.ValueOf(q.HSBA),
			"Iround":           reflect.ValueOf(q.Iround),
			"KeyFromString":    reflect.ValueOf(q.KeyFromString),
			"NewList":          reflect.ValueOf(q.NewList),
			"NewValue":         reflect.ValueOf(q.NewValue),
			"Rand__0":          reflect.ValueOf(q.Rand__0),
			"Rand__1":          reflect.ValueOf(q.Rand__1),
			"Repeat":           reflect.ValueOf(q.Repeat),
			"RepeatUntil":      reflect.ValueOf(q.RepeatUntil),
			"Sched":            reflect.ValueOf(q.Sched),
			"SchedNow":         reflect.ValueOf(q.SchedNow),
			"SetDebug":         reflect.ValueOf(q.SetDebug),
			"WaitUntil":        reflect.ValueOf(q.WaitUntil),
			"XGot_Game_Main":   reflect.ValueOf(q.XGot_Game_Main),
			"XGot_Game_Reload": reflect.ValueOf(q.XGot_Game_Reload),
		},
		TypedConsts: map[string]ixgo.TypedConst{
			"AllOtherScripts":      {Typ: reflect.TypeOf(q.AllOtherScripts), Value: constant.MakeInt64(int64(q.AllOtherScripts))},
			"AllSprites":           {Typ: reflect.TypeOf(q.AllSprites), Value: constant.MakeInt64(int64(q.AllSprites))},
			"AllStop":              {Typ: reflect.TypeOf(q.AllStop), Value: constant.MakeInt64(int64(q.AllStop))},
			"AnimChannelFrame":     {Typ: reflect.TypeOf(q.AnimChannelFrame), Value: constant.MakeString(string(q.AnimChannelFrame))},
			"AnimChannelGlide":     {Typ: reflect.TypeOf(q.AnimChannelGlide), Value: constant.MakeString(string(q.AnimChannelGlide))},
			"AnimChannelMove":      {Typ: reflect.TypeOf(q.AnimChannelMove), Value: constant.MakeString(string(q.AnimChannelMove))},
			"AnimChannelTurn":      {Typ: reflect.TypeOf(q.AnimChannelTurn), Value: constant.MakeString(string(q.AnimChannelTurn))},
			"Back":                 {Typ: reflect.TypeOf(q.Back), Value: constant.MakeInt64(int64(q.Back))},
			"Backward":             {Typ: reflect.TypeOf(q.Backward), Value: constant.MakeInt64(int64(q.Backward))},
			"BrightnessEffect":     {Typ: reflect.TypeOf(q.BrightnessEffect), Value: constant.MakeInt64(int64(q.BrightnessEffect))},
			"CapsuleCollider":      {Typ: reflect.TypeOf(q.CapsuleCollider), Value: constant.MakeInt64(int64(q.CapsuleCollider))},
			"CircleCollider":       {Typ: reflect.TypeOf(q.CircleCollider), Value: constant.MakeInt64(int64(q.CircleCollider))},
			"ColorEffect":          {Typ: reflect.TypeOf(q.ColorEffect), Value: constant.MakeInt64(int64(q.ColorEffect))},
			"DbgFlagAll":           {Typ: reflect.TypeOf(q.DbgFlagAll), Value: constant.MakeInt64(int64(q.DbgFlagAll))},
			"DbgFlagEvent":         {Typ: reflect.TypeOf(q.DbgFlagEvent), Value: constant.MakeInt64(int64(q.DbgFlagEvent))},
			"DbgFlagInstr":         {Typ: reflect.TypeOf(q.DbgFlagInstr), Value: constant.MakeInt64(int64(q.DbgFlagInstr))},
			"DbgFlagLoad":          {Typ: reflect.TypeOf(q.DbgFlagLoad), Value: constant.MakeInt64(int64(q.DbgFlagLoad))},
			"DbgFlagPerf":          {Typ: reflect.TypeOf(q.DbgFlagPerf), Value: constant.MakeInt64(int64(q.DbgFlagPerf))},
			"Down":                 {Typ: reflect.TypeOf(q.Down), Value: constant.MakeFromLiteral("1.8e+2", token.FLOAT, 0)},
			"DynamicPhysics":       {Typ: reflect.TypeOf(q.DynamicPhysics), Value: constant.MakeInt64(int64(q.DynamicPhysics))},
			"Edge":                 {Typ: reflect.TypeOf(q.Edge), Value: constant.MakeInt64(int64(q.Edge))},
			"EdgeBottom":           {Typ: reflect.TypeOf(q.EdgeBottom), Value: constant.MakeInt64(int64(q.EdgeBottom))},
			"EdgeLeft":             {Typ: reflect.TypeOf(q.EdgeLeft), Value: constant.MakeInt64(int64(q.EdgeLeft))},
			"EdgeRight":            {Typ: reflect.TypeOf(q.EdgeRight), Value: constant.MakeInt64(int64(q.EdgeRight))},
			"EdgeTop":              {Typ: reflect.TypeOf(q.EdgeTop), Value: constant.MakeInt64(int64(q.EdgeTop))},
			"FishEyeEffect":        {Typ: reflect.TypeOf(q.FishEyeEffect), Value: constant.MakeInt64(int64(q.FishEyeEffect))},
			"Forward":              {Typ: reflect.TypeOf(q.Forward), Value: constant.MakeInt64(int64(q.Forward))},
			"Front":                {Typ: reflect.TypeOf(q.Front), Value: constant.MakeInt64(int64(q.Front))},
			"GhostEffect":          {Typ: reflect.TypeOf(q.GhostEffect), Value: constant.MakeInt64(int64(q.GhostEffect))},
			"Invalid":              {Typ: reflect.TypeOf(q.Invalid), Value: constant.MakeInt64(int64(q.Invalid))},
			"Key0":                 {Typ: reflect.TypeOf(q.Key0), Value: constant.MakeInt64(int64(q.Key0))},
			"Key1":                 {Typ: reflect.TypeOf(q.Key1), Value: constant.MakeInt64(int64(q.Key1))},
			"Key2":                 {Typ: reflect.TypeOf(q.Key2), Value: constant.MakeInt64(int64(q.Key2))},
			"Key3":                 {Typ: reflect.TypeOf(q.Key3), Value: constant.MakeInt64(int64(q.Key3))},
			"Key4":                 {Typ: reflect.TypeOf(q.Key4), Value: constant.MakeInt64(int64(q.Key4))},
			"Key5":                 {Typ: reflect.TypeOf(q.Key5), Value: constant.MakeInt64(int64(q.Key5))},
			"Key6":                 {Typ: reflect.TypeOf(q.Key6), Value: constant.MakeInt64(int64(q.Key6))},
			"Key7":                 {Typ: reflect.TypeOf(q.Key7), Value: constant.MakeInt64(int64(q.Key7))},
			"Key8":                 {Typ: reflect.TypeOf(q.Key8), Value: constant.MakeInt64(int64(q.Key8))},
			"Key9":                 {Typ: reflect.TypeOf(q.Key9), Value: constant.MakeInt64(int64(q.Key9))},
			"KeyA":                 {Typ: reflect.TypeOf(q.KeyA), Value: constant.MakeInt64(int64(q.KeyA))},
			"KeyAlt":               {Typ: reflect.TypeOf(q.KeyAlt), Value: constant.MakeInt64(int64(q.KeyAlt))},
			"KeyAny":               {Typ: reflect.TypeOf(q.KeyAny), Value: constant.MakeInt64(int64(q.KeyAny))},
			"KeyApostrophe":        {Typ: reflect.TypeOf(q.KeyApostrophe), Value: constant.MakeInt64(int64(q.KeyApostrophe))},
			"KeyB":                 {Typ: reflect.TypeOf(q.KeyB), Value: constant.MakeInt64(int64(q.KeyB))},
			"KeyBackslash":         {Typ: reflect.TypeOf(q.KeyBackslash), Value: constant.MakeInt64(int64(q.KeyBackslash))},
			"KeyBackspace":         {Typ: reflect.TypeOf(q.KeyBackspace), Value: constant.MakeInt64(int64(q.KeyBackspace))},
			"KeyC":                 {Typ: reflect.TypeOf(q.KeyC), Value: constant.MakeInt64(int64(q.KeyC))},
			"KeyCapsLock":          {Typ: reflect.TypeOf(q.KeyCapsLock), Value: constant.MakeInt64(int64(q.KeyCapsLock))},
			"KeyComma":             {Typ: reflect.TypeOf(q.KeyComma), Value: constant.MakeInt64(int64(q.KeyComma))},
			"KeyControl":           {Typ: reflect.TypeOf(q.KeyControl), Value: constant.MakeInt64(int64(q.KeyControl))},
			"KeyD":                 {Typ: reflect.TypeOf(q.KeyD), Value: constant.MakeInt64(int64(q.KeyD))},
			"KeyDelete":            {Typ: reflect.TypeOf(q.KeyDelete), Value: constant.MakeInt64(int64(q.KeyDelete))},
			"KeyDown":              {Typ: reflect.TypeOf(q.KeyDown), Value: constant.MakeInt64(int64(q.KeyDown))},
			"KeyE":                 {Typ: reflect.TypeOf(q.KeyE), Value: constant.MakeInt64(int64(q.KeyE))},
			"KeyEnd":               {Typ: reflect.TypeOf(q.KeyEnd), Value: constant.MakeInt64(int64(q.KeyEnd))},
			"KeyEnter":             {Typ: reflect.TypeOf(q.KeyEnter), Value: constant.MakeInt64(int64(q.KeyEnter))},
			"KeyEqual":             {Typ: reflect.TypeOf(q.KeyEqual), Value: constant.MakeInt64(int64(q.KeyEqual))},
			"KeyEscape":            {Typ: reflect.TypeOf(q.KeyEscape), Value: constant.MakeInt64(int64(q.KeyEscape))},
			"KeyF":                 {Typ: reflect.TypeOf(q.KeyF), Value: constant.MakeInt64(int64(q.KeyF))},
			"KeyF1":                {Typ: reflect.TypeOf(q.KeyF1), Value: constant.MakeInt64(int64(q.KeyF1))},
			"KeyF10":               {Typ: reflect.TypeOf(q.KeyF10), Value: constant.MakeInt64(int64(q.KeyF10))},
			"KeyF11":               {Typ: reflect.TypeOf(q.KeyF11), Value: constant.MakeInt64(int64(q.KeyF11))},
			"KeyF12":               {Typ: reflect.TypeOf(q.KeyF12), Value: constant.MakeInt64(int64(q.KeyF12))},
			"KeyF2":                {Typ: reflect.TypeOf(q.KeyF2), Value: constant.MakeInt64(int64(q.KeyF2))},
			"KeyF3":                {Typ: reflect.TypeOf(q.KeyF3), Value: constant.MakeInt64(int64(q.KeyF3))},
			"KeyF4":                {Typ: reflect.TypeOf(q.KeyF4), Value: constant.MakeInt64(int64(q.KeyF4))},
			"KeyF5":                {Typ: reflect.TypeOf(q.KeyF5), Value: constant.MakeInt64(int64(q.KeyF5))},
			"KeyF6":                {Typ: reflect.TypeOf(q.KeyF6), Value: constant.MakeInt64(int64(q.KeyF6))},
			"KeyF7":                {Typ: reflect.TypeOf(q.KeyF7), Value: constant.MakeInt64(int64(q.KeyF7))},
			"KeyF8":                {Typ: reflect.TypeOf(q.KeyF8), Value: constant.MakeInt64(int64(q.KeyF8))},
			"KeyF9":                {Typ: reflect.TypeOf(q.KeyF9), Value: constant.MakeInt64(int64(q.KeyF9))},
			"KeyG":                 {Typ: reflect.TypeOf(q.KeyG), Value: constant.MakeInt64(int64(q.KeyG))},
			"KeyGraveAccent":       {Typ: reflect.TypeOf(q.KeyGraveAccent), Value: constant.MakeInt64(int64(q.KeyGraveAccent))},
			"KeyH":                 {Typ: reflect.TypeOf(q.KeyH), Value: constant.MakeInt64(int64(q.KeyH))},
			"KeyHome":              {Typ: reflect.TypeOf(q.KeyHome), Value: constant.MakeInt64(int64(q.KeyHome))},
			"KeyI":                 {Typ: reflect.TypeOf(q.KeyI), Value: constant.MakeInt64(int64(q.KeyI))},
			"KeyInsert":            {Typ: reflect.TypeOf(q.KeyInsert), Value: constant.MakeInt64(int64(q.KeyInsert))},
			"KeyJ":                 {Typ: reflect.TypeOf(q.KeyJ), Value: constant.MakeInt64(int64(q.KeyJ))},
			"KeyK":                 {Typ: reflect.TypeOf(q.KeyK), Value: constant.MakeInt64(int64(q.KeyK))},
			"KeyKP0":               {Typ: reflect.TypeOf(q.KeyKP0), Value: constant.MakeInt64(int64(q.KeyKP0))},
			"KeyKP1":               {Typ: reflect.TypeOf(q.KeyKP1), Value: constant.MakeInt64(int64(q.KeyKP1))},
			"KeyKP2":               {Typ: reflect.TypeOf(q.KeyKP2), Value: constant.MakeInt64(int64(q.KeyKP2))},
			"KeyKP3":               {Typ: reflect.TypeOf(q.KeyKP3), Value: constant.MakeInt64(int64(q.KeyKP3))},
			"KeyKP4":               {Typ: reflect.TypeOf(q.KeyKP4), Value: constant.MakeInt64(int64(q.KeyKP4))},
			"KeyKP5":               {Typ: reflect.TypeOf(q.KeyKP5), Value: constant.MakeInt64(int64(q.KeyKP5))},
			"KeyKP6":               {Typ: reflect.TypeOf(q.KeyKP6), Value: constant.MakeInt64(int64(q.KeyKP6))},
			"KeyKP7":               {Typ: reflect.TypeOf(q.KeyKP7), Value: constant.MakeInt64(int64(q.KeyKP7))},
			"KeyKP8":               {Typ: reflect.TypeOf(q.KeyKP8), Value: constant.MakeInt64(int64(q.KeyKP8))},
			"KeyKP9":               {Typ: reflect.TypeOf(q.KeyKP9), Value: constant.MakeInt64(int64(q.KeyKP9))},
			"KeyKPDecimal":         {Typ: reflect.TypeOf(q.KeyKPDecimal), Value: constant.MakeInt64(int64(q.KeyKPDecimal))},
			"KeyKPDivide":          {Typ: reflect.TypeOf(q.KeyKPDivide), Value: constant.MakeInt64(int64(q.KeyKPDivide))},
			"KeyKPEnter":           {Typ: reflect.TypeOf(q.KeyKPEnter), Value: constant.MakeInt64(int64(q.KeyKPEnter))},
			"KeyKPEqual":           {Typ: reflect.TypeOf(q.KeyKPEqual), Value: constant.MakeInt64(int64(q.KeyKPEqual))},
			"KeyKPMultiply":        {Typ: reflect.TypeOf(q.KeyKPMultiply), Value: constant.MakeInt64(int64(q.KeyKPMultiply))},
			"KeyKPSubtract":        {Typ: reflect.TypeOf(q.KeyKPSubtract), Value: constant.MakeInt64(int64(q.KeyKPSubtract))},
			"KeyL":                 {Typ: reflect.TypeOf(q.KeyL), Value: constant.MakeInt64(int64(q.KeyL))},
			"KeyLeft":              {Typ: reflect.TypeOf(q.KeyLeft), Value: constant.MakeInt64(int64(q.KeyLeft))},
			"KeyLeftBracket":       {Typ: reflect.TypeOf(q.KeyLeftBracket), Value: constant.MakeInt64(int64(q.KeyLeftBracket))},
			"KeyM":                 {Typ: reflect.TypeOf(q.KeyM), Value: constant.MakeInt64(int64(q.KeyM))},
			"KeyMax":               {Typ: reflect.TypeOf(q.KeyMax), Value: constant.MakeInt64(int64(q.KeyMax))},
			"KeyMenu":              {Typ: reflect.TypeOf(q.KeyMenu), Value: constant.MakeInt64(int64(q.KeyMenu))},
			"KeyMinus":             {Typ: reflect.TypeOf(q.KeyMinus), Value: constant.MakeInt64(int64(q.KeyMinus))},
			"KeyN":                 {Typ: reflect.TypeOf(q.KeyN), Value: constant.MakeInt64(int64(q.KeyN))},
			"KeyNumLock":           {Typ: reflect.TypeOf(q.KeyNumLock), Value: constant.MakeInt64(int64(q.KeyNumLock))},
			"KeyO":                 {Typ: reflect.TypeOf(q.KeyO), Value: constant.MakeInt64(int64(q.KeyO))},
			"KeyP":                 {Typ: reflect.TypeOf(q.KeyP), Value: constant.MakeInt64(int64(q.KeyP))},
			"KeyPageDown":          {Typ: reflect.TypeOf(q.KeyPageDown), Value: constant.MakeInt64(int64(q.KeyPageDown))},
			"KeyPageUp":            {Typ: reflect.TypeOf(q.KeyPageUp), Value: constant.MakeInt64(int64(q.KeyPageUp))},
			"KeyPause":             {Typ: reflect.TypeOf(q.KeyPause), Value: constant.MakeInt64(int64(q.KeyPause))},
			"KeyPeriod":            {Typ: reflect.TypeOf(q.KeyPeriod), Value: constant.MakeInt64(int64(q.KeyPeriod))},
			"KeyPrintScreen":       {Typ: reflect.TypeOf(q.KeyPrintScreen), Value: constant.MakeInt64(int64(q.KeyPrintScreen))},
			"KeyQ":                 {Typ: reflect.TypeOf(q.KeyQ), Value: constant.MakeInt64(int64(q.KeyQ))},
			"KeyR":                 {Typ: reflect.TypeOf(q.KeyR), Value: constant.MakeInt64(int64(q.KeyR))},
			"KeyRight":             {Typ: reflect.TypeOf(q.KeyRight), Value: constant.MakeInt64(int64(q.KeyRight))},
			"KeyRightBracket":      {Typ: reflect.TypeOf(q.KeyRightBracket), Value: constant.MakeInt64(int64(q.KeyRightBracket))},
			"KeyS":                 {Typ: reflect.TypeOf(q.KeyS), Value: constant.MakeInt64(int64(q.KeyS))},
			"KeyScrollLock":        {Typ: reflect.TypeOf(q.KeyScrollLock), Value: constant.MakeInt64(int64(q.KeyScrollLock))},
			"KeySemicolon":         {Typ: reflect.TypeOf(q.KeySemicolon), Value: constant.MakeInt64(int64(q.KeySemicolon))},
			"KeyShift":             {Typ: reflect.TypeOf(q.KeyShift), Value: constant.MakeInt64(int64(q.KeyShift))},
			"KeySlash":             {Typ: reflect.TypeOf(q.KeySlash), Value: constant.MakeInt64(int64(q.KeySlash))},
			"KeySpace":             {Typ: reflect.TypeOf(q.KeySpace), Value: constant.MakeInt64(int64(q.KeySpace))},
			"KeyT":                 {Typ: reflect.TypeOf(q.KeyT), Value: constant.MakeInt64(int64(q.KeyT))},
			"KeyTab":               {Typ: reflect.TypeOf(q.KeyTab), Value: constant.MakeInt64(int64(q.KeyTab))},
			"KeyU":                 {Typ: reflect.TypeOf(q.KeyU), Value: constant.MakeInt64(int64(q.KeyU))},
			"KeyUp":                {Typ: reflect.TypeOf(q.KeyUp), Value: constant.MakeInt64(int64(q.KeyUp))},
			"KeyV":                 {Typ: reflect.TypeOf(q.KeyV), Value: constant.MakeInt64(int64(q.KeyV))},
			"KeyW":                 {Typ: reflect.TypeOf(q.KeyW), Value: constant.MakeInt64(int64(q.KeyW))},
			"KeyX":                 {Typ: reflect.TypeOf(q.KeyX), Value: constant.MakeInt64(int64(q.KeyX))},
			"KeyY":                 {Typ: reflect.TypeOf(q.KeyY), Value: constant.MakeInt64(int64(q.KeyY))},
			"KeyZ":                 {Typ: reflect.TypeOf(q.KeyZ), Value: constant.MakeInt64(int64(q.KeyZ))},
			"KinematicPhysics":     {Typ: reflect.TypeOf(q.KinematicPhysics), Value: constant.MakeInt64(int64(q.KinematicPhysics))},
			"Last":                 {Typ: reflect.TypeOf(q.Last), Value: constant.MakeInt64(int64(q.Last))},
			"Left":                 {Typ: reflect.TypeOf(q.Left), Value: constant.MakeFromLiteral("-.9e+2", token.FLOAT, 0)},
			"LeftRight":            {Typ: reflect.TypeOf(q.LeftRight), Value: constant.MakeInt64(int64(q.LeftRight))},
			"MOUSE_BUTTON_LEFT":    {Typ: reflect.TypeOf(q.MOUSE_BUTTON_LEFT), Value: constant.MakeInt64(int64(q.MOUSE_BUTTON_LEFT))},
			"MOUSE_BUTTON_MIDDLE":  {Typ: reflect.TypeOf(q.MOUSE_BUTTON_MIDDLE), Value: constant.MakeInt64(int64(q.MOUSE_BUTTON_MIDDLE))},
			"MOUSE_BUTTON_RIGHT":   {Typ: reflect.TypeOf(q.MOUSE_BUTTON_RIGHT), Value: constant.MakeInt64(int64(q.MOUSE_BUTTON_RIGHT))},
			"MosaicEffect":         {Typ: reflect.TypeOf(q.MosaicEffect), Value: constant.MakeInt64(int64(q.MosaicEffect))},
			"Mouse":                {Typ: reflect.TypeOf(q.Mouse), Value: constant.MakeInt64(int64(q.Mouse))},
			"Next":                 {Typ: reflect.TypeOf(q.Next), Value: constant.MakeInt64(int64(q.Next))},
			"NoPhysics":            {Typ: reflect.TypeOf(q.NoPhysics), Value: constant.MakeInt64(int64(q.NoPhysics))},
			"None":                 {Typ: reflect.TypeOf(q.None), Value: constant.MakeInt64(int64(q.None))},
			"Normal":               {Typ: reflect.TypeOf(q.Normal), Value: constant.MakeInt64(int64(q.Normal))},
			"OtherScriptsInSprite": {Typ: reflect.TypeOf(q.OtherScriptsInSprite), Value: constant.MakeInt64(int64(q.OtherScriptsInSprite))},
			"PenBrightness":        {Typ: reflect.TypeOf(q.PenBrightness), Value: constant.MakeInt64(int64(q.PenBrightness))},
			"PenHue":               {Typ: reflect.TypeOf(q.PenHue), Value: constant.MakeInt64(int64(q.PenHue))},
			"PenSaturation":        {Typ: reflect.TypeOf(q.PenSaturation), Value: constant.MakeInt64(int64(q.PenSaturation))},
			"PenTransparency":      {Typ: reflect.TypeOf(q.PenTransparency), Value: constant.MakeInt64(int64(q.PenTransparency))},
			"PixelateEffect":       {Typ: reflect.TypeOf(q.PixelateEffect), Value: constant.MakeInt64(int64(q.PixelateEffect))},
			"PolygonCollider":      {Typ: reflect.TypeOf(q.PolygonCollider), Value: constant.MakeInt64(int64(q.PolygonCollider))},
			"Prev":                 {Typ: reflect.TypeOf(q.Prev), Value: constant.MakeInt64(int64(q.Prev))},
			"Random":               {Typ: reflect.TypeOf(q.Random), Value: constant.MakeInt64(int64(q.Random))},
			"RectCollider":         {Typ: reflect.TypeOf(q.RectCollider), Value: constant.MakeInt64(int64(q.RectCollider))},
			"Right":                {Typ: reflect.TypeOf(q.Right), Value: constant.MakeFromLiteral("9.e+1", token.FLOAT, 0)},
			"SoundPanEffect":       {Typ: reflect.TypeOf(q.SoundPanEffect), Value: constant.MakeInt64(int64(q.SoundPanEffect))},
			"SoundPitchEffect":     {Typ: reflect.TypeOf(q.SoundPitchEffect), Value: constant.MakeInt64(int64(q.SoundPitchEffect))},
			"StateDie":             {Typ: reflect.TypeOf(q.StateDie), Value: constant.MakeString(string(q.StateDie))},
			"StateGlide":           {Typ: reflect.TypeOf(q.StateGlide), Value: constant.MakeString(string(q.StateGlide))},
			"StateStep":            {Typ: reflect.TypeOf(q.StateStep), Value: constant.MakeString(string(q.StateStep))},
			"StateTurn":            {Typ: reflect.TypeOf(q.StateTurn), Value: constant.MakeString(string(q.StateTurn))},
			"StaticPhysics":        {Typ: reflect.TypeOf(q.StaticPhysics), Value: constant.MakeInt64(int64(q.StaticPhysics))},
			"ThisScript":           {Typ: reflect.TypeOf(q.ThisScript), Value: constant.MakeInt64(int64(q.ThisScript))},
			"ThisSprite":           {Typ: reflect.TypeOf(q.ThisSprite), Value: constant.MakeInt64(int64(q.ThisSprite))},
			"TriggerExtraPixel":    {Typ: reflect.TypeOf(q.TriggerExtraPixel), Value: constant.MakeFromLiteral("2.e+0", token.FLOAT, 0)},
			"Up":                   {Typ: reflect.TypeOf(q.Up), Value: constant.MakeFromLiteral("0", token.FLOAT, 0)},
			"WhirlEffect":          {Typ: reflect.TypeOf(q.WhirlEffect), Value: constant.MakeInt64(int64(q.WhirlEffect))},
		},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"All":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.All))},
			"GopPackage": {Typ: "untyped bool", Value: constant.MakeBool(bool(q.GopPackage))},
			"Gop_sched":  {Typ: "untyped string", Value: constant.MakeString(string(q.Gop_sched))},
		},
	})
}
