//go:build !js && !wasm

/*
 * Copyright (c) 2021 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*------------------------------------------------------------------------------
//   This code was generated by template ffi.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/
// Code generated by spx codegen; DO NOT EDIT.

package ffi

//revive:disable

var (
	api GDExtensionInterface
)

type GDExtensionInterface struct {
	// All of the GDExtension interface functions.
	SpxAudioStopAll                             GDExtensionSpxAudioStopAll
	SpxAudioCreateAudio                         GDExtensionSpxAudioCreateAudio
	SpxAudioDestroyAudio                        GDExtensionSpxAudioDestroyAudio
	SpxAudioSetPitch                            GDExtensionSpxAudioSetPitch
	SpxAudioGetPitch                            GDExtensionSpxAudioGetPitch
	SpxAudioSetPan                              GDExtensionSpxAudioSetPan
	SpxAudioGetPan                              GDExtensionSpxAudioGetPan
	SpxAudioSetVolume                           GDExtensionSpxAudioSetVolume
	SpxAudioGetVolume                           GDExtensionSpxAudioGetVolume
	SpxAudioPlayWithAttenuation                 GDExtensionSpxAudioPlayWithAttenuation
	SpxAudioPlay                                GDExtensionSpxAudioPlay
	SpxAudioPause                               GDExtensionSpxAudioPause
	SpxAudioResume                              GDExtensionSpxAudioResume
	SpxAudioStop                                GDExtensionSpxAudioStop
	SpxAudioRestart                             GDExtensionSpxAudioRestart
	SpxAudioSetLoop                             GDExtensionSpxAudioSetLoop
	SpxAudioGetLoop                             GDExtensionSpxAudioGetLoop
	SpxAudioGetTimer                            GDExtensionSpxAudioGetTimer
	SpxAudioSetTimer                            GDExtensionSpxAudioSetTimer
	SpxAudioIsPlaying                           GDExtensionSpxAudioIsPlaying
	SpxCameraGetCameraPosition                  GDExtensionSpxCameraGetCameraPosition
	SpxCameraSetCameraPosition                  GDExtensionSpxCameraSetCameraPosition
	SpxCameraGetCameraZoom                      GDExtensionSpxCameraGetCameraZoom
	SpxCameraSetCameraZoom                      GDExtensionSpxCameraSetCameraZoom
	SpxCameraGetViewportRect                    GDExtensionSpxCameraGetViewportRect
	SpxCameraGetGlobalCameraRect                GDExtensionSpxCameraGetGlobalCameraRect
	SpxCameraGetStageLimitsRect                 GDExtensionSpxCameraGetStageLimitsRect
	SpxCameraSetCameraLimit                     GDExtensionSpxCameraSetCameraLimit
	SpxCameraSetCameraSmoothing                 GDExtensionSpxCameraSetCameraSmoothing
	SpxDebugDebugDrawCircle                     GDExtensionSpxDebugDebugDrawCircle
	SpxDebugDebugDrawRect                       GDExtensionSpxDebugDebugDrawRect
	SpxDebugDebugDrawLine                       GDExtensionSpxDebugDebugDrawLine
	SpxExtRequestExit                           GDExtensionSpxExtRequestExit
	SpxExtRequestReset                          GDExtensionSpxExtRequestReset
	SpxExtRequestRestart                        GDExtensionSpxExtRequestRestart
	SpxExtOnRuntimePanic                        GDExtensionSpxExtOnRuntimePanic
	SpxExtPause                                 GDExtensionSpxExtPause
	SpxExtResume                                GDExtensionSpxExtResume
	SpxExtIsPaused                              GDExtensionSpxExtIsPaused
	SpxExtNextFrame                             GDExtensionSpxExtNextFrame
	SpxExtSetLayerSorterMode                    GDExtensionSpxExtSetLayerSorterMode
	SpxInputGetGlobalMousePos                   GDExtensionSpxInputGetGlobalMousePos
	SpxInputGetKey                              GDExtensionSpxInputGetKey
	SpxInputGetMouseState                       GDExtensionSpxInputGetMouseState
	SpxInputGetKeyState                         GDExtensionSpxInputGetKeyState
	SpxInputGetAxis                             GDExtensionSpxInputGetAxis
	SpxInputIsActionPressed                     GDExtensionSpxInputIsActionPressed
	SpxInputIsActionJustPressed                 GDExtensionSpxInputIsActionJustPressed
	SpxInputIsActionJustReleased                GDExtensionSpxInputIsActionJustReleased
	SpxNavigationSetupPathFinderWithSize        GDExtensionSpxNavigationSetupPathFinderWithSize
	SpxNavigationSetupPathFinder                GDExtensionSpxNavigationSetupPathFinder
	SpxNavigationSetObstacle                    GDExtensionSpxNavigationSetObstacle
	SpxNavigationFindPath                       GDExtensionSpxNavigationFindPath
	SpxPenDestroyAllPens                        GDExtensionSpxPenDestroyAllPens
	SpxPenCreatePen                             GDExtensionSpxPenCreatePen
	SpxPenDestroyPen                            GDExtensionSpxPenDestroyPen
	SpxPenPenStamp                              GDExtensionSpxPenPenStamp
	SpxPenMovePenTo                             GDExtensionSpxPenMovePenTo
	SpxPenPenDown                               GDExtensionSpxPenPenDown
	SpxPenPenUp                                 GDExtensionSpxPenPenUp
	SpxPenSetPenColorTo                         GDExtensionSpxPenSetPenColorTo
	SpxPenChangePenBy                           GDExtensionSpxPenChangePenBy
	SpxPenSetPenTo                              GDExtensionSpxPenSetPenTo
	SpxPenChangePenSizeBy                       GDExtensionSpxPenChangePenSizeBy
	SpxPenSetPenSizeTo                          GDExtensionSpxPenSetPenSizeTo
	SpxPenSetPenStampTexture                    GDExtensionSpxPenSetPenStampTexture
	SpxPhysicsRaycast                           GDExtensionSpxPhysicsRaycast
	SpxPhysicsCheckCollision                    GDExtensionSpxPhysicsCheckCollision
	SpxPhysicsCheckTouchedCameraBoundaries      GDExtensionSpxPhysicsCheckTouchedCameraBoundaries
	SpxPhysicsCheckTouchedCameraBoundary        GDExtensionSpxPhysicsCheckTouchedCameraBoundary
	SpxPhysicsCheckNearestTouchedCameraBoundary GDExtensionSpxPhysicsCheckNearestTouchedCameraBoundary
	SpxPhysicsCheckTouchedStageBoundaries       GDExtensionSpxPhysicsCheckTouchedStageBoundaries
	SpxPhysicsCheckTouchedStageBoundary         GDExtensionSpxPhysicsCheckTouchedStageBoundary
	SpxPhysicsCheckNearestTouchedStageBoundary  GDExtensionSpxPhysicsCheckNearestTouchedStageBoundary
	SpxPhysicsSetCollisionSystemType            GDExtensionSpxPhysicsSetCollisionSystemType
	SpxPhysicsSetGlobalGravity                  GDExtensionSpxPhysicsSetGlobalGravity
	SpxPhysicsGetGlobalGravity                  GDExtensionSpxPhysicsGetGlobalGravity
	SpxPhysicsSetGlobalFriction                 GDExtensionSpxPhysicsSetGlobalFriction
	SpxPhysicsGetGlobalFriction                 GDExtensionSpxPhysicsGetGlobalFriction
	SpxPhysicsSetGlobalAirDrag                  GDExtensionSpxPhysicsSetGlobalAirDrag
	SpxPhysicsGetGlobalAirDrag                  GDExtensionSpxPhysicsGetGlobalAirDrag
	SpxPhysicsCheckCollisionRect                GDExtensionSpxPhysicsCheckCollisionRect
	SpxPhysicsCheckCollisionCircle              GDExtensionSpxPhysicsCheckCollisionCircle
	SpxPhysicsRaycastWithDetails                GDExtensionSpxPhysicsRaycastWithDetails
	SpxPlatformSetStretchMode                   GDExtensionSpxPlatformSetStretchMode
	SpxPlatformSetStretchAspect                 GDExtensionSpxPlatformSetStretchAspect
	SpxPlatformSetStretchContentScale           GDExtensionSpxPlatformSetStretchContentScale
	SpxPlatformSetWindowPosition                GDExtensionSpxPlatformSetWindowPosition
	SpxPlatformGetWindowPosition                GDExtensionSpxPlatformGetWindowPosition
	SpxPlatformSetWindowSize                    GDExtensionSpxPlatformSetWindowSize
	SpxPlatformGetWindowSize                    GDExtensionSpxPlatformGetWindowSize
	SpxPlatformSetWindowTitle                   GDExtensionSpxPlatformSetWindowTitle
	SpxPlatformGetWindowTitle                   GDExtensionSpxPlatformGetWindowTitle
	SpxPlatformSetWindowFullscreen              GDExtensionSpxPlatformSetWindowFullscreen
	SpxPlatformIsWindowFullscreen               GDExtensionSpxPlatformIsWindowFullscreen
	SpxPlatformSetDebugMode                     GDExtensionSpxPlatformSetDebugMode
	SpxPlatformIsDebugMode                      GDExtensionSpxPlatformIsDebugMode
	SpxPlatformGetTimeScale                     GDExtensionSpxPlatformGetTimeScale
	SpxPlatformSetTimeScale                     GDExtensionSpxPlatformSetTimeScale
	SpxPlatformGetMaxFps                        GDExtensionSpxPlatformGetMaxFps
	SpxPlatformSetMaxFps                        GDExtensionSpxPlatformSetMaxFps
	SpxPlatformGetPersistantDataDir             GDExtensionSpxPlatformGetPersistantDataDir
	SpxPlatformSetPersistantDataDir             GDExtensionSpxPlatformSetPersistantDataDir
	SpxPlatformIsInPersistantDataDir            GDExtensionSpxPlatformIsInPersistantDataDir
	SpxResCreateAnimation                       GDExtensionSpxResCreateAnimation
	SpxResSetLoadMode                           GDExtensionSpxResSetLoadMode
	SpxResGetLoadMode                           GDExtensionSpxResGetLoadMode
	SpxResGetBoundFromAlpha                     GDExtensionSpxResGetBoundFromAlpha
	SpxResGetImageSize                          GDExtensionSpxResGetImageSize
	SpxResReadAllText                           GDExtensionSpxResReadAllText
	SpxResHasFile                               GDExtensionSpxResHasFile
	SpxResReloadTexture                         GDExtensionSpxResReloadTexture
	SpxResFreeStr                               GDExtensionSpxResFreeStr
	SpxResSetDefaultFont                        GDExtensionSpxResSetDefaultFont
	SpxResRegisterSvgFontFace                   GDExtensionSpxResRegisterSvgFontFace
	SpxSceneChangeSceneToFile                   GDExtensionSpxSceneChangeSceneToFile
	SpxSceneDestroyAllSprites                   GDExtensionSpxSceneDestroyAllSprites
	SpxSceneReloadCurrentScene                  GDExtensionSpxSceneReloadCurrentScene
	SpxSceneUnloadCurrentScene                  GDExtensionSpxSceneUnloadCurrentScene
	SpxSceneClearPureSprites                    GDExtensionSpxSceneClearPureSprites
	SpxSceneCreatePureSprite                    GDExtensionSpxSceneCreatePureSprite
	SpxSceneDestroyPureSprite                   GDExtensionSpxSceneDestroyPureSprite
	SpxSceneCreateRenderSprite                  GDExtensionSpxSceneCreateRenderSprite
	SpxSceneCreateStaticSprite                  GDExtensionSpxSceneCreateStaticSprite
	SpxSpriteSetDontDestroyOnLoad               GDExtensionSpxSpriteSetDontDestroyOnLoad
	SpxSpriteSetProcess                         GDExtensionSpxSpriteSetProcess
	SpxSpriteSetPhysicProcess                   GDExtensionSpxSpriteSetPhysicProcess
	SpxSpriteSetTypeName                        GDExtensionSpxSpriteSetTypeName
	SpxSpriteSetPivot                           GDExtensionSpxSpriteSetPivot
	SpxSpriteGetPivot                           GDExtensionSpxSpriteGetPivot
	SpxSpriteSetChildPosition                   GDExtensionSpxSpriteSetChildPosition
	SpxSpriteGetChildPosition                   GDExtensionSpxSpriteGetChildPosition
	SpxSpriteSetChildRotation                   GDExtensionSpxSpriteSetChildRotation
	SpxSpriteGetChildRotation                   GDExtensionSpxSpriteGetChildRotation
	SpxSpriteSetChildScale                      GDExtensionSpxSpriteSetChildScale
	SpxSpriteGetChildScale                      GDExtensionSpxSpriteGetChildScale
	SpxSpriteCheckCollision                     GDExtensionSpxSpriteCheckCollision
	SpxSpriteCheckCollisionWithPoint            GDExtensionSpxSpriteCheckCollisionWithPoint
	SpxSpriteSetDebugCollisionVisible           GDExtensionSpxSpriteSetDebugCollisionVisible
	SpxSpriteIsDebugCollisionVisible            GDExtensionSpxSpriteIsDebugCollisionVisible
	SpxSpriteCreateBackdrop                     GDExtensionSpxSpriteCreateBackdrop
	SpxSpriteCreateSprite                       GDExtensionSpxSpriteCreateSprite
	SpxSpriteCreateBareSprite                   GDExtensionSpxSpriteCreateBareSprite
	SpxSpriteCloneSprite                        GDExtensionSpxSpriteCloneSprite
	SpxSpriteDestroySprite                      GDExtensionSpxSpriteDestroySprite
	SpxSpriteIsSpriteAlive                      GDExtensionSpxSpriteIsSpriteAlive
	SpxSpriteSetPosition                        GDExtensionSpxSpriteSetPosition
	SpxSpriteGetPosition                        GDExtensionSpxSpriteGetPosition
	SpxSpriteSetRotation                        GDExtensionSpxSpriteSetRotation
	SpxSpriteGetRotation                        GDExtensionSpxSpriteGetRotation
	SpxSpriteSetScale                           GDExtensionSpxSpriteSetScale
	SpxSpriteGetScale                           GDExtensionSpxSpriteGetScale
	SpxSpriteSetRenderScale                     GDExtensionSpxSpriteSetRenderScale
	SpxSpriteGetRenderScale                     GDExtensionSpxSpriteGetRenderScale
	SpxSpriteSetColor                           GDExtensionSpxSpriteSetColor
	SpxSpriteGetColor                           GDExtensionSpxSpriteGetColor
	SpxSpriteSetMaterialShader                  GDExtensionSpxSpriteSetMaterialShader
	SpxSpriteGetMaterialShader                  GDExtensionSpxSpriteGetMaterialShader
	SpxSpriteSetMaterialParams                  GDExtensionSpxSpriteSetMaterialParams
	SpxSpriteGetMaterialParams                  GDExtensionSpxSpriteGetMaterialParams
	SpxSpriteSetMaterialParamsVec               GDExtensionSpxSpriteSetMaterialParamsVec
	SpxSpriteSetMaterialParamsVec4              GDExtensionSpxSpriteSetMaterialParamsVec4
	SpxSpriteGetMaterialParamsVec4              GDExtensionSpxSpriteGetMaterialParamsVec4
	SpxSpriteSetMaterialParamsColor             GDExtensionSpxSpriteSetMaterialParamsColor
	SpxSpriteGetMaterialParamsColor             GDExtensionSpxSpriteGetMaterialParamsColor
	SpxSpriteSetTextureAtlas                    GDExtensionSpxSpriteSetTextureAtlas
	SpxSpriteSetTexture                         GDExtensionSpxSpriteSetTexture
	SpxSpriteSetTextureAtlasDirect              GDExtensionSpxSpriteSetTextureAtlasDirect
	SpxSpriteSetTextureDirect                   GDExtensionSpxSpriteSetTextureDirect
	SpxSpriteGetTexture                         GDExtensionSpxSpriteGetTexture
	SpxSpriteSetVisible                         GDExtensionSpxSpriteSetVisible
	SpxSpriteGetVisible                         GDExtensionSpxSpriteGetVisible
	SpxSpriteGetZIndex                          GDExtensionSpxSpriteGetZIndex
	SpxSpriteSetZIndex                          GDExtensionSpxSpriteSetZIndex
	SpxSpritePlayAnim                           GDExtensionSpxSpritePlayAnim
	SpxSpritePlayBackwardsAnim                  GDExtensionSpxSpritePlayBackwardsAnim
	SpxSpritePauseAnim                          GDExtensionSpxSpritePauseAnim
	SpxSpriteStopAnim                           GDExtensionSpxSpriteStopAnim
	SpxSpriteIsPlayingAnim                      GDExtensionSpxSpriteIsPlayingAnim
	SpxSpriteSetAnim                            GDExtensionSpxSpriteSetAnim
	SpxSpriteGetAnim                            GDExtensionSpxSpriteGetAnim
	SpxSpriteSetAnimFrame                       GDExtensionSpxSpriteSetAnimFrame
	SpxSpriteGetAnimFrame                       GDExtensionSpxSpriteGetAnimFrame
	SpxSpriteSetAnimSpeedScale                  GDExtensionSpxSpriteSetAnimSpeedScale
	SpxSpriteGetAnimSpeedScale                  GDExtensionSpxSpriteGetAnimSpeedScale
	SpxSpriteGetAnimPlayingSpeed                GDExtensionSpxSpriteGetAnimPlayingSpeed
	SpxSpriteSetAnimCentered                    GDExtensionSpxSpriteSetAnimCentered
	SpxSpriteIsAnimCentered                     GDExtensionSpxSpriteIsAnimCentered
	SpxSpriteSetAnimOffset                      GDExtensionSpxSpriteSetAnimOffset
	SpxSpriteGetAnimOffset                      GDExtensionSpxSpriteGetAnimOffset
	SpxSpriteSetAnimFlipH                       GDExtensionSpxSpriteSetAnimFlipH
	SpxSpriteIsAnimFlippedH                     GDExtensionSpxSpriteIsAnimFlippedH
	SpxSpriteSetAnimFlipV                       GDExtensionSpxSpriteSetAnimFlipV
	SpxSpriteIsAnimFlippedV                     GDExtensionSpxSpriteIsAnimFlippedV
	SpxSpriteGetCurrentAnimName                 GDExtensionSpxSpriteGetCurrentAnimName
	SpxSpriteSetVelocity                        GDExtensionSpxSpriteSetVelocity
	SpxSpriteGetVelocity                        GDExtensionSpxSpriteGetVelocity
	SpxSpriteIsOnFloor                          GDExtensionSpxSpriteIsOnFloor
	SpxSpriteIsOnFloorOnly                      GDExtensionSpxSpriteIsOnFloorOnly
	SpxSpriteIsOnWall                           GDExtensionSpxSpriteIsOnWall
	SpxSpriteIsOnWallOnly                       GDExtensionSpxSpriteIsOnWallOnly
	SpxSpriteIsOnCeiling                        GDExtensionSpxSpriteIsOnCeiling
	SpxSpriteIsOnCeilingOnly                    GDExtensionSpxSpriteIsOnCeilingOnly
	SpxSpriteGetLastMotion                      GDExtensionSpxSpriteGetLastMotion
	SpxSpriteGetPositionDelta                   GDExtensionSpxSpriteGetPositionDelta
	SpxSpriteGetFloorNormal                     GDExtensionSpxSpriteGetFloorNormal
	SpxSpriteGetWallNormal                      GDExtensionSpxSpriteGetWallNormal
	SpxSpriteGetRealVelocity                    GDExtensionSpxSpriteGetRealVelocity
	SpxSpriteMoveAndSlide                       GDExtensionSpxSpriteMoveAndSlide
	SpxSpriteSetGravity                         GDExtensionSpxSpriteSetGravity
	SpxSpriteGetGravity                         GDExtensionSpxSpriteGetGravity
	SpxSpriteSetMass                            GDExtensionSpxSpriteSetMass
	SpxSpriteGetMass                            GDExtensionSpxSpriteGetMass
	SpxSpriteAddForce                           GDExtensionSpxSpriteAddForce
	SpxSpriteAddImpulse                         GDExtensionSpxSpriteAddImpulse
	SpxSpriteSetPhysicsMode                     GDExtensionSpxSpriteSetPhysicsMode
	SpxSpriteGetPhysicsMode                     GDExtensionSpxSpriteGetPhysicsMode
	SpxSpriteSetUseGravity                      GDExtensionSpxSpriteSetUseGravity
	SpxSpriteIsUseGravity                       GDExtensionSpxSpriteIsUseGravity
	SpxSpriteSetGravityScale                    GDExtensionSpxSpriteSetGravityScale
	SpxSpriteGetGravityScale                    GDExtensionSpxSpriteGetGravityScale
	SpxSpriteSetDrag                            GDExtensionSpxSpriteSetDrag
	SpxSpriteGetDrag                            GDExtensionSpxSpriteGetDrag
	SpxSpriteSetFriction                        GDExtensionSpxSpriteSetFriction
	SpxSpriteGetFriction                        GDExtensionSpxSpriteGetFriction
	SpxSpriteSetCollisionLayer                  GDExtensionSpxSpriteSetCollisionLayer
	SpxSpriteGetCollisionLayer                  GDExtensionSpxSpriteGetCollisionLayer
	SpxSpriteSetCollisionMask                   GDExtensionSpxSpriteSetCollisionMask
	SpxSpriteGetCollisionMask                   GDExtensionSpxSpriteGetCollisionMask
	SpxSpriteSetTriggerLayer                    GDExtensionSpxSpriteSetTriggerLayer
	SpxSpriteGetTriggerLayer                    GDExtensionSpxSpriteGetTriggerLayer
	SpxSpriteSetTriggerMask                     GDExtensionSpxSpriteSetTriggerMask
	SpxSpriteGetTriggerMask                     GDExtensionSpxSpriteGetTriggerMask
	SpxSpriteSetColliderRect                    GDExtensionSpxSpriteSetColliderRect
	SpxSpriteSetColliderCircle                  GDExtensionSpxSpriteSetColliderCircle
	SpxSpriteSetColliderCapsule                 GDExtensionSpxSpriteSetColliderCapsule
	SpxSpriteSetColliderPolygon                 GDExtensionSpxSpriteSetColliderPolygon
	SpxSpriteSetCollisionEnabled                GDExtensionSpxSpriteSetCollisionEnabled
	SpxSpriteIsCollisionEnabled                 GDExtensionSpxSpriteIsCollisionEnabled
	SpxSpriteSetTriggerRect                     GDExtensionSpxSpriteSetTriggerRect
	SpxSpriteSetTriggerCircle                   GDExtensionSpxSpriteSetTriggerCircle
	SpxSpriteSetTriggerCapsule                  GDExtensionSpxSpriteSetTriggerCapsule
	SpxSpriteSetTriggerPolygon                  GDExtensionSpxSpriteSetTriggerPolygon
	SpxSpriteSetTriggerEnabled                  GDExtensionSpxSpriteSetTriggerEnabled
	SpxSpriteIsTriggerEnabled                   GDExtensionSpxSpriteIsTriggerEnabled
	SpxSpriteCheckCollisionByColor              GDExtensionSpxSpriteCheckCollisionByColor
	SpxSpriteCheckCollisionByColors             GDExtensionSpxSpriteCheckCollisionByColors
	SpxSpriteCheckCollisionByAlpha              GDExtensionSpxSpriteCheckCollisionByAlpha
	SpxSpriteCheckCollisionWithSprite           GDExtensionSpxSpriteCheckCollisionWithSprite
	SpxSpriteSetPixelCollisionSamplingStep      GDExtensionSpxSpriteSetPixelCollisionSamplingStep
	SpxSpriteGetPixelCollisionSamplingStep      GDExtensionSpxSpriteGetPixelCollisionSamplingStep
	SpxSpriteBatchUpdateTransforms              GDExtensionSpxSpriteBatchUpdateTransforms
	SpxSpriteBatchUpdateVisuals                 GDExtensionSpxSpriteBatchUpdateVisuals
	SpxSpriteBatchRetrievePositions             GDExtensionSpxSpriteBatchRetrievePositions
	SpxTilemapOpenDrawTilesWithSize             GDExtensionSpxTilemapOpenDrawTilesWithSize
	SpxTilemapOpenDrawTiles                     GDExtensionSpxTilemapOpenDrawTiles
	SpxTilemapSetLayerIndex                     GDExtensionSpxTilemapSetLayerIndex
	SpxTilemapSetTile                           GDExtensionSpxTilemapSetTile
	SpxTilemapSetTileWithCollisionInfo          GDExtensionSpxTilemapSetTileWithCollisionInfo
	SpxTilemapSetLayerOffset                    GDExtensionSpxTilemapSetLayerOffset
	SpxTilemapGetLayerOffset                    GDExtensionSpxTilemapGetLayerOffset
	SpxTilemapPlaceTiles                        GDExtensionSpxTilemapPlaceTiles
	SpxTilemapPlaceTilesWithLayer               GDExtensionSpxTilemapPlaceTilesWithLayer
	SpxTilemapPlaceTile                         GDExtensionSpxTilemapPlaceTile
	SpxTilemapPlaceTileWithLayer                GDExtensionSpxTilemapPlaceTileWithLayer
	SpxTilemapEraseTile                         GDExtensionSpxTilemapEraseTile
	SpxTilemapEraseTileWithLayer                GDExtensionSpxTilemapEraseTileWithLayer
	SpxTilemapGetTile                           GDExtensionSpxTilemapGetTile
	SpxTilemapGetTileWithLayer                  GDExtensionSpxTilemapGetTileWithLayer
	SpxTilemapCloseDrawTiles                    GDExtensionSpxTilemapCloseDrawTiles
	SpxTilemapExitTilemapEditorMode             GDExtensionSpxTilemapExitTilemapEditorMode
	SpxTilemapparserLoadTilemap                 GDExtensionSpxTilemapparserLoadTilemap
	SpxTilemapparserUnloadTilemap               GDExtensionSpxTilemapparserUnloadTilemap
	SpxTilemapparserDestroyAllTilemaps          GDExtensionSpxTilemapparserDestroyAllTilemaps
	SpxTilemapparserHasTilemap                  GDExtensionSpxTilemapparserHasTilemap
	SpxTilemapparserGetTilemapLayerCount        GDExtensionSpxTilemapparserGetTilemapLayerCount
	SpxUiBindNode                               GDExtensionSpxUiBindNode
	SpxUiCreateNode                             GDExtensionSpxUiCreateNode
	SpxUiCreateButton                           GDExtensionSpxUiCreateButton
	SpxUiCreateLabel                            GDExtensionSpxUiCreateLabel
	SpxUiCreateImage                            GDExtensionSpxUiCreateImage
	SpxUiCreateToggle                           GDExtensionSpxUiCreateToggle
	SpxUiCreateSlider                           GDExtensionSpxUiCreateSlider
	SpxUiCreateInput                            GDExtensionSpxUiCreateInput
	SpxUiDestroyNode                            GDExtensionSpxUiDestroyNode
	SpxUiGetType                                GDExtensionSpxUiGetType
	SpxUiSetText                                GDExtensionSpxUiSetText
	SpxUiGetText                                GDExtensionSpxUiGetText
	SpxUiSetTexture                             GDExtensionSpxUiSetTexture
	SpxUiGetTexture                             GDExtensionSpxUiGetTexture
	SpxUiSetColor                               GDExtensionSpxUiSetColor
	SpxUiGetColor                               GDExtensionSpxUiGetColor
	SpxUiSetFontSize                            GDExtensionSpxUiSetFontSize
	SpxUiGetFontSize                            GDExtensionSpxUiGetFontSize
	SpxUiSetVisible                             GDExtensionSpxUiSetVisible
	SpxUiGetVisible                             GDExtensionSpxUiGetVisible
	SpxUiSetInteractable                        GDExtensionSpxUiSetInteractable
	SpxUiGetInteractable                        GDExtensionSpxUiGetInteractable
	SpxUiSetRect                                GDExtensionSpxUiSetRect
	SpxUiGetRect                                GDExtensionSpxUiGetRect
	SpxUiGetLayoutDirection                     GDExtensionSpxUiGetLayoutDirection
	SpxUiSetLayoutDirection                     GDExtensionSpxUiSetLayoutDirection
	SpxUiGetLayoutMode                          GDExtensionSpxUiGetLayoutMode
	SpxUiSetLayoutMode                          GDExtensionSpxUiSetLayoutMode
	SpxUiGetAnchorsPreset                       GDExtensionSpxUiGetAnchorsPreset
	SpxUiSetAnchorsPreset                       GDExtensionSpxUiSetAnchorsPreset
	SpxUiGetScale                               GDExtensionSpxUiGetScale
	SpxUiSetScale                               GDExtensionSpxUiSetScale
	SpxUiGetPosition                            GDExtensionSpxUiGetPosition
	SpxUiSetPosition                            GDExtensionSpxUiSetPosition
	SpxUiGetSize                                GDExtensionSpxUiGetSize
	SpxUiSetSize                                GDExtensionSpxUiSetSize
	SpxUiGetGlobalPosition                      GDExtensionSpxUiGetGlobalPosition
	SpxUiSetGlobalPosition                      GDExtensionSpxUiSetGlobalPosition
	SpxUiGetRotation                            GDExtensionSpxUiGetRotation
	SpxUiSetRotation                            GDExtensionSpxUiSetRotation
	SpxUiGetFlip                                GDExtensionSpxUiGetFlip
	SpxUiSetFlip                                GDExtensionSpxUiSetFlip
}

func (x *GDExtensionInterface) resolveAPIFunctions() {
	x.SpxAudioStopAll = (GDExtensionSpxAudioStopAll)(resolveCFunc("spx_audio_stop_all"))
	x.SpxAudioCreateAudio = (GDExtensionSpxAudioCreateAudio)(resolveCFunc("spx_audio_create_audio"))
	x.SpxAudioDestroyAudio = (GDExtensionSpxAudioDestroyAudio)(resolveCFunc("spx_audio_destroy_audio"))
	x.SpxAudioSetPitch = (GDExtensionSpxAudioSetPitch)(resolveCFunc("spx_audio_set_pitch"))
	x.SpxAudioGetPitch = (GDExtensionSpxAudioGetPitch)(resolveCFunc("spx_audio_get_pitch"))
	x.SpxAudioSetPan = (GDExtensionSpxAudioSetPan)(resolveCFunc("spx_audio_set_pan"))
	x.SpxAudioGetPan = (GDExtensionSpxAudioGetPan)(resolveCFunc("spx_audio_get_pan"))
	x.SpxAudioSetVolume = (GDExtensionSpxAudioSetVolume)(resolveCFunc("spx_audio_set_volume"))
	x.SpxAudioGetVolume = (GDExtensionSpxAudioGetVolume)(resolveCFunc("spx_audio_get_volume"))
	x.SpxAudioPlayWithAttenuation = (GDExtensionSpxAudioPlayWithAttenuation)(resolveCFunc("spx_audio_play_with_attenuation"))
	x.SpxAudioPlay = (GDExtensionSpxAudioPlay)(resolveCFunc("spx_audio_play"))
	x.SpxAudioPause = (GDExtensionSpxAudioPause)(resolveCFunc("spx_audio_pause"))
	x.SpxAudioResume = (GDExtensionSpxAudioResume)(resolveCFunc("spx_audio_resume"))
	x.SpxAudioStop = (GDExtensionSpxAudioStop)(resolveCFunc("spx_audio_stop"))
	x.SpxAudioRestart = (GDExtensionSpxAudioRestart)(resolveCFunc("spx_audio_restart"))
	x.SpxAudioSetLoop = (GDExtensionSpxAudioSetLoop)(resolveCFunc("spx_audio_set_loop"))
	x.SpxAudioGetLoop = (GDExtensionSpxAudioGetLoop)(resolveCFunc("spx_audio_get_loop"))
	x.SpxAudioGetTimer = (GDExtensionSpxAudioGetTimer)(resolveCFunc("spx_audio_get_timer"))
	x.SpxAudioSetTimer = (GDExtensionSpxAudioSetTimer)(resolveCFunc("spx_audio_set_timer"))
	x.SpxAudioIsPlaying = (GDExtensionSpxAudioIsPlaying)(resolveCFunc("spx_audio_is_playing"))
	x.SpxCameraGetCameraPosition = (GDExtensionSpxCameraGetCameraPosition)(resolveCFunc("spx_camera_get_camera_position"))
	x.SpxCameraSetCameraPosition = (GDExtensionSpxCameraSetCameraPosition)(resolveCFunc("spx_camera_set_camera_position"))
	x.SpxCameraGetCameraZoom = (GDExtensionSpxCameraGetCameraZoom)(resolveCFunc("spx_camera_get_camera_zoom"))
	x.SpxCameraSetCameraZoom = (GDExtensionSpxCameraSetCameraZoom)(resolveCFunc("spx_camera_set_camera_zoom"))
	x.SpxCameraGetViewportRect = (GDExtensionSpxCameraGetViewportRect)(resolveCFunc("spx_camera_get_viewport_rect"))
	x.SpxCameraGetGlobalCameraRect = (GDExtensionSpxCameraGetGlobalCameraRect)(resolveCFunc("spx_camera_get_global_camera_rect"))
	x.SpxCameraGetStageLimitsRect = (GDExtensionSpxCameraGetStageLimitsRect)(resolveCFunc("spx_camera_get_stage_limits_rect"))
	x.SpxCameraSetCameraLimit = (GDExtensionSpxCameraSetCameraLimit)(resolveCFunc("spx_camera_set_camera_limit"))
	x.SpxCameraSetCameraSmoothing = (GDExtensionSpxCameraSetCameraSmoothing)(resolveCFunc("spx_camera_set_camera_smoothing"))
	x.SpxDebugDebugDrawCircle = (GDExtensionSpxDebugDebugDrawCircle)(resolveCFunc("spx_debug_debug_draw_circle"))
	x.SpxDebugDebugDrawRect = (GDExtensionSpxDebugDebugDrawRect)(resolveCFunc("spx_debug_debug_draw_rect"))
	x.SpxDebugDebugDrawLine = (GDExtensionSpxDebugDebugDrawLine)(resolveCFunc("spx_debug_debug_draw_line"))
	x.SpxExtRequestExit = (GDExtensionSpxExtRequestExit)(resolveCFunc("spx_ext_request_exit"))
	x.SpxExtRequestReset = (GDExtensionSpxExtRequestReset)(resolveCFunc("spx_ext_request_reset"))
	x.SpxExtRequestRestart = (GDExtensionSpxExtRequestRestart)(resolveCFunc("spx_ext_request_restart"))
	x.SpxExtOnRuntimePanic = (GDExtensionSpxExtOnRuntimePanic)(resolveCFunc("spx_ext_on_runtime_panic"))
	x.SpxExtPause = (GDExtensionSpxExtPause)(resolveCFunc("spx_ext_pause"))
	x.SpxExtResume = (GDExtensionSpxExtResume)(resolveCFunc("spx_ext_resume"))
	x.SpxExtIsPaused = (GDExtensionSpxExtIsPaused)(resolveCFunc("spx_ext_is_paused"))
	x.SpxExtNextFrame = (GDExtensionSpxExtNextFrame)(resolveCFunc("spx_ext_next_frame"))
	x.SpxExtSetLayerSorterMode = (GDExtensionSpxExtSetLayerSorterMode)(resolveCFunc("spx_ext_set_layer_sorter_mode"))
	x.SpxInputGetGlobalMousePos = (GDExtensionSpxInputGetGlobalMousePos)(resolveCFunc("spx_input_get_global_mouse_pos"))
	x.SpxInputGetKey = (GDExtensionSpxInputGetKey)(resolveCFunc("spx_input_get_key"))
	x.SpxInputGetMouseState = (GDExtensionSpxInputGetMouseState)(resolveCFunc("spx_input_get_mouse_state"))
	x.SpxInputGetKeyState = (GDExtensionSpxInputGetKeyState)(resolveCFunc("spx_input_get_key_state"))
	x.SpxInputGetAxis = (GDExtensionSpxInputGetAxis)(resolveCFunc("spx_input_get_axis"))
	x.SpxInputIsActionPressed = (GDExtensionSpxInputIsActionPressed)(resolveCFunc("spx_input_is_action_pressed"))
	x.SpxInputIsActionJustPressed = (GDExtensionSpxInputIsActionJustPressed)(resolveCFunc("spx_input_is_action_just_pressed"))
	x.SpxInputIsActionJustReleased = (GDExtensionSpxInputIsActionJustReleased)(resolveCFunc("spx_input_is_action_just_released"))
	x.SpxNavigationSetupPathFinderWithSize = (GDExtensionSpxNavigationSetupPathFinderWithSize)(resolveCFunc("spx_navigation_setup_path_finder_with_size"))
	x.SpxNavigationSetupPathFinder = (GDExtensionSpxNavigationSetupPathFinder)(resolveCFunc("spx_navigation_setup_path_finder"))
	x.SpxNavigationSetObstacle = (GDExtensionSpxNavigationSetObstacle)(resolveCFunc("spx_navigation_set_obstacle"))
	x.SpxNavigationFindPath = (GDExtensionSpxNavigationFindPath)(resolveCFunc("spx_navigation_find_path"))
	x.SpxPenDestroyAllPens = (GDExtensionSpxPenDestroyAllPens)(resolveCFunc("spx_pen_destroy_all_pens"))
	x.SpxPenCreatePen = (GDExtensionSpxPenCreatePen)(resolveCFunc("spx_pen_create_pen"))
	x.SpxPenDestroyPen = (GDExtensionSpxPenDestroyPen)(resolveCFunc("spx_pen_destroy_pen"))
	x.SpxPenPenStamp = (GDExtensionSpxPenPenStamp)(resolveCFunc("spx_pen_pen_stamp"))
	x.SpxPenMovePenTo = (GDExtensionSpxPenMovePenTo)(resolveCFunc("spx_pen_move_pen_to"))
	x.SpxPenPenDown = (GDExtensionSpxPenPenDown)(resolveCFunc("spx_pen_pen_down"))
	x.SpxPenPenUp = (GDExtensionSpxPenPenUp)(resolveCFunc("spx_pen_pen_up"))
	x.SpxPenSetPenColorTo = (GDExtensionSpxPenSetPenColorTo)(resolveCFunc("spx_pen_set_pen_color_to"))
	x.SpxPenChangePenBy = (GDExtensionSpxPenChangePenBy)(resolveCFunc("spx_pen_change_pen_by"))
	x.SpxPenSetPenTo = (GDExtensionSpxPenSetPenTo)(resolveCFunc("spx_pen_set_pen_to"))
	x.SpxPenChangePenSizeBy = (GDExtensionSpxPenChangePenSizeBy)(resolveCFunc("spx_pen_change_pen_size_by"))
	x.SpxPenSetPenSizeTo = (GDExtensionSpxPenSetPenSizeTo)(resolveCFunc("spx_pen_set_pen_size_to"))
	x.SpxPenSetPenStampTexture = (GDExtensionSpxPenSetPenStampTexture)(resolveCFunc("spx_pen_set_pen_stamp_texture"))
	x.SpxPhysicsRaycast = (GDExtensionSpxPhysicsRaycast)(resolveCFunc("spx_physics_raycast"))
	x.SpxPhysicsCheckCollision = (GDExtensionSpxPhysicsCheckCollision)(resolveCFunc("spx_physics_check_collision"))
	x.SpxPhysicsCheckTouchedCameraBoundaries = (GDExtensionSpxPhysicsCheckTouchedCameraBoundaries)(resolveCFunc("spx_physics_check_touched_camera_boundaries"))
	x.SpxPhysicsCheckTouchedCameraBoundary = (GDExtensionSpxPhysicsCheckTouchedCameraBoundary)(resolveCFunc("spx_physics_check_touched_camera_boundary"))
	x.SpxPhysicsCheckNearestTouchedCameraBoundary = (GDExtensionSpxPhysicsCheckNearestTouchedCameraBoundary)(resolveCFunc("spx_physics_check_nearest_touched_camera_boundary"))
	x.SpxPhysicsCheckTouchedStageBoundaries = (GDExtensionSpxPhysicsCheckTouchedStageBoundaries)(resolveCFunc("spx_physics_check_touched_stage_boundaries"))
	x.SpxPhysicsCheckTouchedStageBoundary = (GDExtensionSpxPhysicsCheckTouchedStageBoundary)(resolveCFunc("spx_physics_check_touched_stage_boundary"))
	x.SpxPhysicsCheckNearestTouchedStageBoundary = (GDExtensionSpxPhysicsCheckNearestTouchedStageBoundary)(resolveCFunc("spx_physics_check_nearest_touched_stage_boundary"))
	x.SpxPhysicsSetCollisionSystemType = (GDExtensionSpxPhysicsSetCollisionSystemType)(resolveCFunc("spx_physics_set_collision_system_type"))
	x.SpxPhysicsSetGlobalGravity = (GDExtensionSpxPhysicsSetGlobalGravity)(resolveCFunc("spx_physics_set_global_gravity"))
	x.SpxPhysicsGetGlobalGravity = (GDExtensionSpxPhysicsGetGlobalGravity)(resolveCFunc("spx_physics_get_global_gravity"))
	x.SpxPhysicsSetGlobalFriction = (GDExtensionSpxPhysicsSetGlobalFriction)(resolveCFunc("spx_physics_set_global_friction"))
	x.SpxPhysicsGetGlobalFriction = (GDExtensionSpxPhysicsGetGlobalFriction)(resolveCFunc("spx_physics_get_global_friction"))
	x.SpxPhysicsSetGlobalAirDrag = (GDExtensionSpxPhysicsSetGlobalAirDrag)(resolveCFunc("spx_physics_set_global_air_drag"))
	x.SpxPhysicsGetGlobalAirDrag = (GDExtensionSpxPhysicsGetGlobalAirDrag)(resolveCFunc("spx_physics_get_global_air_drag"))
	x.SpxPhysicsCheckCollisionRect = (GDExtensionSpxPhysicsCheckCollisionRect)(resolveCFunc("spx_physics_check_collision_rect"))
	x.SpxPhysicsCheckCollisionCircle = (GDExtensionSpxPhysicsCheckCollisionCircle)(resolveCFunc("spx_physics_check_collision_circle"))
	x.SpxPhysicsRaycastWithDetails = (GDExtensionSpxPhysicsRaycastWithDetails)(resolveCFunc("spx_physics_raycast_with_details"))
	x.SpxPlatformSetStretchMode = (GDExtensionSpxPlatformSetStretchMode)(resolveCFunc("spx_platform_set_stretch_mode"))
	x.SpxPlatformSetStretchAspect = (GDExtensionSpxPlatformSetStretchAspect)(resolveCFunc("spx_platform_set_stretch_aspect"))
	x.SpxPlatformSetStretchContentScale = (GDExtensionSpxPlatformSetStretchContentScale)(resolveCFunc("spx_platform_set_stretch_content_scale"))
	x.SpxPlatformSetWindowPosition = (GDExtensionSpxPlatformSetWindowPosition)(resolveCFunc("spx_platform_set_window_position"))
	x.SpxPlatformGetWindowPosition = (GDExtensionSpxPlatformGetWindowPosition)(resolveCFunc("spx_platform_get_window_position"))
	x.SpxPlatformSetWindowSize = (GDExtensionSpxPlatformSetWindowSize)(resolveCFunc("spx_platform_set_window_size"))
	x.SpxPlatformGetWindowSize = (GDExtensionSpxPlatformGetWindowSize)(resolveCFunc("spx_platform_get_window_size"))
	x.SpxPlatformSetWindowTitle = (GDExtensionSpxPlatformSetWindowTitle)(resolveCFunc("spx_platform_set_window_title"))
	x.SpxPlatformGetWindowTitle = (GDExtensionSpxPlatformGetWindowTitle)(resolveCFunc("spx_platform_get_window_title"))
	x.SpxPlatformSetWindowFullscreen = (GDExtensionSpxPlatformSetWindowFullscreen)(resolveCFunc("spx_platform_set_window_fullscreen"))
	x.SpxPlatformIsWindowFullscreen = (GDExtensionSpxPlatformIsWindowFullscreen)(resolveCFunc("spx_platform_is_window_fullscreen"))
	x.SpxPlatformSetDebugMode = (GDExtensionSpxPlatformSetDebugMode)(resolveCFunc("spx_platform_set_debug_mode"))
	x.SpxPlatformIsDebugMode = (GDExtensionSpxPlatformIsDebugMode)(resolveCFunc("spx_platform_is_debug_mode"))
	x.SpxPlatformGetTimeScale = (GDExtensionSpxPlatformGetTimeScale)(resolveCFunc("spx_platform_get_time_scale"))
	x.SpxPlatformSetTimeScale = (GDExtensionSpxPlatformSetTimeScale)(resolveCFunc("spx_platform_set_time_scale"))
	x.SpxPlatformGetMaxFps = (GDExtensionSpxPlatformGetMaxFps)(resolveCFunc("spx_platform_get_max_fps"))
	x.SpxPlatformSetMaxFps = (GDExtensionSpxPlatformSetMaxFps)(resolveCFunc("spx_platform_set_max_fps"))
	x.SpxPlatformGetPersistantDataDir = (GDExtensionSpxPlatformGetPersistantDataDir)(resolveCFunc("spx_platform_get_persistant_data_dir"))
	x.SpxPlatformSetPersistantDataDir = (GDExtensionSpxPlatformSetPersistantDataDir)(resolveCFunc("spx_platform_set_persistant_data_dir"))
	x.SpxPlatformIsInPersistantDataDir = (GDExtensionSpxPlatformIsInPersistantDataDir)(resolveCFunc("spx_platform_is_in_persistant_data_dir"))
	x.SpxResCreateAnimation = (GDExtensionSpxResCreateAnimation)(resolveCFunc("spx_res_create_animation"))
	x.SpxResSetLoadMode = (GDExtensionSpxResSetLoadMode)(resolveCFunc("spx_res_set_load_mode"))
	x.SpxResGetLoadMode = (GDExtensionSpxResGetLoadMode)(resolveCFunc("spx_res_get_load_mode"))
	x.SpxResGetBoundFromAlpha = (GDExtensionSpxResGetBoundFromAlpha)(resolveCFunc("spx_res_get_bound_from_alpha"))
	x.SpxResGetImageSize = (GDExtensionSpxResGetImageSize)(resolveCFunc("spx_res_get_image_size"))
	x.SpxResReadAllText = (GDExtensionSpxResReadAllText)(resolveCFunc("spx_res_read_all_text"))
	x.SpxResHasFile = (GDExtensionSpxResHasFile)(resolveCFunc("spx_res_has_file"))
	x.SpxResReloadTexture = (GDExtensionSpxResReloadTexture)(resolveCFunc("spx_res_reload_texture"))
	x.SpxResFreeStr = (GDExtensionSpxResFreeStr)(resolveCFunc("spx_res_free_str"))
	x.SpxResSetDefaultFont = (GDExtensionSpxResSetDefaultFont)(resolveCFunc("spx_res_set_default_font"))
	x.SpxResRegisterSvgFontFace = (GDExtensionSpxResRegisterSvgFontFace)(resolveCFunc("spx_res_register_svg_font_face"))
	x.SpxSceneChangeSceneToFile = (GDExtensionSpxSceneChangeSceneToFile)(resolveCFunc("spx_scene_change_scene_to_file"))
	x.SpxSceneDestroyAllSprites = (GDExtensionSpxSceneDestroyAllSprites)(resolveCFunc("spx_scene_destroy_all_sprites"))
	x.SpxSceneReloadCurrentScene = (GDExtensionSpxSceneReloadCurrentScene)(resolveCFunc("spx_scene_reload_current_scene"))
	x.SpxSceneUnloadCurrentScene = (GDExtensionSpxSceneUnloadCurrentScene)(resolveCFunc("spx_scene_unload_current_scene"))
	x.SpxSceneClearPureSprites = (GDExtensionSpxSceneClearPureSprites)(resolveCFunc("spx_scene_clear_pure_sprites"))
	x.SpxSceneCreatePureSprite = (GDExtensionSpxSceneCreatePureSprite)(resolveCFunc("spx_scene_create_pure_sprite"))
	x.SpxSceneDestroyPureSprite = (GDExtensionSpxSceneDestroyPureSprite)(resolveCFunc("spx_scene_destroy_pure_sprite"))
	x.SpxSceneCreateRenderSprite = (GDExtensionSpxSceneCreateRenderSprite)(resolveCFunc("spx_scene_create_render_sprite"))
	x.SpxSceneCreateStaticSprite = (GDExtensionSpxSceneCreateStaticSprite)(resolveCFunc("spx_scene_create_static_sprite"))
	x.SpxSpriteSetDontDestroyOnLoad = (GDExtensionSpxSpriteSetDontDestroyOnLoad)(resolveCFunc("spx_sprite_set_dont_destroy_on_load"))
	x.SpxSpriteSetProcess = (GDExtensionSpxSpriteSetProcess)(resolveCFunc("spx_sprite_set_process"))
	x.SpxSpriteSetPhysicProcess = (GDExtensionSpxSpriteSetPhysicProcess)(resolveCFunc("spx_sprite_set_physic_process"))
	x.SpxSpriteSetTypeName = (GDExtensionSpxSpriteSetTypeName)(resolveCFunc("spx_sprite_set_type_name"))
	x.SpxSpriteSetPivot = (GDExtensionSpxSpriteSetPivot)(resolveCFunc("spx_sprite_set_pivot"))
	x.SpxSpriteGetPivot = (GDExtensionSpxSpriteGetPivot)(resolveCFunc("spx_sprite_get_pivot"))
	x.SpxSpriteSetChildPosition = (GDExtensionSpxSpriteSetChildPosition)(resolveCFunc("spx_sprite_set_child_position"))
	x.SpxSpriteGetChildPosition = (GDExtensionSpxSpriteGetChildPosition)(resolveCFunc("spx_sprite_get_child_position"))
	x.SpxSpriteSetChildRotation = (GDExtensionSpxSpriteSetChildRotation)(resolveCFunc("spx_sprite_set_child_rotation"))
	x.SpxSpriteGetChildRotation = (GDExtensionSpxSpriteGetChildRotation)(resolveCFunc("spx_sprite_get_child_rotation"))
	x.SpxSpriteSetChildScale = (GDExtensionSpxSpriteSetChildScale)(resolveCFunc("spx_sprite_set_child_scale"))
	x.SpxSpriteGetChildScale = (GDExtensionSpxSpriteGetChildScale)(resolveCFunc("spx_sprite_get_child_scale"))
	x.SpxSpriteCheckCollision = (GDExtensionSpxSpriteCheckCollision)(resolveCFunc("spx_sprite_check_collision"))
	x.SpxSpriteCheckCollisionWithPoint = (GDExtensionSpxSpriteCheckCollisionWithPoint)(resolveCFunc("spx_sprite_check_collision_with_point"))
	x.SpxSpriteSetDebugCollisionVisible = (GDExtensionSpxSpriteSetDebugCollisionVisible)(resolveCFunc("spx_sprite_set_debug_collision_visible"))
	x.SpxSpriteIsDebugCollisionVisible = (GDExtensionSpxSpriteIsDebugCollisionVisible)(resolveCFunc("spx_sprite_is_debug_collision_visible"))
	x.SpxSpriteCreateBackdrop = (GDExtensionSpxSpriteCreateBackdrop)(resolveCFunc("spx_sprite_create_backdrop"))
	x.SpxSpriteCreateSprite = (GDExtensionSpxSpriteCreateSprite)(resolveCFunc("spx_sprite_create_sprite"))
	x.SpxSpriteCreateBareSprite = (GDExtensionSpxSpriteCreateBareSprite)(resolveCFunc("spx_sprite_create_bare_sprite"))
	x.SpxSpriteCloneSprite = (GDExtensionSpxSpriteCloneSprite)(resolveCFunc("spx_sprite_clone_sprite"))
	x.SpxSpriteDestroySprite = (GDExtensionSpxSpriteDestroySprite)(resolveCFunc("spx_sprite_destroy_sprite"))
	x.SpxSpriteIsSpriteAlive = (GDExtensionSpxSpriteIsSpriteAlive)(resolveCFunc("spx_sprite_is_sprite_alive"))
	x.SpxSpriteSetPosition = (GDExtensionSpxSpriteSetPosition)(resolveCFunc("spx_sprite_set_position"))
	x.SpxSpriteGetPosition = (GDExtensionSpxSpriteGetPosition)(resolveCFunc("spx_sprite_get_position"))
	x.SpxSpriteSetRotation = (GDExtensionSpxSpriteSetRotation)(resolveCFunc("spx_sprite_set_rotation"))
	x.SpxSpriteGetRotation = (GDExtensionSpxSpriteGetRotation)(resolveCFunc("spx_sprite_get_rotation"))
	x.SpxSpriteSetScale = (GDExtensionSpxSpriteSetScale)(resolveCFunc("spx_sprite_set_scale"))
	x.SpxSpriteGetScale = (GDExtensionSpxSpriteGetScale)(resolveCFunc("spx_sprite_get_scale"))
	x.SpxSpriteSetRenderScale = (GDExtensionSpxSpriteSetRenderScale)(resolveCFunc("spx_sprite_set_render_scale"))
	x.SpxSpriteGetRenderScale = (GDExtensionSpxSpriteGetRenderScale)(resolveCFunc("spx_sprite_get_render_scale"))
	x.SpxSpriteSetColor = (GDExtensionSpxSpriteSetColor)(resolveCFunc("spx_sprite_set_color"))
	x.SpxSpriteGetColor = (GDExtensionSpxSpriteGetColor)(resolveCFunc("spx_sprite_get_color"))
	x.SpxSpriteSetMaterialShader = (GDExtensionSpxSpriteSetMaterialShader)(resolveCFunc("spx_sprite_set_material_shader"))
	x.SpxSpriteGetMaterialShader = (GDExtensionSpxSpriteGetMaterialShader)(resolveCFunc("spx_sprite_get_material_shader"))
	x.SpxSpriteSetMaterialParams = (GDExtensionSpxSpriteSetMaterialParams)(resolveCFunc("spx_sprite_set_material_params"))
	x.SpxSpriteGetMaterialParams = (GDExtensionSpxSpriteGetMaterialParams)(resolveCFunc("spx_sprite_get_material_params"))
	x.SpxSpriteSetMaterialParamsVec = (GDExtensionSpxSpriteSetMaterialParamsVec)(resolveCFunc("spx_sprite_set_material_params_vec"))
	x.SpxSpriteSetMaterialParamsVec4 = (GDExtensionSpxSpriteSetMaterialParamsVec4)(resolveCFunc("spx_sprite_set_material_params_vec4"))
	x.SpxSpriteGetMaterialParamsVec4 = (GDExtensionSpxSpriteGetMaterialParamsVec4)(resolveCFunc("spx_sprite_get_material_params_vec4"))
	x.SpxSpriteSetMaterialParamsColor = (GDExtensionSpxSpriteSetMaterialParamsColor)(resolveCFunc("spx_sprite_set_material_params_color"))
	x.SpxSpriteGetMaterialParamsColor = (GDExtensionSpxSpriteGetMaterialParamsColor)(resolveCFunc("spx_sprite_get_material_params_color"))
	x.SpxSpriteSetTextureAtlas = (GDExtensionSpxSpriteSetTextureAtlas)(resolveCFunc("spx_sprite_set_texture_atlas"))
	x.SpxSpriteSetTexture = (GDExtensionSpxSpriteSetTexture)(resolveCFunc("spx_sprite_set_texture"))
	x.SpxSpriteSetTextureAtlasDirect = (GDExtensionSpxSpriteSetTextureAtlasDirect)(resolveCFunc("spx_sprite_set_texture_atlas_direct"))
	x.SpxSpriteSetTextureDirect = (GDExtensionSpxSpriteSetTextureDirect)(resolveCFunc("spx_sprite_set_texture_direct"))
	x.SpxSpriteGetTexture = (GDExtensionSpxSpriteGetTexture)(resolveCFunc("spx_sprite_get_texture"))
	x.SpxSpriteSetVisible = (GDExtensionSpxSpriteSetVisible)(resolveCFunc("spx_sprite_set_visible"))
	x.SpxSpriteGetVisible = (GDExtensionSpxSpriteGetVisible)(resolveCFunc("spx_sprite_get_visible"))
	x.SpxSpriteGetZIndex = (GDExtensionSpxSpriteGetZIndex)(resolveCFunc("spx_sprite_get_z_index"))
	x.SpxSpriteSetZIndex = (GDExtensionSpxSpriteSetZIndex)(resolveCFunc("spx_sprite_set_z_index"))
	x.SpxSpritePlayAnim = (GDExtensionSpxSpritePlayAnim)(resolveCFunc("spx_sprite_play_anim"))
	x.SpxSpritePlayBackwardsAnim = (GDExtensionSpxSpritePlayBackwardsAnim)(resolveCFunc("spx_sprite_play_backwards_anim"))
	x.SpxSpritePauseAnim = (GDExtensionSpxSpritePauseAnim)(resolveCFunc("spx_sprite_pause_anim"))
	x.SpxSpriteStopAnim = (GDExtensionSpxSpriteStopAnim)(resolveCFunc("spx_sprite_stop_anim"))
	x.SpxSpriteIsPlayingAnim = (GDExtensionSpxSpriteIsPlayingAnim)(resolveCFunc("spx_sprite_is_playing_anim"))
	x.SpxSpriteSetAnim = (GDExtensionSpxSpriteSetAnim)(resolveCFunc("spx_sprite_set_anim"))
	x.SpxSpriteGetAnim = (GDExtensionSpxSpriteGetAnim)(resolveCFunc("spx_sprite_get_anim"))
	x.SpxSpriteSetAnimFrame = (GDExtensionSpxSpriteSetAnimFrame)(resolveCFunc("spx_sprite_set_anim_frame"))
	x.SpxSpriteGetAnimFrame = (GDExtensionSpxSpriteGetAnimFrame)(resolveCFunc("spx_sprite_get_anim_frame"))
	x.SpxSpriteSetAnimSpeedScale = (GDExtensionSpxSpriteSetAnimSpeedScale)(resolveCFunc("spx_sprite_set_anim_speed_scale"))
	x.SpxSpriteGetAnimSpeedScale = (GDExtensionSpxSpriteGetAnimSpeedScale)(resolveCFunc("spx_sprite_get_anim_speed_scale"))
	x.SpxSpriteGetAnimPlayingSpeed = (GDExtensionSpxSpriteGetAnimPlayingSpeed)(resolveCFunc("spx_sprite_get_anim_playing_speed"))
	x.SpxSpriteSetAnimCentered = (GDExtensionSpxSpriteSetAnimCentered)(resolveCFunc("spx_sprite_set_anim_centered"))
	x.SpxSpriteIsAnimCentered = (GDExtensionSpxSpriteIsAnimCentered)(resolveCFunc("spx_sprite_is_anim_centered"))
	x.SpxSpriteSetAnimOffset = (GDExtensionSpxSpriteSetAnimOffset)(resolveCFunc("spx_sprite_set_anim_offset"))
	x.SpxSpriteGetAnimOffset = (GDExtensionSpxSpriteGetAnimOffset)(resolveCFunc("spx_sprite_get_anim_offset"))
	x.SpxSpriteSetAnimFlipH = (GDExtensionSpxSpriteSetAnimFlipH)(resolveCFunc("spx_sprite_set_anim_flip_h"))
	x.SpxSpriteIsAnimFlippedH = (GDExtensionSpxSpriteIsAnimFlippedH)(resolveCFunc("spx_sprite_is_anim_flipped_h"))
	x.SpxSpriteSetAnimFlipV = (GDExtensionSpxSpriteSetAnimFlipV)(resolveCFunc("spx_sprite_set_anim_flip_v"))
	x.SpxSpriteIsAnimFlippedV = (GDExtensionSpxSpriteIsAnimFlippedV)(resolveCFunc("spx_sprite_is_anim_flipped_v"))
	x.SpxSpriteGetCurrentAnimName = (GDExtensionSpxSpriteGetCurrentAnimName)(resolveCFunc("spx_sprite_get_current_anim_name"))
	x.SpxSpriteSetVelocity = (GDExtensionSpxSpriteSetVelocity)(resolveCFunc("spx_sprite_set_velocity"))
	x.SpxSpriteGetVelocity = (GDExtensionSpxSpriteGetVelocity)(resolveCFunc("spx_sprite_get_velocity"))
	x.SpxSpriteIsOnFloor = (GDExtensionSpxSpriteIsOnFloor)(resolveCFunc("spx_sprite_is_on_floor"))
	x.SpxSpriteIsOnFloorOnly = (GDExtensionSpxSpriteIsOnFloorOnly)(resolveCFunc("spx_sprite_is_on_floor_only"))
	x.SpxSpriteIsOnWall = (GDExtensionSpxSpriteIsOnWall)(resolveCFunc("spx_sprite_is_on_wall"))
	x.SpxSpriteIsOnWallOnly = (GDExtensionSpxSpriteIsOnWallOnly)(resolveCFunc("spx_sprite_is_on_wall_only"))
	x.SpxSpriteIsOnCeiling = (GDExtensionSpxSpriteIsOnCeiling)(resolveCFunc("spx_sprite_is_on_ceiling"))
	x.SpxSpriteIsOnCeilingOnly = (GDExtensionSpxSpriteIsOnCeilingOnly)(resolveCFunc("spx_sprite_is_on_ceiling_only"))
	x.SpxSpriteGetLastMotion = (GDExtensionSpxSpriteGetLastMotion)(resolveCFunc("spx_sprite_get_last_motion"))
	x.SpxSpriteGetPositionDelta = (GDExtensionSpxSpriteGetPositionDelta)(resolveCFunc("spx_sprite_get_position_delta"))
	x.SpxSpriteGetFloorNormal = (GDExtensionSpxSpriteGetFloorNormal)(resolveCFunc("spx_sprite_get_floor_normal"))
	x.SpxSpriteGetWallNormal = (GDExtensionSpxSpriteGetWallNormal)(resolveCFunc("spx_sprite_get_wall_normal"))
	x.SpxSpriteGetRealVelocity = (GDExtensionSpxSpriteGetRealVelocity)(resolveCFunc("spx_sprite_get_real_velocity"))
	x.SpxSpriteMoveAndSlide = (GDExtensionSpxSpriteMoveAndSlide)(resolveCFunc("spx_sprite_move_and_slide"))
	x.SpxSpriteSetGravity = (GDExtensionSpxSpriteSetGravity)(resolveCFunc("spx_sprite_set_gravity"))
	x.SpxSpriteGetGravity = (GDExtensionSpxSpriteGetGravity)(resolveCFunc("spx_sprite_get_gravity"))
	x.SpxSpriteSetMass = (GDExtensionSpxSpriteSetMass)(resolveCFunc("spx_sprite_set_mass"))
	x.SpxSpriteGetMass = (GDExtensionSpxSpriteGetMass)(resolveCFunc("spx_sprite_get_mass"))
	x.SpxSpriteAddForce = (GDExtensionSpxSpriteAddForce)(resolveCFunc("spx_sprite_add_force"))
	x.SpxSpriteAddImpulse = (GDExtensionSpxSpriteAddImpulse)(resolveCFunc("spx_sprite_add_impulse"))
	x.SpxSpriteSetPhysicsMode = (GDExtensionSpxSpriteSetPhysicsMode)(resolveCFunc("spx_sprite_set_physics_mode"))
	x.SpxSpriteGetPhysicsMode = (GDExtensionSpxSpriteGetPhysicsMode)(resolveCFunc("spx_sprite_get_physics_mode"))
	x.SpxSpriteSetUseGravity = (GDExtensionSpxSpriteSetUseGravity)(resolveCFunc("spx_sprite_set_use_gravity"))
	x.SpxSpriteIsUseGravity = (GDExtensionSpxSpriteIsUseGravity)(resolveCFunc("spx_sprite_is_use_gravity"))
	x.SpxSpriteSetGravityScale = (GDExtensionSpxSpriteSetGravityScale)(resolveCFunc("spx_sprite_set_gravity_scale"))
	x.SpxSpriteGetGravityScale = (GDExtensionSpxSpriteGetGravityScale)(resolveCFunc("spx_sprite_get_gravity_scale"))
	x.SpxSpriteSetDrag = (GDExtensionSpxSpriteSetDrag)(resolveCFunc("spx_sprite_set_drag"))
	x.SpxSpriteGetDrag = (GDExtensionSpxSpriteGetDrag)(resolveCFunc("spx_sprite_get_drag"))
	x.SpxSpriteSetFriction = (GDExtensionSpxSpriteSetFriction)(resolveCFunc("spx_sprite_set_friction"))
	x.SpxSpriteGetFriction = (GDExtensionSpxSpriteGetFriction)(resolveCFunc("spx_sprite_get_friction"))
	x.SpxSpriteSetCollisionLayer = (GDExtensionSpxSpriteSetCollisionLayer)(resolveCFunc("spx_sprite_set_collision_layer"))
	x.SpxSpriteGetCollisionLayer = (GDExtensionSpxSpriteGetCollisionLayer)(resolveCFunc("spx_sprite_get_collision_layer"))
	x.SpxSpriteSetCollisionMask = (GDExtensionSpxSpriteSetCollisionMask)(resolveCFunc("spx_sprite_set_collision_mask"))
	x.SpxSpriteGetCollisionMask = (GDExtensionSpxSpriteGetCollisionMask)(resolveCFunc("spx_sprite_get_collision_mask"))
	x.SpxSpriteSetTriggerLayer = (GDExtensionSpxSpriteSetTriggerLayer)(resolveCFunc("spx_sprite_set_trigger_layer"))
	x.SpxSpriteGetTriggerLayer = (GDExtensionSpxSpriteGetTriggerLayer)(resolveCFunc("spx_sprite_get_trigger_layer"))
	x.SpxSpriteSetTriggerMask = (GDExtensionSpxSpriteSetTriggerMask)(resolveCFunc("spx_sprite_set_trigger_mask"))
	x.SpxSpriteGetTriggerMask = (GDExtensionSpxSpriteGetTriggerMask)(resolveCFunc("spx_sprite_get_trigger_mask"))
	x.SpxSpriteSetColliderRect = (GDExtensionSpxSpriteSetColliderRect)(resolveCFunc("spx_sprite_set_collider_rect"))
	x.SpxSpriteSetColliderCircle = (GDExtensionSpxSpriteSetColliderCircle)(resolveCFunc("spx_sprite_set_collider_circle"))
	x.SpxSpriteSetColliderCapsule = (GDExtensionSpxSpriteSetColliderCapsule)(resolveCFunc("spx_sprite_set_collider_capsule"))
	x.SpxSpriteSetColliderPolygon = (GDExtensionSpxSpriteSetColliderPolygon)(resolveCFunc("spx_sprite_set_collider_polygon"))
	x.SpxSpriteSetCollisionEnabled = (GDExtensionSpxSpriteSetCollisionEnabled)(resolveCFunc("spx_sprite_set_collision_enabled"))
	x.SpxSpriteIsCollisionEnabled = (GDExtensionSpxSpriteIsCollisionEnabled)(resolveCFunc("spx_sprite_is_collision_enabled"))
	x.SpxSpriteSetTriggerRect = (GDExtensionSpxSpriteSetTriggerRect)(resolveCFunc("spx_sprite_set_trigger_rect"))
	x.SpxSpriteSetTriggerCircle = (GDExtensionSpxSpriteSetTriggerCircle)(resolveCFunc("spx_sprite_set_trigger_circle"))
	x.SpxSpriteSetTriggerCapsule = (GDExtensionSpxSpriteSetTriggerCapsule)(resolveCFunc("spx_sprite_set_trigger_capsule"))
	x.SpxSpriteSetTriggerPolygon = (GDExtensionSpxSpriteSetTriggerPolygon)(resolveCFunc("spx_sprite_set_trigger_polygon"))
	x.SpxSpriteSetTriggerEnabled = (GDExtensionSpxSpriteSetTriggerEnabled)(resolveCFunc("spx_sprite_set_trigger_enabled"))
	x.SpxSpriteIsTriggerEnabled = (GDExtensionSpxSpriteIsTriggerEnabled)(resolveCFunc("spx_sprite_is_trigger_enabled"))
	x.SpxSpriteCheckCollisionByColor = (GDExtensionSpxSpriteCheckCollisionByColor)(resolveCFunc("spx_sprite_check_collision_by_color"))
	x.SpxSpriteCheckCollisionByColors = (GDExtensionSpxSpriteCheckCollisionByColors)(resolveCFunc("spx_sprite_check_collision_by_colors"))
	x.SpxSpriteCheckCollisionByAlpha = (GDExtensionSpxSpriteCheckCollisionByAlpha)(resolveCFunc("spx_sprite_check_collision_by_alpha"))
	x.SpxSpriteCheckCollisionWithSprite = (GDExtensionSpxSpriteCheckCollisionWithSprite)(resolveCFunc("spx_sprite_check_collision_with_sprite"))
	x.SpxSpriteSetPixelCollisionSamplingStep = (GDExtensionSpxSpriteSetPixelCollisionSamplingStep)(resolveCFunc("spx_sprite_set_pixel_collision_sampling_step"))
	x.SpxSpriteGetPixelCollisionSamplingStep = (GDExtensionSpxSpriteGetPixelCollisionSamplingStep)(resolveCFunc("spx_sprite_get_pixel_collision_sampling_step"))
	x.SpxSpriteBatchUpdateTransforms = (GDExtensionSpxSpriteBatchUpdateTransforms)(resolveCFunc("spx_sprite_batch_update_transforms"))
	x.SpxSpriteBatchUpdateVisuals = (GDExtensionSpxSpriteBatchUpdateVisuals)(resolveCFunc("spx_sprite_batch_update_visuals"))
	x.SpxSpriteBatchRetrievePositions = (GDExtensionSpxSpriteBatchRetrievePositions)(resolveCFunc("spx_sprite_batch_retrieve_positions"))
	x.SpxTilemapOpenDrawTilesWithSize = (GDExtensionSpxTilemapOpenDrawTilesWithSize)(resolveCFunc("spx_tilemap_open_draw_tiles_with_size"))
	x.SpxTilemapOpenDrawTiles = (GDExtensionSpxTilemapOpenDrawTiles)(resolveCFunc("spx_tilemap_open_draw_tiles"))
	x.SpxTilemapSetLayerIndex = (GDExtensionSpxTilemapSetLayerIndex)(resolveCFunc("spx_tilemap_set_layer_index"))
	x.SpxTilemapSetTile = (GDExtensionSpxTilemapSetTile)(resolveCFunc("spx_tilemap_set_tile"))
	x.SpxTilemapSetTileWithCollisionInfo = (GDExtensionSpxTilemapSetTileWithCollisionInfo)(resolveCFunc("spx_tilemap_set_tile_with_collision_info"))
	x.SpxTilemapSetLayerOffset = (GDExtensionSpxTilemapSetLayerOffset)(resolveCFunc("spx_tilemap_set_layer_offset"))
	x.SpxTilemapGetLayerOffset = (GDExtensionSpxTilemapGetLayerOffset)(resolveCFunc("spx_tilemap_get_layer_offset"))
	x.SpxTilemapPlaceTiles = (GDExtensionSpxTilemapPlaceTiles)(resolveCFunc("spx_tilemap_place_tiles"))
	x.SpxTilemapPlaceTilesWithLayer = (GDExtensionSpxTilemapPlaceTilesWithLayer)(resolveCFunc("spx_tilemap_place_tiles_with_layer"))
	x.SpxTilemapPlaceTile = (GDExtensionSpxTilemapPlaceTile)(resolveCFunc("spx_tilemap_place_tile"))
	x.SpxTilemapPlaceTileWithLayer = (GDExtensionSpxTilemapPlaceTileWithLayer)(resolveCFunc("spx_tilemap_place_tile_with_layer"))
	x.SpxTilemapEraseTile = (GDExtensionSpxTilemapEraseTile)(resolveCFunc("spx_tilemap_erase_tile"))
	x.SpxTilemapEraseTileWithLayer = (GDExtensionSpxTilemapEraseTileWithLayer)(resolveCFunc("spx_tilemap_erase_tile_with_layer"))
	x.SpxTilemapGetTile = (GDExtensionSpxTilemapGetTile)(resolveCFunc("spx_tilemap_get_tile"))
	x.SpxTilemapGetTileWithLayer = (GDExtensionSpxTilemapGetTileWithLayer)(resolveCFunc("spx_tilemap_get_tile_with_layer"))
	x.SpxTilemapCloseDrawTiles = (GDExtensionSpxTilemapCloseDrawTiles)(resolveCFunc("spx_tilemap_close_draw_tiles"))
	x.SpxTilemapExitTilemapEditorMode = (GDExtensionSpxTilemapExitTilemapEditorMode)(resolveCFunc("spx_tilemap_exit_tilemap_editor_mode"))
	x.SpxTilemapparserLoadTilemap = (GDExtensionSpxTilemapparserLoadTilemap)(resolveCFunc("spx_tilemapparser_load_tilemap"))
	x.SpxTilemapparserUnloadTilemap = (GDExtensionSpxTilemapparserUnloadTilemap)(resolveCFunc("spx_tilemapparser_unload_tilemap"))
	x.SpxTilemapparserDestroyAllTilemaps = (GDExtensionSpxTilemapparserDestroyAllTilemaps)(resolveCFunc("spx_tilemapparser_destroy_all_tilemaps"))
	x.SpxTilemapparserHasTilemap = (GDExtensionSpxTilemapparserHasTilemap)(resolveCFunc("spx_tilemapparser_has_tilemap"))
	x.SpxTilemapparserGetTilemapLayerCount = (GDExtensionSpxTilemapparserGetTilemapLayerCount)(resolveCFunc("spx_tilemapparser_get_tilemap_layer_count"))
	x.SpxUiBindNode = (GDExtensionSpxUiBindNode)(resolveCFunc("spx_ui_bind_node"))
	x.SpxUiCreateNode = (GDExtensionSpxUiCreateNode)(resolveCFunc("spx_ui_create_node"))
	x.SpxUiCreateButton = (GDExtensionSpxUiCreateButton)(resolveCFunc("spx_ui_create_button"))
	x.SpxUiCreateLabel = (GDExtensionSpxUiCreateLabel)(resolveCFunc("spx_ui_create_label"))
	x.SpxUiCreateImage = (GDExtensionSpxUiCreateImage)(resolveCFunc("spx_ui_create_image"))
	x.SpxUiCreateToggle = (GDExtensionSpxUiCreateToggle)(resolveCFunc("spx_ui_create_toggle"))
	x.SpxUiCreateSlider = (GDExtensionSpxUiCreateSlider)(resolveCFunc("spx_ui_create_slider"))
	x.SpxUiCreateInput = (GDExtensionSpxUiCreateInput)(resolveCFunc("spx_ui_create_input"))
	x.SpxUiDestroyNode = (GDExtensionSpxUiDestroyNode)(resolveCFunc("spx_ui_destroy_node"))
	x.SpxUiGetType = (GDExtensionSpxUiGetType)(resolveCFunc("spx_ui_get_type"))
	x.SpxUiSetText = (GDExtensionSpxUiSetText)(resolveCFunc("spx_ui_set_text"))
	x.SpxUiGetText = (GDExtensionSpxUiGetText)(resolveCFunc("spx_ui_get_text"))
	x.SpxUiSetTexture = (GDExtensionSpxUiSetTexture)(resolveCFunc("spx_ui_set_texture"))
	x.SpxUiGetTexture = (GDExtensionSpxUiGetTexture)(resolveCFunc("spx_ui_get_texture"))
	x.SpxUiSetColor = (GDExtensionSpxUiSetColor)(resolveCFunc("spx_ui_set_color"))
	x.SpxUiGetColor = (GDExtensionSpxUiGetColor)(resolveCFunc("spx_ui_get_color"))
	x.SpxUiSetFontSize = (GDExtensionSpxUiSetFontSize)(resolveCFunc("spx_ui_set_font_size"))
	x.SpxUiGetFontSize = (GDExtensionSpxUiGetFontSize)(resolveCFunc("spx_ui_get_font_size"))
	x.SpxUiSetVisible = (GDExtensionSpxUiSetVisible)(resolveCFunc("spx_ui_set_visible"))
	x.SpxUiGetVisible = (GDExtensionSpxUiGetVisible)(resolveCFunc("spx_ui_get_visible"))
	x.SpxUiSetInteractable = (GDExtensionSpxUiSetInteractable)(resolveCFunc("spx_ui_set_interactable"))
	x.SpxUiGetInteractable = (GDExtensionSpxUiGetInteractable)(resolveCFunc("spx_ui_get_interactable"))
	x.SpxUiSetRect = (GDExtensionSpxUiSetRect)(resolveCFunc("spx_ui_set_rect"))
	x.SpxUiGetRect = (GDExtensionSpxUiGetRect)(resolveCFunc("spx_ui_get_rect"))
	x.SpxUiGetLayoutDirection = (GDExtensionSpxUiGetLayoutDirection)(resolveCFunc("spx_ui_get_layout_direction"))
	x.SpxUiSetLayoutDirection = (GDExtensionSpxUiSetLayoutDirection)(resolveCFunc("spx_ui_set_layout_direction"))
	x.SpxUiGetLayoutMode = (GDExtensionSpxUiGetLayoutMode)(resolveCFunc("spx_ui_get_layout_mode"))
	x.SpxUiSetLayoutMode = (GDExtensionSpxUiSetLayoutMode)(resolveCFunc("spx_ui_set_layout_mode"))
	x.SpxUiGetAnchorsPreset = (GDExtensionSpxUiGetAnchorsPreset)(resolveCFunc("spx_ui_get_anchors_preset"))
	x.SpxUiSetAnchorsPreset = (GDExtensionSpxUiSetAnchorsPreset)(resolveCFunc("spx_ui_set_anchors_preset"))
	x.SpxUiGetScale = (GDExtensionSpxUiGetScale)(resolveCFunc("spx_ui_get_scale"))
	x.SpxUiSetScale = (GDExtensionSpxUiSetScale)(resolveCFunc("spx_ui_set_scale"))
	x.SpxUiGetPosition = (GDExtensionSpxUiGetPosition)(resolveCFunc("spx_ui_get_position"))
	x.SpxUiSetPosition = (GDExtensionSpxUiSetPosition)(resolveCFunc("spx_ui_set_position"))
	x.SpxUiGetSize = (GDExtensionSpxUiGetSize)(resolveCFunc("spx_ui_get_size"))
	x.SpxUiSetSize = (GDExtensionSpxUiSetSize)(resolveCFunc("spx_ui_set_size"))
	x.SpxUiGetGlobalPosition = (GDExtensionSpxUiGetGlobalPosition)(resolveCFunc("spx_ui_get_global_position"))
	x.SpxUiSetGlobalPosition = (GDExtensionSpxUiSetGlobalPosition)(resolveCFunc("spx_ui_set_global_position"))
	x.SpxUiGetRotation = (GDExtensionSpxUiGetRotation)(resolveCFunc("spx_ui_get_rotation"))
	x.SpxUiSetRotation = (GDExtensionSpxUiSetRotation)(resolveCFunc("spx_ui_set_rotation"))
	x.SpxUiGetFlip = (GDExtensionSpxUiGetFlip)(resolveCFunc("spx_ui_get_flip"))
	x.SpxUiSetFlip = (GDExtensionSpxUiSetFlip)(resolveCFunc("spx_ui_set_flip"))
}
