/*------------------------------------------------------------------------------
//   This code was generated by gdspx template sync.gen.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//----------------------------------------------------------------------------*/

package engine

import (
	. "github.com/realdream-ai/gdspx/pkg/engine"
)

// IAudioMgr
func SyncAudioStopAll() {
	WaitMainThread(func() {
		AudioMgr.StopAll()
	})
}
func SyncAudioPlaySfx(path string) {
	WaitMainThread(func() {
		AudioMgr.PlaySfx(path)
	})
}
func SyncAudioPlayMusic(path string) {
	WaitMainThread(func() {
		AudioMgr.PlayMusic(path)
	})
}
func SyncAudioPauseMusic() {
	WaitMainThread(func() {
		AudioMgr.PauseMusic()
	})
}
func SyncAudioResumeMusic() {
	WaitMainThread(func() {
		AudioMgr.ResumeMusic()
	})
}
func SyncAudioGetMusicTimer() float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = AudioMgr.GetMusicTimer()
	})
	return _ret1
}
func SyncAudioSetMusicTimer(time float32) {
	WaitMainThread(func() {
		AudioMgr.SetMusicTimer(time)
	})
}
func SyncAudioIsMusicPlaying() bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = AudioMgr.IsMusicPlaying()
	})
	return _ret1
}
func SyncAudioSetSfxVolume(volume float32) {
	WaitMainThread(func() {
		AudioMgr.SetSfxVolume(volume)
	})
}
func SyncAudioGetSfxVolume() float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = AudioMgr.GetSfxVolume()
	})
	return _ret1
}
func SyncAudioSetMusicVolume(volume float32) {
	WaitMainThread(func() {
		AudioMgr.SetMusicVolume(volume)
	})
}
func SyncAudioGetMusicVolume() float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = AudioMgr.GetMusicVolume()
	})
	return _ret1
}
func SyncAudioSetMasterVolume(volume float32) {
	WaitMainThread(func() {
		AudioMgr.SetMasterVolume(volume)
	})
}
func SyncAudioGetMasterVolume() float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = AudioMgr.GetMasterVolume()
	})
	return _ret1
}

// ICameraMgr
func SyncCameraGetCameraPosition() Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = CameraMgr.GetCameraPosition()
	})
	return _ret1
}
func SyncCameraSetCameraPosition(position Vec2) {
	WaitMainThread(func() {
		CameraMgr.SetCameraPosition(position)
	})
}
func SyncCameraGetCameraZoom() Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = CameraMgr.GetCameraZoom()
	})
	return _ret1
}
func SyncCameraSetCameraZoom(size Vec2) {
	WaitMainThread(func() {
		CameraMgr.SetCameraZoom(size)
	})
}
func SyncCameraGetViewportRect() Rect2 {
	var _ret1 Rect2
	WaitMainThread(func() {
		_ret1 = CameraMgr.GetViewportRect()
	})
	return _ret1
}

// IInputMgr
func SyncInputGetMousePos() Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = InputMgr.GetMousePos()
	})
	return _ret1
}
func SyncInputGetKey(key int64) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = InputMgr.GetKey(key)
	})
	return _ret1
}
func SyncInputGetMouseState(mouse_id int64) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = InputMgr.GetMouseState(mouse_id)
	})
	return _ret1
}
func SyncInputGetKeyState(key int64) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = InputMgr.GetKeyState(key)
	})
	return _ret1
}
func SyncInputGetAxis(neg_action string, pos_action string) float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = InputMgr.GetAxis(neg_action, pos_action)
	})
	return _ret1
}
func SyncInputIsActionPressed(action string) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = InputMgr.IsActionPressed(action)
	})
	return _ret1
}
func SyncInputIsActionJustPressed(action string) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = InputMgr.IsActionJustPressed(action)
	})
	return _ret1
}
func SyncInputIsActionJustReleased(action string) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = InputMgr.IsActionJustReleased(action)
	})
	return _ret1
}

// IPhysicMgr
func SyncPhysicRaycast(from Vec2, to Vec2, collision_mask int64) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = PhysicMgr.Raycast(from, to, collision_mask)
	})
	return _ret1
}
func SyncPhysicCheckCollision(from Vec2, to Vec2, collision_mask int64, collide_with_areas bool, collide_with_bodies bool) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = PhysicMgr.CheckCollision(from, to, collision_mask, collide_with_areas, collide_with_bodies)
	})
	return _ret1
}
func SyncPhysicCheckTouchedCameraBoundary(obj Object, board_type int64) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = PhysicMgr.CheckTouchedCameraBoundary(obj, board_type)
	})
	return _ret1
}

// IPlatformMgr
func SyncPlatformSetWindowPosition(pos Vec2) {
	WaitMainThread(func() {
		PlatformMgr.SetWindowPosition(pos)
	})
}
func SyncPlatformGetWindowPosition() Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = PlatformMgr.GetWindowPosition()
	})
	return _ret1
}
func SyncPlatformSetWindowSize(width int64, height int64) {
	WaitMainThread(func() {
		PlatformMgr.SetWindowSize(width, height)
	})
}
func SyncPlatformGetWindowSize() Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = PlatformMgr.GetWindowSize()
	})
	return _ret1
}
func SyncPlatformSetWindowTitle(title string) {
	WaitMainThread(func() {
		PlatformMgr.SetWindowTitle(title)
	})
}
func SyncPlatformGetWindowTitle() string {
	var _ret1 string
	WaitMainThread(func() {
		_ret1 = PlatformMgr.GetWindowTitle()
	})
	return _ret1
}
func SyncPlatformSetWindowFullscreen(enable bool) {
	WaitMainThread(func() {
		PlatformMgr.SetWindowFullscreen(enable)
	})
}
func SyncPlatformIsWindowFullscreen() bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = PlatformMgr.IsWindowFullscreen()
	})
	return _ret1
}
func SyncPlatformSetDebugMode(enable bool) {
	WaitMainThread(func() {
		PlatformMgr.SetDebugMode(enable)
	})
}
func SyncPlatformIsDebugMode() bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = PlatformMgr.IsDebugMode()
	})
	return _ret1
}
func SyncPlatformGetTimeScale() float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = PlatformMgr.GetTimeScale()
	})
	return _ret1
}
func SyncPlatformSetTimeScale(time_scale float32) {
	WaitMainThread(func() {
		PlatformMgr.SetTimeScale(time_scale)
	})
}

// IResMgr
func SyncResCreateAnimation(sprite_type_name string, anim_name string, context string, fps int64, is_altas bool) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = ResMgr.CreateAnimation(sprite_type_name, anim_name, context, fps, is_altas)
	})
	return _ret1
}
func SyncResSetLoadMode(is_direct_mode bool) {
	WaitMainThread(func() {
		ResMgr.SetLoadMode(is_direct_mode)
	})
}
func SyncResGetLoadMode() bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = ResMgr.GetLoadMode()
	})
	return _ret1
}
func SyncResGetBoundFromAlpha(p_path string) Rect2 {
	var _ret1 Rect2
	WaitMainThread(func() {
		_ret1 = ResMgr.GetBoundFromAlpha(p_path)
	})
	return _ret1
}
func SyncResGetImageSize(p_path string) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = ResMgr.GetImageSize(p_path)
	})
	return _ret1
}
func SyncResReadAllText(p_path string) string {
	var _ret1 string
	WaitMainThread(func() {
		_ret1 = ResMgr.ReadAllText(p_path)
	})
	return _ret1
}
func SyncResHasFile(p_path string) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = ResMgr.HasFile(p_path)
	})
	return _ret1
}

// ISceneMgr
func SyncSceneChangeSceneToFile(path string) {
	WaitMainThread(func() {
		SceneMgr.ChangeSceneToFile(path)
	})
}
func SyncSceneReloadCurrentScene() int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = SceneMgr.ReloadCurrentScene()
	})
	return _ret1
}
func SyncSceneUnloadCurrentScene() {
	WaitMainThread(func() {
		SceneMgr.UnloadCurrentScene()
	})
}

// ISpriteMgr
func SyncSpriteSetDontDestroyOnLoad(obj Object) {
	WaitMainThread(func() {
		SpriteMgr.SetDontDestroyOnLoad(obj)
	})
}
func SyncSpriteSetProcess(obj Object, is_on bool) {
	WaitMainThread(func() {
		SpriteMgr.SetProcess(obj, is_on)
	})
}
func SyncSpriteSetPhysicProcess(obj Object, is_on bool) {
	WaitMainThread(func() {
		SpriteMgr.SetPhysicProcess(obj, is_on)
	})
}
func SyncSpriteSetTypeName(obj Object, type_name string) {
	WaitMainThread(func() {
		SpriteMgr.SetTypeName(obj, type_name)
	})
}
func SyncSpriteSetChildPosition(obj Object, path string, pos Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetChildPosition(obj, path, pos)
	})
}
func SyncSpriteGetChildPosition(obj Object, path string) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetChildPosition(obj, path)
	})
	return _ret1
}
func SyncSpriteSetChildRotation(obj Object, path string, rot float32) {
	WaitMainThread(func() {
		SpriteMgr.SetChildRotation(obj, path, rot)
	})
}
func SyncSpriteGetChildRotation(obj Object, path string) float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetChildRotation(obj, path)
	})
	return _ret1
}
func SyncSpriteSetChildScale(obj Object, path string, scale Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetChildScale(obj, path, scale)
	})
}
func SyncSpriteGetChildScale(obj Object, path string) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetChildScale(obj, path)
	})
	return _ret1
}
func SyncSpriteCheckCollision(obj Object, target Object, is_src_trigger bool, is_dst_trigger bool) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.CheckCollision(obj, target, is_src_trigger, is_dst_trigger)
	})
	return _ret1
}
func SyncSpriteCheckCollisionWithPoint(obj Object, point Vec2, is_trigger bool) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.CheckCollisionWithPoint(obj, point, is_trigger)
	})
	return _ret1
}
func SyncSpriteCreateSprite(path string) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = SpriteMgr.CreateSprite(path)
	})
	return _ret1
}
func SyncSpriteCloneSprite(obj Object) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = SpriteMgr.CloneSprite(obj)
	})
	return _ret1
}
func SyncSpriteDestroySprite(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.DestroySprite(obj)
	})
	return _ret1
}
func SyncSpriteIsSpriteAlive(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsSpriteAlive(obj)
	})
	return _ret1
}
func SyncSpriteSetPosition(obj Object, pos Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetPosition(obj, pos)
	})
}
func SyncSpriteGetPosition(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetPosition(obj)
	})
	return _ret1
}
func SyncSpriteSetRotation(obj Object, rot float32) {
	WaitMainThread(func() {
		SpriteMgr.SetRotation(obj, rot)
	})
}
func SyncSpriteGetRotation(obj Object) float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetRotation(obj)
	})
	return _ret1
}
func SyncSpriteSetScale(obj Object, scale Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetScale(obj, scale)
	})
}
func SyncSpriteGetScale(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetScale(obj)
	})
	return _ret1
}
func SyncSpriteSetRenderScale(obj Object, scale Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetRenderScale(obj, scale)
	})
}
func SyncSpriteGetRenderScale(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetRenderScale(obj)
	})
	return _ret1
}
func SyncSpriteSetColor(obj Object, color Color) {
	WaitMainThread(func() {
		SpriteMgr.SetColor(obj, color)
	})
}
func SyncSpriteGetColor(obj Object) Color {
	var _ret1 Color
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetColor(obj)
	})
	return _ret1
}
func SyncSpriteSetTextureAltas(obj Object, path string, rect2 Rect2) {
	WaitMainThread(func() {
		SpriteMgr.SetTextureAltas(obj, path, rect2)
	})
}
func SyncSpriteSetTexture(obj Object, path string) {
	WaitMainThread(func() {
		SpriteMgr.SetTexture(obj, path)
	})
}
func SyncSpriteGetTexture(obj Object) string {
	var _ret1 string
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetTexture(obj)
	})
	return _ret1
}
func SyncSpriteSetVisible(obj Object, visible bool) {
	WaitMainThread(func() {
		SpriteMgr.SetVisible(obj, visible)
	})
}
func SyncSpriteGetVisible(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetVisible(obj)
	})
	return _ret1
}
func SyncSpriteGetZIndex(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetZIndex(obj)
	})
	return _ret1
}
func SyncSpriteSetZIndex(obj Object, z int64) {
	WaitMainThread(func() {
		SpriteMgr.SetZIndex(obj, z)
	})
}
func SyncSpritePlayAnim(obj Object, p_name string, p_speed float32, p_revert bool) {
	WaitMainThread(func() {
		SpriteMgr.PlayAnim(obj, p_name, p_speed, p_revert)
	})
}
func SyncSpritePlayBackwardsAnim(obj Object, p_name string) {
	WaitMainThread(func() {
		SpriteMgr.PlayBackwardsAnim(obj, p_name)
	})
}
func SyncSpritePauseAnim(obj Object) {
	WaitMainThread(func() {
		SpriteMgr.PauseAnim(obj)
	})
}
func SyncSpriteStopAnim(obj Object) {
	WaitMainThread(func() {
		SpriteMgr.StopAnim(obj)
	})
}
func SyncSpriteIsPlayingAnim(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsPlayingAnim(obj)
	})
	return _ret1
}
func SyncSpriteSetAnim(obj Object, p_name string) {
	WaitMainThread(func() {
		SpriteMgr.SetAnim(obj, p_name)
	})
}
func SyncSpriteGetAnim(obj Object) string {
	var _ret1 string
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetAnim(obj)
	})
	return _ret1
}
func SyncSpriteSetAnimFrame(obj Object, p_frame int64) {
	WaitMainThread(func() {
		SpriteMgr.SetAnimFrame(obj, p_frame)
	})
}
func SyncSpriteGetAnimFrame(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetAnimFrame(obj)
	})
	return _ret1
}
func SyncSpriteSetAnimSpeedScale(obj Object, p_speed_scale float32) {
	WaitMainThread(func() {
		SpriteMgr.SetAnimSpeedScale(obj, p_speed_scale)
	})
}
func SyncSpriteGetAnimSpeedScale(obj Object) float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetAnimSpeedScale(obj)
	})
	return _ret1
}
func SyncSpriteGetAnimPlayingSpeed(obj Object) float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetAnimPlayingSpeed(obj)
	})
	return _ret1
}
func SyncSpriteSetAnimCentered(obj Object, p_center bool) {
	WaitMainThread(func() {
		SpriteMgr.SetAnimCentered(obj, p_center)
	})
}
func SyncSpriteIsAnimCentered(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsAnimCentered(obj)
	})
	return _ret1
}
func SyncSpriteSetAnimOffset(obj Object, p_offset Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetAnimOffset(obj, p_offset)
	})
}
func SyncSpriteGetAnimOffset(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetAnimOffset(obj)
	})
	return _ret1
}
func SyncSpriteSetAnimFlipH(obj Object, p_flip bool) {
	WaitMainThread(func() {
		SpriteMgr.SetAnimFlipH(obj, p_flip)
	})
}
func SyncSpriteIsAnimFlippedH(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsAnimFlippedH(obj)
	})
	return _ret1
}
func SyncSpriteSetAnimFlipV(obj Object, p_flip bool) {
	WaitMainThread(func() {
		SpriteMgr.SetAnimFlipV(obj, p_flip)
	})
}
func SyncSpriteIsAnimFlippedV(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsAnimFlippedV(obj)
	})
	return _ret1
}
func SyncSpriteSetVelocity(obj Object, velocity Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetVelocity(obj, velocity)
	})
}
func SyncSpriteGetVelocity(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetVelocity(obj)
	})
	return _ret1
}
func SyncSpriteIsOnFloor(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsOnFloor(obj)
	})
	return _ret1
}
func SyncSpriteIsOnFloorOnly(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsOnFloorOnly(obj)
	})
	return _ret1
}
func SyncSpriteIsOnWall(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsOnWall(obj)
	})
	return _ret1
}
func SyncSpriteIsOnWallOnly(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsOnWallOnly(obj)
	})
	return _ret1
}
func SyncSpriteIsOnCeiling(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsOnCeiling(obj)
	})
	return _ret1
}
func SyncSpriteIsOnCeilingOnly(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsOnCeilingOnly(obj)
	})
	return _ret1
}
func SyncSpriteGetLastMotion(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetLastMotion(obj)
	})
	return _ret1
}
func SyncSpriteGetPositionDelta(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetPositionDelta(obj)
	})
	return _ret1
}
func SyncSpriteGetFloorNormal(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetFloorNormal(obj)
	})
	return _ret1
}
func SyncSpriteGetWallNormal(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetWallNormal(obj)
	})
	return _ret1
}
func SyncSpriteGetRealVelocity(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetRealVelocity(obj)
	})
	return _ret1
}
func SyncSpriteMoveAndSlide(obj Object) {
	WaitMainThread(func() {
		SpriteMgr.MoveAndSlide(obj)
	})
}
func SyncSpriteSetGravity(obj Object, gravity float32) {
	WaitMainThread(func() {
		SpriteMgr.SetGravity(obj, gravity)
	})
}
func SyncSpriteGetGravity(obj Object) float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetGravity(obj)
	})
	return _ret1
}
func SyncSpriteSetMass(obj Object, mass float32) {
	WaitMainThread(func() {
		SpriteMgr.SetMass(obj, mass)
	})
}
func SyncSpriteGetMass(obj Object) float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetMass(obj)
	})
	return _ret1
}
func SyncSpriteAddForce(obj Object, force Vec2) {
	WaitMainThread(func() {
		SpriteMgr.AddForce(obj, force)
	})
}
func SyncSpriteAddImpulse(obj Object, impulse Vec2) {
	WaitMainThread(func() {
		SpriteMgr.AddImpulse(obj, impulse)
	})
}
func SyncSpriteSetCollisionLayer(obj Object, layer int64) {
	WaitMainThread(func() {
		SpriteMgr.SetCollisionLayer(obj, layer)
	})
}
func SyncSpriteGetCollisionLayer(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetCollisionLayer(obj)
	})
	return _ret1
}
func SyncSpriteSetCollisionMask(obj Object, mask int64) {
	WaitMainThread(func() {
		SpriteMgr.SetCollisionMask(obj, mask)
	})
}
func SyncSpriteGetCollisionMask(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetCollisionMask(obj)
	})
	return _ret1
}
func SyncSpriteSetTriggerLayer(obj Object, layer int64) {
	WaitMainThread(func() {
		SpriteMgr.SetTriggerLayer(obj, layer)
	})
}
func SyncSpriteGetTriggerLayer(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetTriggerLayer(obj)
	})
	return _ret1
}
func SyncSpriteSetTriggerMask(obj Object, mask int64) {
	WaitMainThread(func() {
		SpriteMgr.SetTriggerMask(obj, mask)
	})
}
func SyncSpriteGetTriggerMask(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = SpriteMgr.GetTriggerMask(obj)
	})
	return _ret1
}
func SyncSpriteSetColliderRect(obj Object, center Vec2, size Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetColliderRect(obj, center, size)
	})
}
func SyncSpriteSetColliderCircle(obj Object, center Vec2, radius float32) {
	WaitMainThread(func() {
		SpriteMgr.SetColliderCircle(obj, center, radius)
	})
}
func SyncSpriteSetColliderCapsule(obj Object, center Vec2, size Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetColliderCapsule(obj, center, size)
	})
}
func SyncSpriteSetCollisionEnabled(obj Object, enabled bool) {
	WaitMainThread(func() {
		SpriteMgr.SetCollisionEnabled(obj, enabled)
	})
}
func SyncSpriteIsCollisionEnabled(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsCollisionEnabled(obj)
	})
	return _ret1
}
func SyncSpriteSetTriggerRect(obj Object, center Vec2, size Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetTriggerRect(obj, center, size)
	})
}
func SyncSpriteSetTriggerCircle(obj Object, center Vec2, radius float32) {
	WaitMainThread(func() {
		SpriteMgr.SetTriggerCircle(obj, center, radius)
	})
}
func SyncSpriteSetTriggerCapsule(obj Object, center Vec2, size Vec2) {
	WaitMainThread(func() {
		SpriteMgr.SetTriggerCapsule(obj, center, size)
	})
}
func SyncSpriteSetTriggerEnabled(obj Object, trigger bool) {
	WaitMainThread(func() {
		SpriteMgr.SetTriggerEnabled(obj, trigger)
	})
}
func SyncSpriteIsTriggerEnabled(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = SpriteMgr.IsTriggerEnabled(obj)
	})
	return _ret1
}

// IUiMgr
func SyncUiBindNode(obj Object, rel_path string) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = UiMgr.BindNode(obj, rel_path)
	})
	return _ret1
}
func SyncUiCreateNode(path string) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = UiMgr.CreateNode(path)
	})
	return _ret1
}
func SyncUiCreateButton(path string, text string) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = UiMgr.CreateButton(path, text)
	})
	return _ret1
}
func SyncUiCreateLabel(path string, text string) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = UiMgr.CreateLabel(path, text)
	})
	return _ret1
}
func SyncUiCreateImage(path string) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = UiMgr.CreateImage(path)
	})
	return _ret1
}
func SyncUiCreateToggle(path string, value bool) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = UiMgr.CreateToggle(path, value)
	})
	return _ret1
}
func SyncUiCreateSlider(path string, value float32) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = UiMgr.CreateSlider(path, value)
	})
	return _ret1
}
func SyncUiCreateInput(path string, text string) Object {
	var _ret1 Object
	WaitMainThread(func() {
		_ret1 = UiMgr.CreateInput(path, text)
	})
	return _ret1
}
func SyncUiDestroyNode(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = UiMgr.DestroyNode(obj)
	})
	return _ret1
}
func SyncUiGetType(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = UiMgr.GetType(obj)
	})
	return _ret1
}
func SyncUiSetText(obj Object, text string) {
	WaitMainThread(func() {
		UiMgr.SetText(obj, text)
	})
}
func SyncUiGetText(obj Object) string {
	var _ret1 string
	WaitMainThread(func() {
		_ret1 = UiMgr.GetText(obj)
	})
	return _ret1
}
func SyncUiSetTexture(obj Object, path string) {
	WaitMainThread(func() {
		UiMgr.SetTexture(obj, path)
	})
}
func SyncUiGetTexture(obj Object) string {
	var _ret1 string
	WaitMainThread(func() {
		_ret1 = UiMgr.GetTexture(obj)
	})
	return _ret1
}
func SyncUiSetColor(obj Object, color Color) {
	WaitMainThread(func() {
		UiMgr.SetColor(obj, color)
	})
}
func SyncUiGetColor(obj Object) Color {
	var _ret1 Color
	WaitMainThread(func() {
		_ret1 = UiMgr.GetColor(obj)
	})
	return _ret1
}
func SyncUiSetFontSize(obj Object, size int64) {
	WaitMainThread(func() {
		UiMgr.SetFontSize(obj, size)
	})
}
func SyncUiGetFontSize(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = UiMgr.GetFontSize(obj)
	})
	return _ret1
}
func SyncUiSetVisible(obj Object, visible bool) {
	WaitMainThread(func() {
		UiMgr.SetVisible(obj, visible)
	})
}
func SyncUiGetVisible(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = UiMgr.GetVisible(obj)
	})
	return _ret1
}
func SyncUiSetInteractable(obj Object, interactable bool) {
	WaitMainThread(func() {
		UiMgr.SetInteractable(obj, interactable)
	})
}
func SyncUiGetInteractable(obj Object) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = UiMgr.GetInteractable(obj)
	})
	return _ret1
}
func SyncUiSetRect(obj Object, rect Rect2) {
	WaitMainThread(func() {
		UiMgr.SetRect(obj, rect)
	})
}
func SyncUiGetRect(obj Object) Rect2 {
	var _ret1 Rect2
	WaitMainThread(func() {
		_ret1 = UiMgr.GetRect(obj)
	})
	return _ret1
}
func SyncUiGetLayoutDirection(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = UiMgr.GetLayoutDirection(obj)
	})
	return _ret1
}
func SyncUiSetLayoutDirection(obj Object, value int64) {
	WaitMainThread(func() {
		UiMgr.SetLayoutDirection(obj, value)
	})
}
func SyncUiGetLayoutMode(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = UiMgr.GetLayoutMode(obj)
	})
	return _ret1
}
func SyncUiSetLayoutMode(obj Object, value int64) {
	WaitMainThread(func() {
		UiMgr.SetLayoutMode(obj, value)
	})
}
func SyncUiGetAnchorsPreset(obj Object) int64 {
	var _ret1 int64
	WaitMainThread(func() {
		_ret1 = UiMgr.GetAnchorsPreset(obj)
	})
	return _ret1
}
func SyncUiSetAnchorsPreset(obj Object, value int64) {
	WaitMainThread(func() {
		UiMgr.SetAnchorsPreset(obj, value)
	})
}
func SyncUiGetScale(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = UiMgr.GetScale(obj)
	})
	return _ret1
}
func SyncUiSetScale(obj Object, value Vec2) {
	WaitMainThread(func() {
		UiMgr.SetScale(obj, value)
	})
}
func SyncUiGetPosition(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = UiMgr.GetPosition(obj)
	})
	return _ret1
}
func SyncUiSetPosition(obj Object, value Vec2) {
	WaitMainThread(func() {
		UiMgr.SetPosition(obj, value)
	})
}
func SyncUiGetSize(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = UiMgr.GetSize(obj)
	})
	return _ret1
}
func SyncUiSetSize(obj Object, value Vec2) {
	WaitMainThread(func() {
		UiMgr.SetSize(obj, value)
	})
}
func SyncUiGetGlobalPosition(obj Object) Vec2 {
	var _ret1 Vec2
	WaitMainThread(func() {
		_ret1 = UiMgr.GetGlobalPosition(obj)
	})
	return _ret1
}
func SyncUiSetGlobalPosition(obj Object, value Vec2) {
	WaitMainThread(func() {
		UiMgr.SetGlobalPosition(obj, value)
	})
}
func SyncUiGetRotation(obj Object) float32 {
	var _ret1 float32
	WaitMainThread(func() {
		_ret1 = UiMgr.GetRotation(obj)
	})
	return _ret1
}
func SyncUiSetRotation(obj Object, value float32) {
	WaitMainThread(func() {
		UiMgr.SetRotation(obj, value)
	})
}
func SyncUiGetFlip(obj Object, horizontal bool) bool {
	var _ret1 bool
	WaitMainThread(func() {
		_ret1 = UiMgr.GetFlip(obj, horizontal)
	})
	return _ret1
}
func SyncUiSetFlip(obj Object, horizontal bool, is_flip bool) {
	WaitMainThread(func() {
		UiMgr.SetFlip(obj, horizontal, is_flip)
	})
}
