/*
 * Copyright (c) 2021 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gdext

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/goplus/spx/v3/internal/cmd/codegen/gdextensionparser/clang"
	"github.com/goplus/spx/v3/internal/cmd/codegen/generate/common"
)

// Default callbacks are generated from the ABI fields, so adding a callback
// cannot leave an uninitialized function pointer in the engine's fallback table.
func (g *Generator) writeCallbackDefaults(spxModulePath string) error {
	functions := make(map[string]clang.TypedefFunction)
	for _, function := range g.AST().CollectGDExtensionICallbackFunctions() {
		functions[function.Name] = function
	}
	var callbackStruct *clang.TypedefStruct
	for _, expr := range g.AST().Expr {
		if expr.Struct != nil && expr.Struct.Name == "SpxCallbackInfo" {
			callbackStruct = expr.Struct
			break
		}
	}
	if callbackStruct == nil {
		return fmt.Errorf("generate callback defaults: missing SpxCallbackInfo")
	}
	var out strings.Builder
	out.WriteString(`// Code generated by SPX codegen; DO NOT EDIT.
#ifndef SPX_CALLBACK_DEFAULTS_GEN_H
#define SPX_CALLBACK_DEFAULTS_GEN_H

#include "gdextension_spx_ext.h"

inline SpxCallbackInfo get_default_spx_callbacks() {
	SpxCallbackInfo callbacks = {};
`)
	for _, field := range callbackStruct.Fields {
		if field.Variable == nil {
			return fmt.Errorf("generate callback defaults: unsupported inline callback field")
		}
		variable := field.Variable
		function, ok := functions[variable.Type.Name]
		if !ok || variable.Type.IsPointer || function.ReturnType.CStyleString() != "void" {
			return fmt.Errorf("generate callback defaults: unsupported callback %s", variable.Name)
		}
		args := make([]string, len(function.Arguments))
		for i, arg := range function.Arguments {
			args[i] = arg.Type.CStyleString()
		}
		fmt.Fprintf(&out, "\tcallbacks.%s = [](%s) {};\n", variable.Name, strings.Join(args, ", "))
	}
	out.WriteString("\treturn callbacks;\n}\n\n#endif // SPX_CALLBACK_DEFAULTS_GEN_H\n")
	return common.WriteGeneratedFile(filepath.Join(spxModulePath, "spx_callback_defaults.gen.h"), []byte(out.String()), 0o644)
}
