//go:build pure_engine
// +build pure_engine

/*
 * Copyright (c) 2021 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*------------------------------------------------------------------------------
//   This code was generated by template sprite_pure.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "sprite_pure.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

// Code generated by spx codegen; DO NOT EDIT.

package engine

import (
	. "github.com/goplus/spbase/mathf"
)

func (pself *Sprite) AddForce(force Vec2) {
}

func (pself *Sprite) AddImpulse(impulse Vec2) {
}

func (pself *Sprite) BatchRetrievePositions(objs Array) Array {
	return nil
}

func (pself *Sprite) BatchUpdateTransforms(buffer []float32) {
}

func (pself *Sprite) BatchUpdateVisuals(buffer []float32) {
}

func (pself *Sprite) CheckCollision(target Object, is_src_trigger bool, is_dst_trigger bool) bool {
	return false
}

func (pself *Sprite) CheckCollisionByAlpha(alpha_threshold float64) bool {
	return false
}

func (pself *Sprite) CheckCollisionByColor(color Color, color_threshold float64, alpha_threshold float64) bool {
	return false
}

func (pself *Sprite) CheckCollisionWithPoint(point Vec2, is_trigger bool) bool {
	return false
}

func (pself *Sprite) CheckCollisionWithSprite(obj_b Object, alpha_threshold float64, use_pixel_perfect bool) bool {
	return false
}

func (pself *Sprite) CloneSprite() Object {
	return 0
}

func (pself *Sprite) CreateBackdrop(path string) Object {
	return 0
}

func (pself *Sprite) CreateBareSprite(pos Vec2) Object {
	return 0
}

func (pself *Sprite) CreateSprite(path string, pos Vec2) Object {
	return 0
}

func (pself *Sprite) DestroySprite() bool {
	return false
}

func (pself *Sprite) GetAnim() string {
	return ""
}

func (pself *Sprite) GetAnimFrame() int64 {
	return 0
}

func (pself *Sprite) GetAnimOffset() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetAnimPlayingSpeed() float64 {
	return 0
}

func (pself *Sprite) GetAnimSpeedScale() float64 {
	return 0
}

func (pself *Sprite) GetChildPosition(path string) Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetChildRotation(path string) float64 {
	return 0
}

func (pself *Sprite) GetChildScale(path string) Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetCollisionLayer() int64 {
	return 0
}

func (pself *Sprite) GetCollisionMask() int64 {
	return 0
}

func (pself *Sprite) GetColor() Color {
	return Color{}
}

func (pself *Sprite) GetCurrentAnimName() string {
	return ""
}

func (pself *Sprite) GetDrag() float64 {
	return 0
}

func (pself *Sprite) GetFloorNormal() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetFriction() float64 {
	return 0
}

func (pself *Sprite) GetGravity() float64 {
	return 0
}

func (pself *Sprite) GetGravityScale() float64 {
	return 0
}

func (pself *Sprite) GetLastMotion() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetMass() float64 {
	return 0
}

func (pself *Sprite) GetMaterialParams(effect string) float64 {
	return 0
}

func (pself *Sprite) GetMaterialParamsColor(effect string) Color {
	return Color{}
}

func (pself *Sprite) GetMaterialParamsVec4(effect string) Vec4 {
	return Vec4{}
}

func (pself *Sprite) GetMaterialShader() string {
	return ""
}

func (pself *Sprite) GetPhysicsMode() int64 {
	return 0
}

func (pself *Sprite) GetPivot() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetPixelCollisionSamplingStep() int64 {
	return 0
}

func (pself *Sprite) GetPosition() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetPositionDelta() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetRealVelocity() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetRenderScale() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetRotation() float64 {
	return 0
}

func (pself *Sprite) GetScale() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetTexture() string {
	return ""
}

func (pself *Sprite) GetTriggerLayer() int64 {
	return 0
}

func (pself *Sprite) GetTriggerMask() int64 {
	return 0
}

func (pself *Sprite) GetVelocity() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetVisible() bool {
	return false
}

func (pself *Sprite) GetWallNormal() Vec2 {
	return Vec2{}
}

func (pself *Sprite) GetZIndex() int64 {
	return 0
}

func (pself *Sprite) IsAnimCentered() bool {
	return false
}

func (pself *Sprite) IsAnimFlippedH() bool {
	return false
}

func (pself *Sprite) IsAnimFlippedV() bool {
	return false
}

func (pself *Sprite) IsCollisionEnabled() bool {
	return false
}

func (pself *Sprite) IsDebugCollisionVisible() bool {
	return false
}

func (pself *Sprite) IsOnCeiling() bool {
	return false
}

func (pself *Sprite) IsOnCeilingOnly() bool {
	return false
}

func (pself *Sprite) IsOnFloor() bool {
	return false
}

func (pself *Sprite) IsOnFloorOnly() bool {
	return false
}

func (pself *Sprite) IsOnWall() bool {
	return false
}

func (pself *Sprite) IsOnWallOnly() bool {
	return false
}

func (pself *Sprite) IsPlayingAnim() bool {
	return false
}

func (pself *Sprite) IsSpriteAlive() bool {
	return false
}

func (pself *Sprite) IsTriggerEnabled() bool {
	return false
}

func (pself *Sprite) IsUseGravity() bool {
	return false
}

func (pself *Sprite) MoveAndSlide() {
}

func (pself *Sprite) PauseAnim() {
}

func (pself *Sprite) PlayAnim(p_name string, p_speed float64, isLoop bool, p_revert bool) {
}

func (pself *Sprite) PlayBackwardsAnim(p_name string) {
}

func (pself *Sprite) SetAnim(p_name string) {
}

func (pself *Sprite) SetAnimCentered(p_center bool) {
}

func (pself *Sprite) SetAnimFlipH(p_flip bool) {
}

func (pself *Sprite) SetAnimFlipV(p_flip bool) {
}

func (pself *Sprite) SetAnimFrame(p_frame int64) {
}

func (pself *Sprite) SetAnimOffset(p_offset Vec2) {
}

func (pself *Sprite) SetAnimSpeedScale(p_speed_scale float64) {
}

func (pself *Sprite) SetChildPosition(path string, pos Vec2) {
}

func (pself *Sprite) SetChildRotation(path string, rot float64) {
}

func (pself *Sprite) SetChildScale(path string, scale Vec2) {
}

func (pself *Sprite) SetColliderCapsule(center Vec2, size Vec2) {
}

func (pself *Sprite) SetColliderCircle(center Vec2, radius float64) {
}

func (pself *Sprite) SetColliderPolygon(center Vec2, points Array) {
}

func (pself *Sprite) SetColliderRect(center Vec2, size Vec2) {
}

func (pself *Sprite) SetCollisionEnabled(enabled bool) {
}

func (pself *Sprite) SetCollisionLayer(layer int64) {
}

func (pself *Sprite) SetCollisionMask(mask int64) {
}

func (pself *Sprite) SetColor(color Color) {
}

func (pself *Sprite) SetDebugCollisionVisible(visible bool) {
}

func (pself *Sprite) SetDontDestroyOnLoad() {
}

func (pself *Sprite) SetDrag(drag float64) {
}

func (pself *Sprite) SetFriction(friction float64) {
}

func (pself *Sprite) SetGravity(gravity float64) {
}

func (pself *Sprite) SetGravityScale(scale float64) {
}

func (pself *Sprite) SetMass(mass float64) {
}

func (pself *Sprite) SetMaterialParams(effect string, amount float64) {
}

func (pself *Sprite) SetMaterialParamsColor(effect string, color Color) {
}

func (pself *Sprite) SetMaterialParamsVec(effect string, x float64, y float64, z float64, w float64) {
}

func (pself *Sprite) SetMaterialParamsVec4(effect string, vec4 Vec4) {
}

func (pself *Sprite) SetMaterialShader(path string) {
}

func (pself *Sprite) SetPhysicProcess(is_on bool) {
}

func (pself *Sprite) SetPhysicsMode(mode int64) {
}

func (pself *Sprite) SetPivot(pivot Vec2) {
}

func (pself *Sprite) SetPixelCollisionSamplingStep(step int64) {
}

func (pself *Sprite) SetPosition(pos Vec2) {
}

func (pself *Sprite) SetProcess(is_on bool) {
}

func (pself *Sprite) SetRenderScale(scale Vec2) {
}

func (pself *Sprite) SetRotation(rot float64) {
}

func (pself *Sprite) SetScale(scale Vec2) {
}

func (pself *Sprite) SetTexture(path string) {
}

func (pself *Sprite) SetTextureAtlas(path string, rect2 Rect2) {
}

func (pself *Sprite) SetTextureAtlasDirect(path string, rect2 Rect2) {
}

func (pself *Sprite) SetTextureDirect(path string) {
}

func (pself *Sprite) SetTriggerCapsule(center Vec2, size Vec2) {
}

func (pself *Sprite) SetTriggerCircle(center Vec2, radius float64) {
}

func (pself *Sprite) SetTriggerEnabled(trigger bool) {
}

func (pself *Sprite) SetTriggerLayer(layer int64) {
}

func (pself *Sprite) SetTriggerMask(mask int64) {
}

func (pself *Sprite) SetTriggerPolygon(center Vec2, points Array) {
}

func (pself *Sprite) SetTriggerRect(center Vec2, size Vec2) {
}

func (pself *Sprite) SetTypeName(type_name string) {
}

func (pself *Sprite) SetUseGravity(enabled bool) {
}

func (pself *Sprite) SetVelocity(velocity Vec2) {
}

func (pself *Sprite) SetVisible(visible bool) {
}

func (pself *Sprite) SetZIndex(z int64) {
}

func (pself *Sprite) StopAnim() {
}
