package ui

const (
	LAYOUT_MODE_POSITION int64 = iota
	LAYOUT_MODE_ANCHORS
	LAYOUT_MODE_CONTAINER
	LAYOUT_MODE_UNCONTROLLED
)
const (
	LAYOUT_DIRECTION_INHERITED int64 = iota
	LAYOUT_DIRECTION_LOCALE
	LAYOUT_DIRECTION_LTR
	LAYOUT_DIRECTION_RTL
)

const (
	PRESET_TOP_LEFT int64 = iota
	PRESET_TOP_RIGHT
	PRESET_BOTTOM_LEFT
	PRESET_BOTTOM_RIGHT
	PRESET_CENTER_LEFT
	PRESET_CENTER_TOP
	PRESET_CENTER_RIGHT
	PRESET_CENTER_BOTTOM
	PRESET_CENTER
	PRESET_LEFT_WIDE
	PRESET_TOP_WIDE
	PRESET_RIGHT_WIDE
	PRESET_BOTTOM_WIDE
	PRESET_VCENTER_WIDE
	PRESET_HCENTER_WIDE
	PRESET_FULL_RECT
)
