/*
------------------------------------------------------------------------------
//   This code was generated by template ffi_gdextension_interface.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_gdextension_interface.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------
*/
package engine

import (
	. "github.com/goplus/spbase/mathf"
)

var (
	AudioMgr      IAudioMgr
	CameraMgr     ICameraMgr
	DebugMgr      IDebugMgr
	ExtMgr        IExtMgr
	InputMgr      IInputMgr
	NavigationMgr INavigationMgr
	PenMgr        IPenMgr
	PhysicMgr     IPhysicMgr
	PlatformMgr   IPlatformMgr
	ResMgr        IResMgr
	SceneMgr      ISceneMgr
	SpriteMgr     ISpriteMgr
	TilemapMgr    ITilemapMgr
	UiMgr         IUiMgr
)

type IAudioMgr interface {
	StopAll()
	CreateAudio() Object
	DestroyAudio(obj Object)
	SetPitch(obj Object, pitch float64)
	GetPitch(obj Object) float64
	SetPan(obj Object, pan float64)
	GetPan(obj Object) float64
	SetVolume(obj Object, volume float64)
	GetVolume(obj Object) float64
	PlayWithAttenuation(obj Object, path string, owner_id Object, attenuation float64, max_distance float64) int64
	Play(obj Object, path string) int64
	Pause(aid int64)
	Resume(aid int64)
	Stop(aid int64)
	SetLoop(aid int64, loop bool)
	GetLoop(aid int64) bool
	GetTimer(aid int64) float64
	SetTimer(aid int64, time float64)
	IsPlaying(aid int64) bool
}

type ICameraMgr interface {
	GetCameraPosition() Vec2
	SetCameraPosition(position Vec2)
	GetCameraZoom() Vec2
	SetCameraZoom(size Vec2)
	GetViewportRect() Rect2
	GetGlobalCameraRect() Rect2
	SetCameraLimit(side int64, limit int64)
	SetCameraSmoothing(enabled bool)
}

type IDebugMgr interface {
	DebugDrawCircle(pos Vec2, radius float64, color Color)
	DebugDrawRect(pos Vec2, size Vec2, color Color)
	DebugDrawLine(from Vec2, to Vec2, color Color)
}

type IExtMgr interface {
	RequestExit(exit_code int64)
	RequestReset(exit_code int64)
	RequestRestart()
	OnRuntimePanic(msg string)
	Pause()
	Resume()
	IsPaused() bool
	NextFrame()
	SetLayerSorterMode(mode int64)
}

type IInputMgr interface {
	GetGlobalMousePos() Vec2
	GetKey(key int64) bool
	GetMouseState(mouse_id int64) bool
	GetKeyState(key int64) int64
	GetAxis(neg_action string, pos_action string) float64
	IsActionPressed(action string) bool
	IsActionJustPressed(action string) bool
	IsActionJustReleased(action string) bool
}

type INavigationMgr interface {
	SetupPathFinderWithSize(grid_size Vec2, cell_size Vec2, with_jump bool, with_debug bool)
	SetupPathFinder(with_jump bool)
	SetObstacle(obj Object, enabled bool)
	FindPath(p_from Vec2, p_to Vec2, with_jump bool) Array
}

type IPenMgr interface {
	DestroyAllPens()
	CreatePen() Object
	DestroyPen(obj Object)
	PenStamp(obj Object)
	MovePenTo(obj Object, position Vec2)
	PenDown(obj Object, move_by_mouse bool)
	PenUp(obj Object)
	SetPenColorTo(obj Object, color Color)
	ChangePenBy(obj Object, property int64, amount float64)
	SetPenTo(obj Object, property int64, value float64)
	ChangePenSizeBy(obj Object, amount float64)
	SetPenSizeTo(obj Object, size float64)
	SetPenStampTexture(obj Object, texture_path string)
}

type IPhysicMgr interface {
	Raycast(from Vec2, to Vec2, collision_mask int64) Object
	CheckCollision(from Vec2, to Vec2, collision_mask int64, collide_with_areas bool, collide_with_bodies bool) bool
	CheckTouchedCameraBoundaries(obj Object) int64
	CheckTouchedCameraBoundary(obj Object, board_type int64) bool
	SetCollisionSystemType(is_collision_by_alpha bool)
	SetGlobalGravity(gravity float64)
	GetGlobalGravity() float64
	SetGlobalFriction(friction float64)
	GetGlobalFriction() float64
	SetGlobalAirDrag(air_drag float64)
	GetGlobalAirDrag() float64
	CheckCollisionRect(pos Vec2, size Vec2, collision_mask int64) Array
	CheckCollisionCircle(pos Vec2, radius float64, collision_mask int64) Array
	RaycastWithDetails(from Vec2, to Vec2, ignore_sprites Array, collision_mask int64, collide_with_areas bool, collide_with_bodies bool) Array
}

type IPlatformMgr interface {
	SetStretchMode(enable bool)
	SetStretchAspect(is_keep bool)
	SetStretchContentScale(width int64, height int64)
	SetWindowPosition(pos Vec2)
	GetWindowPosition() Vec2
	SetWindowSize(width int64, height int64, with_content_scale bool)
	GetWindowSize() Vec2
	SetWindowTitle(title string)
	GetWindowTitle() string
	SetWindowFullscreen(enable bool)
	IsWindowFullscreen() bool
	SetDebugMode(enable bool)
	IsDebugMode() bool
	GetTimeScale() float64
	SetTimeScale(time_scale float64)
	GetPersistantDataDir() string
	SetPersistantDataDir(path string)
	IsInPersistantDataDir(path string) bool
}

type IResMgr interface {
	CreateAnimation(p_sprite_type string, p_anim_name string, p_json_ctx string, fps int64, is_atlas bool)
	SetLoadMode(is_direct_mode bool)
	GetLoadMode() bool
	GetBoundFromAlpha(p_path string) Rect2
	GetImageSize(p_path string) Vec2
	ReadAllText(p_path string) string
	HasFile(p_path string) bool
	ReloadTexture(path string)
	FreeStr(str string)
	SetDefaultFont(font_path string)
}

type ISceneMgr interface {
	ChangeSceneToFile(path string)
	DestroyAllSprites()
	ReloadCurrentScene() int64
	UnloadCurrentScene()
	ClearPureSprites()
	CreatePureSprite(texture_path string, pos Vec2, zindex int64)
	DestroyPureSprite(id Object)
	CreateRenderSprite(texture_path string, pos Vec2, degree float64, scale Vec2, zindex int64, pivot Vec2) Object
	CreateStaticSprite(texture_path string, pos Vec2, degree float64, scale Vec2, zindex int64, pivot Vec2, collider_type int64, collider_pivot Vec2, collider_params Array) Object
}

type ISpriteMgr interface {
	SetDontDestroyOnLoad(obj Object)
	SetProcess(obj Object, is_on bool)
	SetPhysicProcess(obj Object, is_on bool)
	SetTypeName(obj Object, type_name string)
	SetPivot(obj Object, pivot Vec2)
	GetPivot(obj Object) Vec2
	SetChildPosition(obj Object, path string, pos Vec2)
	GetChildPosition(obj Object, path string) Vec2
	SetChildRotation(obj Object, path string, rot float64)
	GetChildRotation(obj Object, path string) float64
	SetChildScale(obj Object, path string, scale Vec2)
	GetChildScale(obj Object, path string) Vec2
	CheckCollision(obj Object, target Object, is_src_trigger bool, is_dst_trigger bool) bool
	CheckCollisionWithPoint(obj Object, point Vec2, is_trigger bool) bool
	CreateBackdrop(path string) Object
	CreateSprite(path string, pos Vec2) Object
	CloneSprite(obj Object) Object
	DestroySprite(obj Object) bool
	IsSpriteAlive(obj Object) bool
	SetPosition(obj Object, pos Vec2)
	GetPosition(obj Object) Vec2
	SetRotation(obj Object, rot float64)
	GetRotation(obj Object) float64
	SetScale(obj Object, scale Vec2)
	GetScale(obj Object) Vec2
	SetRenderScale(obj Object, scale Vec2)
	GetRenderScale(obj Object) Vec2
	SetColor(obj Object, color Color)
	GetColor(obj Object) Color
	SetMaterialShader(obj Object, path string)
	GetMaterialShader(obj Object) string
	SetMaterialParams(obj Object, effect string, amount float64)
	GetMaterialParams(obj Object, effect string) float64
	SetMaterialParamsVec(obj Object, effect string, x float64, y float64, z float64, w float64)
	SetMaterialParamsVec4(obj Object, effect string, vec4 Vec4)
	GetMaterialParamsVec4(obj Object, effect string) Vec4
	SetMaterialParamsColor(obj Object, effect string, color Color)
	GetMaterialParamsColor(obj Object, effect string) Color
	SetTextureAltas(obj Object, path string, rect2 Rect2)
	SetTexture(obj Object, path string)
	SetTextureAltasDirect(obj Object, path string, rect2 Rect2)
	SetTextureDirect(obj Object, path string)
	GetTexture(obj Object) string
	SetVisible(obj Object, visible bool)
	GetVisible(obj Object) bool
	GetZIndex(obj Object) int64
	SetZIndex(obj Object, z int64)
	PlayAnim(obj Object, p_name string, p_speed float64, isLoop bool, p_revert bool)
	PlayBackwardsAnim(obj Object, p_name string)
	PauseAnim(obj Object)
	StopAnim(obj Object)
	IsPlayingAnim(obj Object) bool
	SetAnim(obj Object, p_name string)
	GetAnim(obj Object) string
	SetAnimFrame(obj Object, p_frame int64)
	GetAnimFrame(obj Object) int64
	SetAnimSpeedScale(obj Object, p_speed_scale float64)
	GetAnimSpeedScale(obj Object) float64
	GetAnimPlayingSpeed(obj Object) float64
	SetAnimCentered(obj Object, p_center bool)
	IsAnimCentered(obj Object) bool
	SetAnimOffset(obj Object, p_offset Vec2)
	GetAnimOffset(obj Object) Vec2
	SetAnimFlipH(obj Object, p_flip bool)
	IsAnimFlippedH(obj Object) bool
	SetAnimFlipV(obj Object, p_flip bool)
	IsAnimFlippedV(obj Object) bool
	GetCurrentAnimName(obj Object) string
	SetVelocity(obj Object, velocity Vec2)
	GetVelocity(obj Object) Vec2
	IsOnFloor(obj Object) bool
	IsOnFloorOnly(obj Object) bool
	IsOnWall(obj Object) bool
	IsOnWallOnly(obj Object) bool
	IsOnCeiling(obj Object) bool
	IsOnCeilingOnly(obj Object) bool
	GetLastMotion(obj Object) Vec2
	GetPositionDelta(obj Object) Vec2
	GetFloorNormal(obj Object) Vec2
	GetWallNormal(obj Object) Vec2
	GetRealVelocity(obj Object) Vec2
	MoveAndSlide(obj Object)
	SetGravity(obj Object, gravity float64)
	GetGravity(obj Object) float64
	SetMass(obj Object, mass float64)
	GetMass(obj Object) float64
	AddForce(obj Object, force Vec2)
	AddImpulse(obj Object, impulse Vec2)
	SetPhysicsMode(obj Object, mode int64)
	GetPhysicsMode(obj Object) int64
	SetUseGravity(obj Object, enabled bool)
	IsUseGravity(obj Object) bool
	SetGravityScale(obj Object, scale float64)
	GetGravityScale(obj Object) float64
	SetDrag(obj Object, drag float64)
	GetDrag(obj Object) float64
	SetFriction(obj Object, friction float64)
	GetFriction(obj Object) float64
	SetCollisionLayer(obj Object, layer int64)
	GetCollisionLayer(obj Object) int64
	SetCollisionMask(obj Object, mask int64)
	GetCollisionMask(obj Object) int64
	SetTriggerLayer(obj Object, layer int64)
	GetTriggerLayer(obj Object) int64
	SetTriggerMask(obj Object, mask int64)
	GetTriggerMask(obj Object) int64
	SetColliderRect(obj Object, center Vec2, size Vec2)
	SetColliderCircle(obj Object, center Vec2, radius float64)
	SetColliderCapsule(obj Object, center Vec2, size Vec2)
	SetCollisionEnabled(obj Object, enabled bool)
	IsCollisionEnabled(obj Object) bool
	SetTriggerRect(obj Object, center Vec2, size Vec2)
	SetTriggerCircle(obj Object, center Vec2, radius float64)
	SetTriggerCapsule(obj Object, center Vec2, size Vec2)
	SetTriggerEnabled(obj Object, trigger bool)
	IsTriggerEnabled(obj Object) bool
	CheckCollisionByColor(obj Object, color Color, color_threshold float64, alpha_threshold float64) bool
	CheckCollisionByAlpha(obj Object, alpha_threshold float64) bool
	CheckCollisionWithSpriteByAlpha(obj Object, obj_b Object, alpha_threshold float64) bool
}

type ITilemapMgr interface {
	OpenDrawTilesWithSize(tile_size int64)
	OpenDrawTiles()
	SetLayerIndex(index int64)
	SetTile(texture_path string, with_collision bool)
	SetTileWithCollisionInfo(texture_path string, collision_points Array)
	SetLayerOffset(index int64, offset Vec2)
	GetLayerOffset(index int64) Vec2
	PlaceTiles(positions Array, texture_path string)
	PlaceTilesWithLayer(positions Array, texture_path string, layer_index int64)
	PlaceTile(pos Vec2, texture_path string)
	PlaceTileWithLayer(pos Vec2, texture_path string, layer_index int64)
	EraseTile(pos Vec2)
	EraseTileWithLayer(pos Vec2, layer_index int64)
	GetTile(pos Vec2) string
	GetTileWithLayer(pos Vec2, layer_index int64) string
	CloseDrawTiles()
	ExitTilemapEditorMode()
}

type IUiMgr interface {
	BindNode(obj Object, rel_path string) Object
	CreateNode(path string) Object
	CreateButton(path string, text string) Object
	CreateLabel(path string, text string) Object
	CreateImage(path string) Object
	CreateToggle(path string, value bool) Object
	CreateSlider(path string, value float64) Object
	CreateInput(path string, text string) Object
	DestroyNode(obj Object) bool
	GetType(obj Object) int64
	SetText(obj Object, text string)
	GetText(obj Object) string
	SetTexture(obj Object, path string)
	GetTexture(obj Object) string
	SetColor(obj Object, color Color)
	GetColor(obj Object) Color
	SetFontSize(obj Object, size int64)
	GetFontSize(obj Object) int64
	SetVisible(obj Object, visible bool)
	GetVisible(obj Object) bool
	SetInteractable(obj Object, interactable bool)
	GetInteractable(obj Object) bool
	SetRect(obj Object, rect Rect2)
	GetRect(obj Object) Rect2
	GetLayoutDirection(obj Object) int64
	SetLayoutDirection(obj Object, value int64)
	GetLayoutMode(obj Object) int64
	SetLayoutMode(obj Object, value int64)
	GetAnchorsPreset(obj Object) int64
	SetAnchorsPreset(obj Object, value int64)
	GetScale(obj Object) Vec2
	SetScale(obj Object, value Vec2)
	GetPosition(obj Object) Vec2
	SetPosition(obj Object, value Vec2)
	GetSize(obj Object) Vec2
	SetSize(obj Object, value Vec2)
	GetGlobalPosition(obj Object) Vec2
	SetGlobalPosition(obj Object, value Vec2)
	GetRotation(obj Object) float64
	SetRotation(obj Object, value float64)
	GetFlip(obj Object, horizontal bool) bool
	SetFlip(obj Object, horizontal bool, is_flip bool)
}
