name: Test Godot project
description: Run the test Godot project.
runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: go build -v $(go list ./... | grep -v /internal/webffi)

    - name: Test
      shell: bash
      run: go test -v $(go list ./... | grep -v /internal/webffi)

    - name: GenGo
      shell: bash
      run: gop go ./...

    - name: Run test demo
      shell: bash
      run: spx run -path="test/CI" -headless=true &> cilog.txt

    - name: Check test result
      shell: bash
      run: |
        if grep -q "===>SpxCIRunSucc" cilog.txt; then
          echo "test success"
          rm -f cilog.txt
        else
          echo "test failed: not found success mark"
          cat cilog.txt
          rm -f cilog.txt
          exit 1
        fi