name: Build Windows

on:
  workflow_call:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:

  build:
    name: Build Windows
    runs-on: "windows-latest"
    steps:
    - name: Check out code
      uses: actions/checkout@v7

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain

    - name: Set up toolchain and engine assets
      uses: ./.github/actions/deps

    - name: Run project test
      uses: ./.github/actions/project-test
