name: 🔗 GHA
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  test:
    name: 🧪 Test
    uses: ./.github/workflows/test.yml

  android-build:
    needs: test
    name: 🤖 Android
    uses: ./.github/workflows/build_android.yml

  ios-build:
    needs: test
    name: 🍏 iOS
    uses: ./.github/workflows/build_ios.yml

  web-build:
    needs: test
    name: 🌐 Web
    uses: ./.github/workflows/build_web.yml

  linux-build:
    needs: test
    name: 🐧 Linux
    uses: ./.github/workflows/build_linux.yml

  macos-build:
    needs: test
    name: 🍎 macOS
    uses: ./.github/workflows/build_macos.yml

  windows-build:
    needs: test
    name: 🏁 Windows
    uses: ./.github/workflows/build_windows.yml


  # Third stage: Run auxiliary tests using build artifacts from previous jobs.

  # Can be turned off for PRs that intentionally break compat with godot-cpp,
  # until both the upstream PR and the matching godot-cpp changes are merged.
