name: Static Checks

on:
  workflow_call:

jobs:
  static-checks:
    name: static-checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.x
          cache-dependency-path: |
            go.sum

      - name: Download Go modules
        run: go mod download

      - name: Check out Godot source
        run: git clone --depth 1 --branch spx4.4.1 https://github.com/goplus/godot.git godot

      - name: Run binding code generation
        run: cd internal/cmd/codegen && GODOT_SRC="$GITHUB_WORKSPACE/godot" go run .

      - name: Run go generate for pkg/ispx
        run: go generate ./pkg/ispx/...

      - name: Ensure working tree is clean
        run: git diff --exit-code

      - name: Test Go code
        run: go test -v $(go list ./... | grep -v /internal/webffi)
